### ISSUE TITLE
[seo-magic] An exception has been thrown during the rendering of a template ("Idle timeout reached

### ISSUE THREAD

**Issue by ptarmic** [getgrav/grav-premium-issues#1]
I am getting a timeout error from `/user/plugins/seo-magic/templates/forms/fields/sitemap-check/sitemap-check.html.twig` 
"An exception has been thrown during the rendering of a template ("Idle timeout reached for "http://XXXXX.com/sitemap.xml".")."
 
![Screenshot_2020-12-16 Crikey There was an error (1)](https://user-images.githubusercontent.com/72616419/102369665-1d1c7700-3fb4-11eb-916f-a59086e1b532.png)

When trying to open the plugin settings in the admin panel, disabling the plugin and when I try to save a page in the admin plugin on my dev site. This site is developed on goormIDE which is an online IDE, I don't know of any restrictions on the platform but I can't rule out this error could stem from a platform issue.

The error lists a url to the sitemap which opens just fine in the browser. The error (and the links in the sitemap) use http:// the site itself is under https://. 

A few fields such as the sitemap urls, cannonical and meta property="og:url and canonical have always been different from the actual site url (previously the url also contained the port number which went away when I changed the port of the site to 443) but as this has not had any effect on the site, I ignored it. This discrepency does not occur on the live site which is hosted with a different provider.

I have attached the user folder, let me know if you need anything else. I've taken the "pages" folder out to make it under the attachment limit, let me know if they are needed.

**Comment by rhukster** [comment]
@ptarmic I also need the `pages/` folder to finish setting things up locally.  Cheers!

**Comment by rhukster** [comment]
For those finding this issue. It appears to be directly related to limitations in place due to the online editor which has its own vm for running grav.
