### ISSUE TITLE
Feature request: Static content in sidebar

### ISSUE THREAD

**Issue by sebastian0119** [getgrav/grav-premium-issues#10]
In the former quark template, one could add static, complementary content into the side bar by using a `modules/sidebar/default.md` file

Trying the same with typhoon does not work and having a quick lock at the `sidebar.html.twg`, it is probably not so easy because of the flexbox classes.

Just a "nice to have"  ;)

**Comment by rhukster** [comment]
I didn't think anyone used that so I removed it in Typhoon.  It's actually pretty easy to add. It could either be in 'documentation' about how to add things like that, or I could do it the same way as was done in Typhoon and just import a page if it exists and is populated.

**Comment by sebastian0119** [comment]
Thanks for the reply and yes, you are actually right. I am not able to match it perfectly, but for the time being I did the following:

I added another `div`, like this:

    <div class="sidebar-content">
        {{ page.find('/modules/sidebar').content|raw }}
    </div>

The `page.find` is the same as in quarks. I added the `div` for consistency, as it is for the rest  of the items in the partial.

Formatting however does not match perfectly: all items in the partial are `<h4 class="text-xl font-bold mt-2 mb-1">`.

But when adding a h4 in markdown, it is not formatted correctly, because it's just the `<h4>` tag, without the classes.

The nice thing with the markdown file was that it was not overwritten when the theme was updated. Right now, I expect that any manual modification in the `sidebar.html.twig` will be lost, when this file is updated, correct?

Thanks in advane

**Comment by rhukster** [comment]
That is correct.  I will add the code back to look for this file and use it so it should still work with the next update.  As it will essentially be the same as yours.  

One thing to do to solve the header issue is to use shortcode for h4 which takes classes as an option.  You could just use an html h4 also but I prefer to stick to shoe codes as they are nextgen editor compatible.

**Comment by sebastian0119** [comment]
Shortcode seems to do the trick, but curiously the `<h4>` gets enclosed by some `<p>...</p>`.

Check it out - this is the `default.md` I am using

    ---
    routable: false
    ---
    [h4 class="text-xl font-bold mt-2 mb-1"]Accesos directos[/h4]

    Just trying

And the output looks like this:

    <div class="sidebar-content">
        <p><h4 class="text-xl font-bold mt-2 mb-1">Accesos directos</h4></p>
         ^ here                                                  and here ^
        <p>Just trying</p>
    </div>

**Comment by w00fz** [comment]
Are you casting `|markdown` on that content in the twig template? If so you might need `.content|markdown(false)|raw`

**Comment by rhukster** [comment]
It's the h4 shortcode.  I'll check on this tomorrow, it could be a bug in shortcode-core.

**Comment by sebastian0119** [comment]
> Are you casting `|markdown` on that content in the twig template? If so you might need `.content|markdown(false)|raw`

Nope, I'm not casting `|markdown`.

**Comment by rhukster** [comment]
Ok I've looked into this.  The way that markdown handles things, and the way that shortcodes are interpreted means that using the `[h4][/h4]` shorcode:

```markdown
[h4]Title[/h4]
```

is treated as **inline** and markdown renders as:

```html
<p>
  <h4>TItle</h4>
</p>
```

Which is not valid.  However:

```markdown
[h4]
Title
[/h4]
```

is treated as **block** and markdown renders as:

```html
<h4>
  <p>TItle</p>
</h4>
```

Which is valid, but has the side effects of `<p>` tags having margins and such causing extra spacing.  However, if you wrap the shortcode in the first example in an HTML `<div>` then markdown will not mess with it:

```markdown
<div>
[h4]Title[/h4]
</div>
```

So this renders as:

```html
<div>
  <h4>TItle</h4>
</div>
```

Which is valid and has no unintended side effects, except an empty div that does nothing.  At this point you might as well just put the following in the markdown:

```markdown
<h4>TItle</h4>
```

That way you don't get any extra divs, and it doesn't render with any internal or external `<p></p>` tags.

**Comment by rhukster** [comment]
BTW i've added the sidebar logic for next release

**Comment by sebastian0119** [comment]
> At this point you might as well just put the following in the markdown:
> 
> ```gfm
> <h4>TItle</h4>
> ```
> 
> That way you don't get any extra divs, and it doesn't render with any internal or external `<p></p>` tags.

Just a last, minor comment:
At some point we sidetracked to the `[h4]` shortcode. When using normal HTML tags, one must use 

```gfm
<h4 class="text-xl font-bold mt-2 mb-1">Title</h4>
```

in order to have the **Title** displayed correctly. When using pure `<h4>` as you suggested, without the `class="..."`, the title will not match the appearance of the remaining `<h4>` titles of the sidebar (e.g. for popular tags, archive, etc.)
