### ISSUE TITLE
[typhoon] Theme labels are not displayed after installing theme

### ISSUE THREAD

**Issue by kiranetph** [getgrav/grav-premium-issues#100]
![2021-05-16_12-28-10](https://user-images.githubusercontent.com/15226809/118385554-6136a500-b642-11eb-9f18-6cbe7a5bce85.jpg)

**Comment by rhukster** [comment]
The theme has to be active to see the translations. This is actually a big in admin plugin and it’s fixed in GitHub just not released yet.

**Comment by kiranetph** [comment]
activating solves it. 
thanks
