### ISSUE TITLE
[seo-magic] Page saved but not generating SEO Magic Data from admin for other language

### ISSUE THREAD

**Issue by ptarmic** [getgrav/grav-premium-issues#101]
On the secondary languge page in the admin panel, I press save and it keeps telling me ` SEO Magic Data has not been generated for this page,` I have added Meta Description and saved, that text has saved but still getting the not generated error. On the dev site I ran seo magic from the command line and that worked but I don't have command line access on the live server.

![Screenshot_2021-05-17 صفحه اصلی ( fa ) JAAM Productions eLearning Content Development Specialists(1)](https://user-images.githubusercontent.com/72616419/118483886-7aa52300-b70e-11eb-94bb-e0b4b9815bcd.png)

EDIT: No errors in the log

**Comment by rhukster** [comment]
Is it possible to get a zip of the 'page' folder in question? The one that has the multiple `.md` files in it? 

It is probably something related to the URL of the translated page not matching the URL in the sitemap so it' can't be found, and therefor not generated, but i'm not sure what exactly would cause that, so hopefully your page configuration can shed some light on it.

Cheers!

**Comment by rhukster** [comment]
I have a fix for this in `seo-magic.php` just change the `$url = ...` line to match below (around line 278):

```php
        if ($obj instanceof PageInterface && $obj->routable() && $obj->published() && is_null($obj->redirect())) {
            $url = $obj->url(true, true, true);
            SEOGenerator::processSEOData($url);
        }
```

**Comment by ptarmic** [comment]
Its working perfectly now. Thanks a lot for fixing it so fast!
