### ISSUE TITLE
[Nextgen-editor] HTML insert breaks on complex links

### ISSUE THREAD

**Issue by sp0ken** [getgrav/grav-premium-issues#103]
Hi,

I'm trying to insert a fairly long html snippet with a mailto link and urlencoded texts. 
Here is the precise HTML
```<table style="border-collapse: separate; width: 100%; line-height: 100%;  " cellspacing="0" cellpadding="0" border="0"><tbody><tr><td style="border-radius: 3px; cursor: auto;  background-color: #3da018; border-collapse: collapse;   border: none;" valign="middle" bgcolor="#3da018" align="center"><a href="https://wa.me/?text=Bonjour%20!%20%0D%0A%20%0D%0AGr%C3%A2ce%20%C3%A0%20mon%20parrainage%2C%20profite%20de%20ton%20incroyable%20offre%20Tediber%20%3A%20%0D%0APour%20un%20matelas%20Tediber%20double%20achet%C3%A9%20(ou%20pour%20tout%20achat%20sup%C3%A9rieur%20ou%20%C3%A9gal%20%C3%A0%20600%20euros)%2C%20un%20incroyable%20prot%C3%A8ge-matelas%20est%20offert%20(valeur%20de%2065%20%C3%A0%2090%20euros).%20%0D%0A%20%0D%0APour%20en%20profiter%20%3A%20ajoute%20tes%20produits%20au%20panier%20ainsi%20que%20le%20prot%C3%A8ge-matelas%20de%20la%20taille%20de%20ton%20choix%20sur%20http%3A%2F%2Fbit.ly%2Ftediber-parrainage%2C%20saisis%20le%20code%20%20et%20ton%20adresse%20email%20dans%20les%20champs%20pr%C3%A9vus%20%C3%A0%20cet%20effet%20et%20hop%2C%20ton%20prot%C3%A8ge-matelas%20est%20offert%20!%20(Offre%20r%C3%A9serv%C3%A9e%20aux%20nouveaux%20clients)%20%0D%0A%20%0D%0AA%20bient%C3%B4t%20!&amp;__s=xxxxxxx&amp;utm_source=drip&amp;utm_medium=email&amp;utm_campaign=Parrainez+vos+incroyables+ami.e.s+%21" style="display: inline-block; background-color: #3da018; color: #ffffff; font-family: Arial; font-size: 20px; font-weight: normal; line-height: 1.2; text-decoration: none; text-transform: none;  border-radius: 3px; margin: 0; padding: 12px 24px;" target="_blank"><span style="font-weight: bold;">ENVOYER PAR WHATSAPP</span></a></td></tr></tbody></table>```

It gets properly displayed in the admin 
<img width="946" alt="Capture d’écran 2021-05-26 à 17 12 45" src="https://user-images.githubusercontent.com/4200473/119685666-d9bd1300-be45-11eb-879c-c3328e34ee8c.png">

And breaks completely as soon as it gets saved
<img width="543" alt="Capture d’écran 2021-05-26 à 17 16 38" src="https://user-images.githubusercontent.com/4200473/119686006-31f41500-be46-11eb-9ad6-58e84e4aac21.png">

**Comment by w00fz** [comment]
Hello @sp0ken , I can't replicate this issue. This is what I did:

1. Created a new HTML Snippet and pasted your code (make sure you hit the ✅ to confirm)
2. Saved the page
3. Loaded frontend and the button showed up properly... I then tried to click the whatsapp link and it opened fine.

If you tried to paste this code inside the editor without the HTML snippet, then that would not work, it would try to convert it into a Markdown link which is not what you are trying to do.

Here is a screenshot I took for each of the steps above.

<img width="1195" alt="w00fz-2021-05-27_@_11 21 56@2x" src="https://user-images.githubusercontent.com/11734/119877725-3bc95700-bede-11eb-8f78-ccce2c9fbf61.png">

<img width="982" alt="w00fz-2021-05-27_@_11 20 59@2x" src="https://user-images.githubusercontent.com/11734/119877734-3ec44780-bede-11eb-9c96-7720e616d7cf.png">

<img width="926" alt="w00fz-2021-05-27_@_11 20 31@2x" src="https://user-images.githubusercontent.com/11734/119877745-41bf3800-bede-11eb-868c-dcd41c874d8b.png">

**Comment by sp0ken** [comment]
Hi @w00fz,

I've tried again and I'm still getting the issue. You can see it [here](https://mag.tediber.com/devenez-un-incroyable-parrain).
We're using Nextgen-editor version 1.1.2 and Grav version 1.6.31 if it changes something.

**Comment by sp0ken** [comment]
Here is what I was seeing:
<img width="739" alt="Capture d’écran 2021-05-28 à 17 23 49" src="https://user-images.githubusercontent.com/4200473/120006829-91365e80-bfd9-11eb-97df-12c833590249.png">
After a few tests it seems that it was a cache issue on our side.
Thanks again for your help @w00fz
