### ISSUE TITLE
[typhoon] Missing logout button

### ISSUE THREAD

**Issue by kiranetph** [getgrav/grav-premium-issues#105]
I miss a logout button in typhoon. 
When you implement this feature request, maybe you can consider at the same time avatar support.
This is, what I use in Quark:
```
{% set user = grav.accounts.load(grav.user.username) %}
<img class="avatar" src="{{ url(user.getAvatarImage().cropResize(50, 50).url()) }}"> 
{% if data.avatar %}
  <label><img src="{{ base_url_simple ~ '/' ~ (data.avatar|first).path }}" /></label> 
{% else %}
  <label><img src="https://www.gravatar.com/avatar/{{ data.email|md5 }}?s=200" /></label> 
{% endif %}
```
 Even better if the avatar can have an optional link to the user_profile ...
Thank you for listening.

**Comment by rhukster** [comment]
I have implemented something similar for a client project that used Typhoon. I need to work out how best to add this back into Typhoon.

**Comment by rhukster** [comment]
This has been integrated into the menu system now.
