### ISSUE TITLE
[typhoon] simplesearch not working as expected on blog page

### ISSUE THREAD

**Issue by j0nnymoe** [getgrav/grav-premium-issues#106]
We seem to be having a slight issue with simplesearch within grav. the live results and click on them works fine but when searching then pressing enter to get a page of results, it spits back everything: https://grav.spad.uk/blog (Using search term `fail2ban` as an example).

The expected results should be: https://grav.spad.uk/search/query:fail2ban but the actual return is: https://grav.spad.uk/blog?searchfield=fail2ban

Disabled the anchor plugin as requested from discord but still no luck. Confirmed an issue on the demo site by @w00fz.

**Comment by rhukster** [comment]
In the `templates/partials/simplesearch_searchbox.html.twig` try replacing the form definition with this:

```twig
<form name="search" action="{{ url('/search') }}" data-simplesearch-form>
    <input
            x-ref="query"
            x-model="query"
            @focus="search($event, $dispatch)"
            @input="search($event, $dispatch)"
            name="query"
            class="search-input"
            type="text"
            {% if min_chars > 0 %} min="{{- min_chars -}}" {% endif %}
            required
            placeholder="{{ "PLUGIN_SIMPLESEARCH.SEARCH_PLACEHOLDER"|t }}"
            value="{{ query|e }}"
            {% if sidebar %}autocomplete="off"{% endif %}
            data-search-invalid="{{ "PLUGIN_SIMPLESEARCH.SEARCH_FIELD_MINIMUM_CHARACTERS"|t(min_chars)|raw }}"
    />
    {% if config.plugins.simplesearch.display_button %}
      <button type="submit" class="search-submit">
        <img src="{{ url('plugin://simplesearch/assets/search.svg') }}"/>
      </button>
    {% endif %}
  </form>
```

**Comment by j0nnymoe** [comment]
Thanks for the code, applying that seems to have worked but now it's knocked out our RSS/Atom buttons next to the search box. Any idea's which part is causing that?

Thanks

**Comment by Roxedus** [comment]
These changes brought search back, it also works with the feed buttons @j0nnymoe was referencing, now that I have ported those to the new code.

**Comment by rhukster** [comment]
I suspect you either deleted or moved the rss/atom icons in the sidebar? 

```twig
  {% if config.plugins.feed.enabled %}
    <div class="sidebar-content syndicate">
      <h4 class="text-xl font-bold mt-2 mb-1">{{ 'THEME_TYPHOON.SIDEBAR.SYNDICATE.HEADLINE'|t }}</h4>
      {% set rss_icon = svg_icon('tabler/rss.svg', 'w-5 inline-block algin-middle') %}
      <a class="btn mb-4" href="{{ feed_url }}.atom">{{ rss_icon|raw }} <span class="ml-1 align-middle">Atom</span></a>
      <a class="btn mb-4" href="{{ feed_url }}.rss">{{ rss_icon|raw }} <span class="ml-1 align-middle">RSS</span></a>
      {% if config.plugins.feed.enable_json_feed %}<a class="btn" href="{{ feed_url }}.json"><i
                class="fa fa-rss-square"></i> JSON</a>{% endif %}
    </div>
  {% endif %}
```

**Comment by rhukster** [comment]
oh seems you already worked that out.  Closing.
