### ISSUE TITLE
[seo-magic] Tab only visible for published pages (question)

### ISSUE THREAD

**Issue by bnjmnhssnn** [getgrav/grav-premium-issues#107]
The SEO Magic tab is only visible when the page is published. I guess this behaviour is intentionally and cannot be changed?

**Comment by rhukster** [comment]
Yes it's only visible for 'published' pages because it has to crawl the site to generate the SEO report.  Thinking about it though I might be able to move that logic to just the SEO report sub-tab.  I will get back to you.

Cheers.

**Comment by rhukster** [comment]
v2.0.1 released with this fix.

**Comment by bnjmnhssnn** [comment]
Thanks for the super fast response & fix
