### ISSUE TITLE
[typhoon] How to create a grid using Lightbox Gallery with Typhoon theme?

### ISSUE THREAD

**Issue by key-notes** [getgrav/grav-premium-issues#109]
Hello,

According to the [Lightbox Gallery docs](https://getgrav.org/premium/lightbox-gallery/docs), "The Typhoon theme already provides a modular Twig template that provides a clean grid layout for thumbnails."

However, I’m using the Typhoon theme yet the grid layout does not appear. Instead, thumbnails are listed vertically.

I tried switching the page template to “Modular” but then nothing appears at all—no gallery, nothing.

Also, if I use this code from the docs:

`[lightbox image="red-dbs-1.jpg" gallery="gallery1" class="inline-block" desc=".dbs-1"]`
    `![Red DBS - 1](red-dbs-1.jpg?cropZoom=200,200)`
`[/lightbox]`

`[lightbox image="red-dbs-2.jpg" gallery="gallery1" class="inline-block" desc=".dbs-2"]`
    `![Red DBS - 2](red-dbs-2.jpg?cropZoom=200,200)`
`[/lightbox]`

... the rendered page simply shows "`![Red DBS - 1](red-dbs-1.jpg?cropZoom=200,200)`" and "`![Red DBS - 2](red-dbs-2.jpg?cropZoom=200,200)`" rather than actual thumbnails, even though I have the Shortcode Core plugin installed and enabled. (Of course, I've replaced the sample image references with my actual images which I've uploaded to that page.)

I’m afraid the documentation could really use more detail, and live, working examples on the documentation page would be extremely helpful.

Could anyone kindly provide the exact code, including all settings (page template, etc.), to make the lightbox work as it’s supposed to by default in the Typhoon theme? As a brand new user to Grav, some very basic hand holding would be greatly appreciated (e.g., “Enter this ____ in this box: ____”). The more detail, the better.

Thanks so much in advance for any assistance.

**Comment by rhukster** [comment]
You can how the built in `modular/gallery.html.twig` template can be used by examining the `typhoon-onepage` skeleton:

<img width="1307" alt="CleanShot 2021-06-11 at 13 43 39@2x" src="https://user-images.githubusercontent.com/1084697/121740940-0e260580-cabb-11eb-8f19-31300065d8e0.png">

You can download this via the Docs: https://getgrav.org/premium/typhoon/docs#skeleton-packages

Look in the `user/templates/typhoon/templates/modular/gallery.html.twig` template for the Twig/Tailwind code that renders the modular page `user/pages/01.home/05._gallery/gallery.md`.

You can also see how to add your own CSS to create a similar layout as Typhoon provides: https://getgrav.org/premium/lightbox-gallery/docs#displaying-a-gallery-of-thumbnails

Hope this info helps.

**Comment by key-notes** [comment]
Thanks for your quick reply. Yes, the lighbox plugin is indeed correctly installed and enabled. It does work for some shortcode such as this:

`[lightbox image="fledermaus1.jpeg" zoomable="false" draggable="false" gallery="Adele"]`
`![Fledermaus](fledermaus1.jpeg?cropZoom=200,200)`
`[/lightbox]`

I downloaded the skeleton package and copied gallery.md and the images to a new page on my installed site, but no images appear. I should mention I'm using the admin backend. Apologies if this is frustrating to experienced users, but as someone completely new to Grav (but not to programming or to web development or to flat file CMSs), literally the simplest of the simple would be extremely welcome: "Click here: ____ Paste this code: ____."

Currently the gallery.md page which I copied to my installed Grav site, along with all the image files, just shows this text:

"This gallery module takes advantage of the new premium Lightbox Gallery plugin for Grav. This is a very flexible and configurable plugin which supports a variety of uses including markdown lightbox, shortcode, and twig."

The images do appear in "Page Media," but they don't appear on the actual rendered page. I'm really quite lost at this point. I'm sure I'll get the hang of it soon, but I could really use more hand holding to get me through the onboarding stage. Thanks so much in advance.

**Comment by key-notes** [comment]
Looks like the whole gallery is defined in the frontmatter in gallery.md. How can we display the actual gallery on the page then?

**Comment by key-notes** [comment]
Would anyone be willing to create a walkthrough video showing how to add a lightbox gallery to the Typhoon theme? I can get individual images to display, each on its own row, but there's no grid, despite the documentation saying that "The Typhoon theme already provides a modular Twig template that provides a clean grid layout for thumbnails."

It seems the lightbox plugin documentation is missing the critical information to make this work. It just says the grid is there by default in the Typhoon theme, but nowhere does it say how to actually get it working.

**Comment by key-notes** [comment]
Okay, looks like I finally got it: Apparently the grid view only works when defining the page as "modular."

Is there any way to display a grid on pages without having to define those pages as modular? Can this work on "normal" pages?

**Comment by rhukster** [comment]
If you are talking about 'regular' pages being just plain content pages and then using shortcodes to render the lightbox parts, then technically yes, but it will involve you adding a bunch of classes to each of the shortcodes.  

Alternatively you could wrap the lightbox shortcodes in a `[div class="lightbox-gallery-wrapper"][/div]` shortcode so a you get a div surrounding everything.  Then you would have to add custom CSS to rendering everything inside `.ligthbox-gallery-wrapper` in a similar way to the modular layout.

I wouldn't advise doing this for more than the most basic of scenarios.

**Comment by key-notes** [comment]
Thanks very much for your help. Looks like I'll stick with modular pages in that case. It should be easy enough to generate the text files and fill in the image filenames—this is much faster than using the GUI backend when working with many images and galleries. This is one reason I really like flat file CMSs.

**Comment by key-notes** [comment]
Incidentally, I may have discovered a bug in the current version of the lightbox plugin: If no title is entered for images, the titles appears to revert to whatever the most recent title is. For example, if you have "Image 1," "Image 2," Image 3," etc., yet only title "Image 1" and leave the others blank ("title: null" in the frontmatter), all subsequent images will render as "Image 1."

**Comment by rhukster** [comment]
does sound like a bug, probably a variable not getting reset.  I'll check that out.

**Comment by rhukster** [comment]
in the `templates/modular/gallery.html.twig` i changed the loop to have:

```twig
    {% for item in data.items %}
      <div class="inline-flex overflow-hidden rounded-md group safari-corner-overflow-fix">
        {% set item_image = page.media[item.image] %}
        {% set title = item.title ?: null %}
        {% set desc = item.desc ? ".desc-" ~ md5(item.desc) : null %}
        {% set content = item_image.cropZoom(thumb_width,thumb_height).classes('transform duration-200 group-hover:scale-110 group-hover:filter group-hover:brightness-110').html(title, title) %}
        {% if item.video %}
          {% set video = item.video %}
          {% set image = null %}
        {% else %}
          {% set image = item.image %}
          {% set video = null %}
        {% endif %}
        {% set class = 'inline-block' %}
        {% include "partials/lightbox.html.twig" %}
      </div>
    {% endfor %}
```

**Comment by mfuggle** [comment]
I am in the same situation as key-notes but a year later. I want to use the Typhoon Blog skeleton which I have successfully installed (I have also installed Onepage and Rocket skeletons to see if they provided me with guidance on what I want to achieve). I am trying to do the following: I want to display Blog entries with a gallery below the blog content. I though this should be a really simple thing to do but I have completely failed to achieve this.
Would it be possible to get a little help to point me in the right direction.  I have worked with Drupal for many years and am keen to use Grav, but it is proving to be a challenge.

**Comment by SudoMakeCake** [comment]
I'm in the same shoes as @mfuggle and @key-notes, though I'm trying to get Lightbox to work with the Clean Blog Theme.

I can get it to display one or more images, by using 

[lightbox image="red-dbs-1.jpg" gallery="gallery1" class="inline-block" desc=".dbs-1"]
![Red DBS - 1](red-dbs-1.jpg?cropZoom=200,200)
[/lightbox]

etc

But shouldn't I be able get a gallery to be shown like this?

---
title: 'Frosty walk'
media_order: 'frosty_water.jpg,frosty_wall.jpg,frosty_tree.jpg,frosty_pendle.jpg,frosty_moss.jpg,frosty_leaves.jpg,frosty_grass.jpg,frosty_fence.jpg'
header_image: frosty_tree.jpg
gallery:
    thumb:
        width: 400
        height: 300
    items:
        -
            title: 'Frosty tree'
            image: frosty_tree.jpg
            desc: 'image description part 1'
        -
            title: 'Frosty wall'
            image: frosty_wall.jpg
            desc: 'image description part 2'
        -
            title: 'Frosty moss'
            image: frosty_moss.jpg
            desc: 'image description part 3'
---
Some some words and other bla bla

[lightbox]


I have used the example partials/gallery.html.twig seen at the bottom of this page https://getgrav.org/premium/lightbox-gallery/docs
 
I've set the page to be Item and Modular, yet still nothing. 

Or am I on the wrong donkey, and if so please help as the above and the docs page is just going over my head

smc
