### ISSUE TITLE
[typhoon] adjust height of the logo/menu bar

### ISSUE THREAD

**Issue by rouben** [getgrav/grav-premium-issues#112]
Hi,

Is it at all possible to adjust the height of the logo uploaded to the Typhoon theme? The logo I uploaded gets crammed into the same height as the original Grav CMS logo file (see top left corner of the screenshot).

Uploading a PNG bitmap gets it crammed like that into the corner. Uploading an SVG logo only shows the tip (top left corner) of its topmost area.

![image](https://user-images.githubusercontent.com/2985666/122125998-1e155080-cdff-11eb-8bbe-615aed4e8331.png)

**Comment by rhukster** [comment]
In the `templates/partials/logo.html.twig` file you can change the height with tailwind classes, it's currently using `h-8` in a couple of places, try with `h-12`:

```twig
<div class="site-logo h-12">
  {% if logo %}
    {% set logo_file = (logo|first).name %}
    {% set logo_path = (logo|first).path %}
    {% if logo_file ends with '.svg' %}
      {{ svg_image(logo_path, 'fill-current h-12 w-auto mr-2', strip_svg)|raw }}
    ...
```
