### ISSUE TITLE
[typhoon] overlap with content and header menu in mobile breakpoints

### ISSUE THREAD

**Issue by key-notes** [getgrav/grav-premium-issues#113]
A bug in the Typhoon theme just caught my eye: On mobile devices, the header navigation overlaps the main content section and cuts off the main content.

This code in `partials/base.html.twig` appears to be correct:

`  {% block body %}
    <section class="flex-1">
      <div class="{{ hero_display ? 'pt-0' : 'pt-16' }}">
        {{ block('content_surround') }}
      </div>
    </section>
  {% endblock %}`

Any ideas as to what might be causing this issue?

**Comment by rhukster** [comment]
I made the assumption from your original URL you provided that you had disabled the **hero display** and the header that was going under the menu was just an h1 or h2 from the content.  However, it seems that it must be a hero element perhaps with some changed classes?

I really can't tell what's going on with a copy of your site.

**Comment by rhukster** [comment]
Did you change any **Hero Padding** or **Hero Align Classes** ?

**Comment by key-notes** [comment]
No, I didn't change anything. It's just a default theme installation so far.

**Comment by rhukster** [comment]
Ok, I think this is because you have a custom template you probably need to explicitly disable the hero display option on your page. A quick way to do it is to edit the page and put this in the frontmatter of the page .md file:

```
hero:
  display: false
```

**Comment by key-notes** [comment]
Thank you! That solved the problem.
