### ISSUE TITLE
[seo-magic] Feature Request - Add the ability to use site.title in page title

### ISSUE THREAD

**Issue by ptarmic** [getgrav/grav-premium-issues#115]
I am now using seo magic to set my page title since it counts the characters, sets the metadata and becasue its good SEO to sometimes use a different page title from the actual page title seen in the admin panel.

However there's no way to automatically include the `site.title` in the page title.

In `base.html.twig` I was originally using this: 
`<title>{% if header.title %}{{ header.title|e('html') }} | {% endif %}{{ 'SITE.TITLE'|t|e('html') }}</title>`

When I started using seo magic to set the page title I changed it to this:
`<title>{% if page.metadata.title.content %}{{ page.metadata.title.content|e('html') }} | {{ 'SITE.TITLE'|t|e('html') }}{% else %}{{ header.title|e('html') }} | {{ 'SITE.TITLE'|t|e('html') }}{% endif %}</title>`

However everytime I saved the page in the admin panel I got the "| site.title" duplicated in the page title.

In SEOMagic.php I hacked this line (86):
`$metadata['title'] = trim($header->{'seo-magic'}['title'].$this->config->get('site.title') ?? $this->getPageTitle($page) ?? $page->title()); `

Now I can have the `site.title` added to my page title. However a) its a hack and b) only picks up site.title from the field in the admin panel, originally I was setting this in `languages.yaml` so it could be translated.

Can you look at allowing site title to be added to the page title automatically or alternatively allow the seo magic to use / set `page.header.title` so my original code would work? Thanks

**Comment by rhukster** [comment]
There are new options in the plugin to allow falling back to site defined metadata.
