### ISSUE TITLE
[seo-magic] Auto-generated Meta Description not populating on the SEO Report

### ISSUE THREAD

**Issue by ptarmic** [getgrav/grav-premium-issues#116]
On pages where I don't create a custom description the SEO report screen doesn't show any description at all.
Despite the report screen, the auto-generated description is actually being generated and shows on the Open Graph tab as well as in the description meta field on the page itself. So more of a display bug.

![image](https://user-images.githubusercontent.com/72616419/122754046-09b3d680-d28b-11eb-87dc-29a9d2168582.png)

**Comment by rhukster** [comment]
Please try this again as this has been refactored.
