### ISSUE TITLE
[warm-cache] ERROR thrown: Sitemap URL extension is invalid. It should end in .json, your URL ended in .

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav-premium-issues#119]
I am running Grav v1.7.17 - Admin v1.10.17, trying to install the very-useful Warm-cache plugin on a test site:

1. Install license manager + relevant license, then install warm-cache + sitemap dependency plugins.

2. When I try warming the cache I get this red error message in the admin panel

`Sitemap URL extension is invalid. It should end in .json, your URL ended in .` 

The cache DOESN'T get warmed... And no idea what this message means! Surely the sitemap is an XML file?

As far as I can tell I have pretty standard setup for Warm-cache and Sitemap...

![Screenshot-Zeolite-2021-06-28-1](https://user-images.githubusercontent.com/6295710/123671716-7f451700-d836-11eb-8e6a-704e8752b762.png)
![Screenshot-Zeolite-2021-06-28](https://user-images.githubusercontent.com/6295710/123671726-810eda80-d836-11eb-8f24-73f7982d8d57.png)

**Comment by MattAppleton** [comment]
Possible related to https://github.com/getgrav/grav-premium-issues/issues/102#issue-896777627? I did try adding the feed plugin but that didn't help either...

**Comment by rhukster** [comment]
Is this warm-cache v1.1.1?

**Comment by MattAppleton** [comment]
how do I install the latest? Admin wont permit...

**Comment by rhukster** [comment]
OK, this is odd, 1.1.1 was released, shows as released in github, but not in GPM.. investigating.

**Comment by MattAppleton** [comment]
thanks — I see it in the changelog, but unable to prompt an update via Admin / License Manager

**Comment by MattAppleton** [comment]
hmmm... updated, still getting my red message...

**Comment by rhukster** [comment]
Yah see the issue.. i had only tested with the CLI, and didn't realize I had a bug in the Ajax version.

1.1.3 should be sorted.
