### ISSUE TITLE
[instagram-feed] 404 error after login to Instagram

### ISSUE THREAD

**Issue by agooa** [getgrav/grav-premium-issues#121]
Hello !

I'm using instagram feed (v1.0) with Grav v1.7.17 and Admin v1.10.17.

I have an issue when I try to login to the instagram account. After creating the app on facebook developpers an setup the instagram test account, I try to login to instagram in the Grav Admin. 
I can authorize the access to my profile but just after I click on "authorize" I'm redirected to a 404 error page. I can see the token in the url but it doesn't seem to be saved in the admin because I don't see the "valid token" badge after I reload the plugin page.
I tried to login with a different theme but I have the same issue.

The website is currently running in a subfolder if it matter. Is there something I'm missing ?

**Comment by w00fz** [comment]
Did you verify the Instagram Redirect URIs is the proper URL including the sub-folder? It should be in the format of `https://your-site.com/sub-folder/task:authInstagram`.

You should have this URL in both the plugin settings and on Facebook App at the `Client OAuth Settings` section.

**Comment by w00fz** [comment]
@agooa were you able to resolve this ?

**Comment by agooa** [comment]
Sorry for the delay ! The website is online (here https://alexaperchemal.com/) and I changed the redirect URL to https://alexaperchemal.com/task:authInstagram . Unfortunately I still have the same issue after clicking on "allow". I Have a 404 error page.

**Comment by rhukster** [comment]
That might be a routing issue.  Are you running this on windows?  Alternatively, are you running this on nginx?  it just seems like it's not working at all with the Grav parmater syntax of `x:y` in the URL.

**Comment by agooa** [comment]
Thank your for your answer. The website is running on a Linux server (shared server) with PHP 7.4 . Can it be caused by a PHP configuration ? I don't have a lot of knowledge in server and hosting.

**Comment by rhukster** [comment]
Sorry, was on vacation.  Does admin plugin work for you, it also uses a variety of colon-based URLs? I think somehow your webserver is not able to parse the `:` in the URLs. Perhaps this is a security thing.  This might be something you need to talk to your hosting provider about.  It's not a common issue.

**Comment by w00fz** [comment]
@agooa You should open a ticket with your hosting service and explain that the url `https://alexaperchemal.com/task:authInstagram` is supposed to be handled by the CMS you are using but instead it returns a 404. 

They should be able to fix it for you or point to the right direction. Unfortunately this is not something we can fix on our end. If you need further help or get please feel free to add a comment, in the meantime I'm going to close the issue.
