### ISSUE TITLE
[typhoon] question : updating duplicated theme

### ISSUE THREAD

**Issue by digitalbirth** [getgrav/grav-premium-issues#122]
I have just had a notification to update typhoon, but how do you sync the copied theme created with devtools, or is this not possible

**Comment by rhukster** [comment]
Unfortunately, there's no automated way to sync changes.  We always recommend having a copy of Typhoon theme that you are customizing, and my method is to use a diff/merge tool to see the changes and merge them as needed.  Something along the lines of VisualDiffer, Meld, WinMerge, etc.  You want something that can merge 'folders' and then you can see which files have changed, and then navigate into the specific files and see the difference and merge the changes you want.

**Comment by guategeek** [comment]
Would be great if someone could write a tutorial or add something to the Docs on how to do this folder merge and diff/merge tool for those of us who are unfamiliar with the process.

**Comment by rhukster** [comment]
There are different tools depending on your platform.  I use Kaleidoscope (mac) as it's quite reasonable and works well.  You just need some software that can do 'directory' diffs, that shows you all the files that have changed, then clicking into a file shows you the specific lines.
