### ISSUE TITLE
[typhoon] Menu Langswitcher is ignoring page-slugs

### ISSUE THREAD

**Issue by AndeeZee** [getgrav/grav-premium-issues#127]
Hello!

I have a multilanguage site for English and German and using the following versions at the moment:

- Grav v1.7.17
- Admin v1.10.17
- Typhoon v2.1.1
- LangSwitcher v1.5.0

Example folder-structure (based on the German language):
\pages\impressum
with 
- default,md --> NO page slug
- default.en.md --> page slug: legal-notice

The language-switcher is working as expected, however, the links being created in the langswitcher menu are not correct or - to be more precise - are ignoring the page-slug:
/de/impressum --> OK
/en/**impressum** --> not OK, should be --> /en/**legal-notice** according to the page-slug.

So I'm getting the following link created (when on the German site):
`<a class="w-full flex px-3 py-2 w-full hover:bg-gray-100 dark:hover:bg-gray-900" href="/en/impressum">English</a>`

Of course it resolves the page as well, but breaking the user experience, that's why I used the translated page-slug.

There are some pull-requests for the langswitcher plugin pending as well, but I think it might need some changes in the Langswitcher-section of the typhoon.php file, where the menu is assembled.

I tried to use a page-route instead of a page-slug as well, without any changes.

Any help appreciated.

Kind regards,
Andy

**Comment by rhukster** [comment]
This is for performance reasons. Grav only knows about one language at a time to ensure things perform optimally. There have been some PRs to provide the functionality that every slug can appear translated but they do not address the performance problem.  To properly determine the translated pages route you need not load all pages for that language. That is the one of the slowest things to do in grav, and it gets progressively worse the more pages and the more languages you have. 

There is a config option to ensure that any link to the page’s rawroute is redirected to the translate route. This is considered the best solution at this point. 

btw this is a langswitcher limitation and not an issue with typhoon itself.

**Comment by AndeeZee** [comment]
Thanks for the swift reply. Since the cause of this is somewhere else, I'm closing this issue.
