### ISSUE TITLE
[warm-cache] clarity on behaviour in relation to scheduled cache scripts...

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav-premium-issues#129]
This is more of a question...

Warm-cache docs state:

`onCacheClear Events → When enabled, Clearing the Cache either via Admin or CLI will then trigger a warm-cache call.`

Can I clarify if the 'onCacheClear' operation is triggered after a GRAV scheduler  'cache-clear' cron-job?

how about 'cache-purge'? that just gets rid of old cache files, right, so warm-cache wouldn't be called?

thanks!

**Comment by rhukster** [comment]
The event is actually called `onAfterCacheClear` and it's called by the `Cache::clearCache()` method.  This is used by anything that clears the cache.  So CLI command, CLI, automated on change detected etc.
