### ISSUE TITLE
Markdown indicators for code are shown in final document

### ISSUE THREAD

**Issue by sebastian0119** [getgrav/grav-premium-issues#13]
According to Grav's markdown syntax, inline code is marked with `backtick`. This works fine; inline code is rendered differently than the rest of the normal text.

However, the backticks still appear in the finally rendered text, immediately before and after the inline code - see following screenshot:

![screenshot](https://user-images.githubusercontent.com/52871458/103226073-e66a2900-48f0-11eb-9ccf-4eb5a2bc43aa.png)

**Comment by w00fz** [comment]
This should be an optional aesthetic behavior that can be disabled. @rhukster should have more info on how to disable the behavior.

**Comment by rhukster** [comment]
This is actually an intentionally visual design element that comes from the TailwindCSS Typography plugin.  You can remove it by overriding the `before` and `after` via `tailwind.config.js`

https://github.com/tailwindlabs/tailwindcss-typography/issues/51

**Comment by sebastian0119** [comment]
Thanks for the reply @rhukster 
But I am not sure where to insert / modify this syntax.
The Typhoon theme already has a ./user/themes/typhoon/tailwind.config.js file with most of the lines you show. Just adding the two pseudo-classes a shown in the [referenced issue](tailwindlabs/tailwindcss-typography#51) did not change the behaviour.
Thanks in advance +1

**Comment by w00fz** [comment]
Hey @sebastian0119 ,

Changing the file is not enough, you also have to recompile the css. We have  instructions you can follow in the docs section “_Installing NPM to Compile CSS_” (https://getgrav.org/premium/typhoon/docs).

**Comment by sebastian0119** [comment]
Got it - thanks Djamil!

Regards,
Sebastian


Am 1/1/21 um 21:58 schrieb Djamil Legato:
