### ISSUE TITLE
[seo-magic] webshot unauthorized image

### ISSUE THREAD

**Issue by digitalbirth** [getgrav/grav-premium-issues#136]
I am testing my seo, and when I check the image generated by webshot, I get this in return,

I have registered the correct domain, but this doesn't seem correct

I have deleted all data, and tried to regen, all seems to work except the webshot image

![image](https://user-images.githubusercontent.com/71056427/130337370-e7cfcdde-a811-4925-ae9d-174122b08347.png)

this is the link that is generated : https://webshot.getgrav.org/?url=aHR0cHM6Ly93d3cuZGlnaXRhbGJpcnRoLmNvbS5hdS8=

**Comment by w00fz** [comment]
The registered URL must match the Grav instance you are testing exactly, and you can only have one registered.

If you are using `https://Mysite.com` then that’s the URL you need to register, including the https protocol.
In the field where you register, it also explicitly tell you what your license is currently associated to for the webshot feature.

I believe you are using http instead of https. Try un registering it and registering it again with the proper protocol.

**Comment by digitalbirth** [comment]
I have double-checked and the url is the https version same as my site, I had updated it a few days ago that's why I deleted the data and regenerated

**Comment by w00fz** [comment]
What does the field where you register the webshot url say?

**Comment by w00fz** [comment]
![w00fz-2021-08-21_@_22 00 55@2x](https://user-images.githubusercontent.com/11734/130343017-1a6ad48c-601c-4d31-80aa-2dc14a008ef2.png)

That is the part I mentioned above that I believe you have registered as `http` instead of `https`.

**Comment by digitalbirth** [comment]
![Screenshot_20210822-151704__01](https://user-images.githubusercontent.com/71056427/130343354-fdb31bf8-5369-4a40-b2ff-0e1fd66a0d61.jpg)
As  mentioned it is the https

**Comment by w00fz** [comment]
Hey @digitalbirth, apologies for this. You didn't do anything wrong, I just finally figured out we had a glitch in the way the authorized sites were synchronizing with the webshot server and a few sites just never officially registered. This most certainly happened recently when we migrated GetGrav to a new machine.

Everything should be resolved now and you should be able to finally see the webshots

**Comment by digitalbirth** [comment]
Hey, 
Just checked, worked without even regenerating data, thank you for looking into it and fixing it
