### ISSUE TITLE
[seo-magic] add a keyword exclusion list

### ISSUE THREAD

**Issue by digitalbirth** [getgrav/grav-premium-issues#137]
When the page automatically generates keywords it would be great to offer an exclusion list so it doesn't pick up common words used within the text that are not as relevant.

I understand I can individually tailor each page, but to have a global exclusion list would be super helpful.

**Comment by rhukster** [comment]
I think it's a valid point, i'll add this to the list for an upcoming release.

**Comment by rhukster** [comment]
Just looking at the code and  we already have "custom stopwords" which should stop TextRank from including those in descriptions or keywords.
