### ISSUE TITLE
[seo-magic] meta images configuration not working as documented

### ISSUE THREAD

**Issue by Bettelotta** [getgrav/grav-premium-issues#138]
I am using SEO magic plugin and according to the documentation the order of setting the og:image is supposed to be og-image.jpg → og-image.png → First image found → Default URL. Each blog post has an image at the top so I would expect that unless there is an og-image.jpg or og-image.png in the page folder the blogpost image would be set as og:image. But it doesn’t - it falls back to the default-URL. Is there anything I am missing? 

I am on Grav version 1.7.17 and SEO Magic 2.1.1.

**Comment by rhukster** [comment]
I recently changed the fallback behavior in the last update but didn't update the documentation yet. If you have it set to "Auto" then it should fall back in this order:

1. image name provided
2. image attribute provided (ie, key of a another attribute that contains an image name)
3. og-image.jpg/png
4. first image found in media object (alphabetical usually)
5. seo-magic configured default filename

**Comment by Bettelotta** [comment]
Hi, could you please explain what is meant by 'first image found in media object'? Do I need to put an image file into each page folder? The pages are referencing images anyway - is there not a way to let seo-magic use the links in the html-code?

**Comment by rhukster** [comment]
Basically it just means the media fro the current page in default order in the filesystem. This is usually alphabetical, but it can be different on various platforms.

**Comment by Bettelotta** [comment]
I have pages in different languages. That would mean the plugin would take the same picture for the different languages? Is there not a way to use the first image reference that is found within the HTML-code?

**Comment by rhukster** [comment]
It could be possible... i'll note it for a future enhancement.

**Comment by Bettelotta** [comment]
Thanks. Can you estimate how long it will take to validate the option and even implement it?

**Comment by rhukster** [comment]
Won't take too long but i've very busy and can't really give an ETA.  You can use one of the other existing methods though in the meantime.

**Comment by Bettelotta** [comment]
How can I provide different images for different languages of the same page?

**Comment by rhukster** [comment]
Use the `image_attribute` option and then enter the appropriate attribute name.  So for example if you have an header attribute called `share_image:` you can reference that in each language file:

**en.md**
---
title: English page
share_image: english_image.jpg
...
---

**fr.md**
---
title: French page
share_image: french_image.jpg
---

**Comment by Bettelotta** [comment]
Ah, great, that will work!

**Comment by Bettelotta** [comment]
I put the option 'Specific attribute in page Header' in meta images of the plugin configuration, then on the page itself I chose 'specific header attribute' again. I left the specific header attribute to 'hero_image' and checked the box. In the page header I put hero_image: /user/img/blog/image_de.jpg. This does not work. 
I put two different images in the folder and put hero_image: image_de.jpg. It does not work. 
Can you please give me more details?

**Comment by rhukster** [comment]
Hmm, looks like a typo in line 207 of `user/plugins/seo-magic/classes/SEOMagic.php`. Should be:

```php
$image_media = $media[$header_image] ?? null;
```

That should fix the issue and i'll get a new release out with it shortly.

**Comment by Bettelotta** [comment]
I fixed the line of code but it still does not work. Could you reproduce the error and hence verify that the fix fixes it?

**Comment by Bettelotta** [comment]
Unfortunately now the default order does not work anymore. The other pages don't find the default URL. 
These are the options:
![image](https://user-images.githubusercontent.com/24413732/131992038-93523d1a-463a-4e2f-9d93-4e5b45e46db7.png)
Which ist the option that is declared 'Automatic' in the documentation? It is a bit irritating that the documentation doesn't match.

**Comment by rhukster** [comment]
I was holding off updating the documentation until the fix was confirmed.  Anyway, i'll double check all the options and get the documentation updated to match the new 'fixed' logic.

**Comment by Bettelotta** [comment]
Hi again, for most of my blog pages I changed the option now to 'specific attribute in page header', added the attribute hero_image and put the image in the page folder. This works fine - the og:image attribute is generated as expected. 
In the meta options I put 'Default URL of a specific image' and put a complete image_path. I would expect now that pages without a specific configuration would fall back to that image. But they don't. They pull an image from the HTML-text. How can I configure that pages without a specific configuration falls back to the parent configuration? I don't want to copy a default image redundantly down to each page directory.

**Comment by rhukster** [comment]
I've improved this some more to provide fallbacks for all types. I've also updated the documentation to reflect how this works.
