### ISSUE TITLE
[FlexObjects] Media picker/insert image/drag drop on flex objects (affecting NextGen Editor)

### ISSUE THREAD

**Issue by ricardo118** [getgrav/grav-premium-issues#140]
Adding a nextgen editor via blueprints to a flex object (adding assets with nextgen-editor.load event the editor works fine except for the media functions

Result on drag/drop image from a `type: file` to the editor works however it creates the image as a base64 encoded image, it doesnt use the actual added image. As seen below:

![image](https://user-images.githubusercontent.com/7531933/131264137-79c4d545-ac7d-4b5c-9acb-7294aadd26fb.png)

Attempting to `insert media` or use the `media picker` simply returns this error: 

![image](https://user-images.githubusercontent.com/7531933/131264184-ca7a6d7b-1da4-4cfa-a2b9-8e9cf369e74c.png)

Despite the object already having been saved

**Comment by ricardo118** [comment]
@mahagr to expand on this, switching to a normal non next-gen editor, causes a different behavior. It instead of creating an image in markdown `![](imgpathhere)` creates instead a full link `https://grav.local/user/data/flexobjectsfolder/objectkey/image.jpg`.

It seems to all be related to the fact that the type: file in flex doesn't have the proper url.

When you click the "eye" icon on a flex object, it will not have the proper path and viewing the direct image cannot be performed.

![image](https://user-images.githubusercontent.com/7531933/132746547-f2190e76-0d96-489e-8a7d-445b49c8f5da.png)

you can see the thumbnail is now fixed (this was an old bug that you fixed) but the dz-view element still has the wrong href. Perhaps theres other links that the editors are looking for when dragging/dropping

**Comment by mahagr** [comment]
You can make objects have proper routes by implementing `getRoute()` method. Flex objects also have logic to get media urls, so maybe that should be used?

**Comment by ricardo118** [comment]
yeah that could be, but probably should work out the box for folderstorage since it technically says media support probably good to have working previews. 

I can test with the getRoute() method, do you have any examples?

**Comment by ricardo118** [comment]
also the media upload on nextgen-editor is probably the biggest issue, since its the premium plugin, should work straight away

**Comment by w00fz** [comment]
> also the media upload on nextgen-editor is probably the biggest issue, since its the premium plugin, should work straight away

@ricardo118 If you are referring to #139 , that is fixed and will be available with next release.


@mahagr As this seems to be a FlexObjects issue, and not NextGen per-se, should we move the issue to that repo instead?

**Comment by mahagr** [comment]
The issue cannot be moved, so we may want to create a new issue.

**Comment by w00fz** [comment]
You are right.

I have renamed and closed this one. @ricardo118 would be great if you could reopen this under https://github.com/trilbymedia/grav-plugin-flex-objects/issues and link to this issue (so you don't have to repeat it all), as it's a more appropriate place.
If any additional work is necessary for making NextGen working after the flexbox issue has been resolved, I will certainly look at that.
