### ISSUE TITLE
[typhoon] users clicking title and not icon to expand menu

### ISSUE THREAD

**Issue by digitalbirth** [getgrav/grav-premium-issues#141]
My typhoon mobile menu is shown as follows

![image](https://user-images.githubusercontent.com/71056427/131277225-3bc6f86b-a99e-44cd-adaf-4026b6bdb4a5.png)

![image](https://user-images.githubusercontent.com/71056427/131276736-120a2eae-35bf-4728-a1f0-561231b18f27.png)

to expand the menu a user needs to click the plus, minus icons

as the services and tools are not routable and are only containers, they need to be expanded to see the routable pages

I'm seeing users click the title and not the icon, which in turn is losing visitors, as they think it is a website issue

here is a video, sorry for the poor video

https://user-images.githubusercontent.com/71056427/131277020-3fbb71ee-e97d-41d2-8408-697b64908379.mp4

if this is an easy fix I would love to see it implemented that you can click on the title to expand if the page is non-routable..

**Comment by rhukster** [comment]
I'll take a look at this in the next few days.. Cheers.

**Comment by rhukster** [comment]
fixed for next release
