### ISSUE TITLE
[nextgen-editor] linking uploaded media

### ISSUE THREAD

**Issue by tg-x** [getgrav/grav-premium-issues#142]
When inserting a non-image file (tried with PDF) from the uploaded media (drag&drop or + icon next to the file), nextgen-editor tries to insert it as an image, showing a huge image with the file extension text, while in this case a simple link would be desirable instead, which is the behaviour of the standard grav editor.

A `Link page media` toolbar icon would be also useful next to `Insert page media`, as a possible solution.

Ideally, it should be possible to set an insertion template per media file type,
to allow certain file types to produce a shortcode or some additional text instead.
e.g. for PDF files to have a template like: `[[fa=file-pdf-o] document title](file.pdf)`

**Comment by w00fz** [comment]
Fix will be available in the next release, thanks!

**Comment by angusmcb** [comment]
I have just updated my plugin and still have the same problem. 

The behaviour has changed - now nothing happens when trying to drag the media across, as opposed to before when the big 'PDF' image was added.

**Comment by w00fz** [comment]
When dragging a non image file you get a link now. That’s what I’m seeing, any errors?
