### ISSUE TITLE
[nextgen-editor] Unable to install Nextgen Editor - Premium Plugin - GPM Error

### ISSUE THREAD

**Issue by bachurva** [getgrav/grav-premium-issues#144]
I am using Grav v1.7.18 (Admin Plugin) and the Learn2 Git Sync theme. I have downloaded and installed other free plugins in the past. But I seem to be having an issue while trying to install the Nextgen-editor with the License Manager (License key and slug have been entered) 

I see this error while trying to install the Nextgen Editor - Premium Plugin.

"GPM not reachable. Please check your internet connection or check the GRAV site is reachable."

The internet connection is fine.

Can you indicate what may be causing this error? 

Thanks
![Nextgen Editor Error](https://user-images.githubusercontent.com/44727728/131631719-ef7720a3-1f61-4f6f-a437-19120c6d17cd.png)

**Comment by rhukster** [comment]
Can you install other plugins or is it just nextgen that is giving you a problem? Can you confirm you have installed your license file?

**Comment by w00fz** [comment]
I tried installing it right now and I have no issues reaching out GPM. This seems to be an error caused by either your internet provider or the server your site is at.
Have you tried installing other plugins? Are you behind proxy?

**Comment by bachurva** [comment]
> I tried installing it right now and I have no issues reaching out GPM. This seems to be an error caused by either your internet provider or the server your site is at.
> Have you tried installing other plugins? Are you behind proxy?
