### ISSUE TITLE
[typhoon] lightbox option in modular image-block.html.twig (request)

### ISSUE THREAD

**Issue by PeterB513** [getgrav/grav-premium-issues#146]
Is it possible to add a lightbox option in modular image-block.html.twig? Or how do I add it myself? Did some tests but didn't succeed.

**Comment by rhukster** [comment]
I would suggest adding it yourself as I don't think it's a common use case to have a small image in this block that 'lightboxes' to a larger version.  

You would definitely have to have some smaller image URL and then a larger image URL to view in the lightbox.  If you have made a copy of Typhoon (as recommended) you can simply edit the `templates/modular/image-block.html.twig` and replace the:

```twig
<img class="mb-8 md:mb-0 rounded-md" alt="{{ image }}" src="{{ image }}">
```

with something like (although this is using the same image for content and target):

```twig
{% set content %}
<img class="mb-8 md:mb-0 rounded-md" alt="{{ image }}" src="{{ image }}">
{% endset}
{% set target  = image %}

{% include "partials/lightbox.html.twig"  with {content: content, image: target} %}
```

**Comment by PeterB513** [comment]
Thanks for the hint. I will give it a try.
