### ISSUE TITLE
[typhoon] error using own plugin 

### ISSUE THREAD

**Issue by PeterB513** [getgrav/grav-premium-issues#147]
I created an own plugin using typhoon. I tested the plugin on the server where Grav was installed. Everything worked fine.
Then I tested the plugin connecting to the webserver from another computer.
I got the error `Call to a member function createObject() on null ` . On the Grav forum I found simular problems. The solution for me was not clear.
I do not know if this has something to do with, it but I get a warning `support for Composer 1 is depricated and some packages will not be avaiable. You should upgrade to Composer 2` after I give the command: `composer upgrade` in the plugin directory. 
The server runs on Ubuntu, Nginx, php7.4.3 and Grav is up to date.
If you need the php source please let me know.

`

**Comment by rhukster** [comment]
I'm afraid the information provided is not enough to determine what the issue is. How did you create a plugin using Typhoon?  Typhoon is a theme, and i'm not sure why it would have any impact on your own plugin.  Please provide some more details so we can know what's going on.  Cheers.

**Comment by PeterB513** [comment]
Clear. I think it is indeed not a Typhoon issue. Did a complete fresh install of Grav with Typhoon theme. Got the same error. Changed from theme to Quark. Some problem. So I should report my problem not here.. On my other server I don't have this problem. Weird.
