### ISSUE TITLE
[warm-cache] Warm-cache not running after cache clear from scheduler

### ISSUE THREAD

**Issue by angusmcb** [getgrav/grav-premium-issues#149]
I have warm-cache set to run on cache clear.

This seems to work when I clear the cache from the admin panel, but not during a scheduled cache clear. 

This is based on what I have seen checking my log file. There are no error messages, but no messages to say any pages have been warmed either.

**Comment by rhukster** [comment]
I will take a look at this.

**Comment by rhukster** [comment]
I've updated the docs with examples on how to get things running with Grav scheduler.  https://getgrav.org/premium/site-toolbox/docs#usage

**Comment by angusmcb** [comment]
Thanks for adding the explanation, it took some time but following the instructions I've got it working now :-)
