### ISSUE TITLE
mouse over with safari browser

### ISSUE THREAD

**Issue by palle1977** [getgrav/grav-premium-issues#15]
by mouse over the is effect not with rounded corners in the safari browser
see on the first and second picture, when I move the mouse from the first to the second pic

![Bildschirmfoto 2021-01-15 um 17 09 01](https://user-images.githubusercontent.com/20641533/104750495-7b27b000-5754-11eb-8701-426775f051a0.png)

**Comment by rhukster** [comment]
I will take a look, thanks!

**Comment by rhukster** [comment]
Turns out this is a well known bug.. https://gist.github.com/ayamflow/b602ab436ac9f05660d9c15190f4fd7b

Will release an update to Typhoon that fixes this + adds the scaling back that got lost with move to Tailwind 2.0

**Comment by rhukster** [comment]
Typhoon 1.0.6 was just released containing this fix, and should be available in about 30mins or so.
