### ISSUE TITLE
[warm-cache] Memory exceeded whilst using warmcache

### ISSUE THREAD

**Issue by angusmcb** [getgrav/grav-premium-issues#150]
After clearing the cache, I always get memory errors when the site is subsequently warmed by warmcache. The specific error can vary but always has 'Cannot allocate memory' somewhere in the logs.

My hosting provider has a memory limit of 512MB (this is a resouce usage limit, not a php limit), but my site is relatively modest in size (the sitemap has 66 pages).

Would it be possible to implement some sort of option for warmcache to reduce the load on the server? Maybe by loading pages more slowly either with a simple short pause between page fetches, or even better something that is aware of errors or memory availability? 

Of course it's possible that this is not really an issue for warm cache at all and it is instead a problem for my site design or for the hosting provider!

**Comment by rhukster** [comment]
The only thing I can do is to limit the number of concurrent connections. It will slow things down quite dramatically though.

**Comment by angusmcb** [comment]
If it's not practical to change then no worries - it could simply be an issue related to being on shared hosting. As far as I can tell the main consequence is that the whole site freezes for a bit, then sometimes some of the images appear broken - presumably as the memory runs out somewhere in the middle of processing them.
