### ISSUE TITLE
[typhoon] Cloning theme - Navigation doesn't work

### ISSUE THREAD

**Issue by PalmTreeVI** [getgrav/grav-premium-issues#152]
When cloning Typoon 2.1.3 theme using cli `bin/plugin devtools newtheme`, the new themes navigation does not work without first edited 2 twig files:
* newtheme/partials/navigation.html.twig
* newtheme/partials/mobile-navigation.html.twig

Original:
```<ul class='{{ classes.root }}'>
  {% if show_onpage_menu %}
    {{ macros.nav_loop(typhoon_onpage_menu(), classes, alpine, svg) }}
  {% else %}
    {{ macros.nav_loop(typhoon_primary_menu(), classes, alpine, svg) }}
  {% endif %}
</ul>
```

Modifications example (newtheme/partials/navigation.html.twig) to get working:

```<ul class='{{ classes.root }}'>
  {% if show_onpage_menu %}
    {{ macros.nav_loop(mytheme_onpage_menu(), classes, alpine, svg) }}
  {% else %}
    {{ macros.nav_loop(mytheme_primary_menu(), classes, alpine, svg) }}
  {% endif %}
</ul>
```
Similiar modification needed for mobile-navaigation.html.twig

(replace mytheme with the name of your new theme)

**Comment by rhukster** [comment]
i will look into this.

**Comment by rhukster** [comment]
I'm going with theme_primary_menu (as well as the other 3 menu functions).

**Comment by rhukster** [comment]
This should be fixed in Typhoon that was released today.
