### ISSUE TITLE
[typhoon] Saving theme settings a second time resets some settings and images

### ISSUE THREAD

**Issue by PalmTreeVI** [getgrav/grav-premium-issues#153]
Typoon theme v2.1.3, Admin v1.10.22

I noticed that if I save the theme settings (using admin plugin), then make another change and save again, the Custom Logo and Custom Favicon get removed and revert to the default Grav logo

**Comment by rhukster** [comment]
Confirmed. It seems something in Grav/Admin, or Forms has broken file upload in theme configuration.

**Comment by rhukster** [comment]
This should be fixed in latest version of Grav Admin plugin that was released today.
