### ISSUE TITLE
[typhoon] One Page modular menu use module slug if present

### ISSUE THREAD

**Issue by AndeeZee** [getgrav/grav-premium-issues#156]
Hello!
This is for Typhoon v2.1.3. The one page modular menu was fixed lately. 
However, I'd love to have the module-slugs be used for creating the id's/links instead of the hyphenized version of the menu-text itself.

**Why is that?**
My primary language is German, and we have umlauts like äöüß. Having those characters inside a Menu will lead to ugly looking id's and links. So when a user clicks on a link, a replacement-character is shown for äöüß in the link.

Would it be possible to modify the one page modular menu, so that it takes the module-slug **if present** and falls back to the hyphenized menu-text?

Changes might be necessary in 
_modular/partials/base.html.twig_
where the id is generated.

And inside
_typhoon.php -> function getOnPageMenu()_
where the menu itself is generated.

Thank you very much,
Andy

**Comment by rhukster** [comment]
I'm going to use a trimmed slug instead of hyphenized menu.

**Comment by rhukster** [comment]
This should be fixed in Typhoon that was released today.

**Comment by AndeeZee** [comment]
Hello!
Thank you for the very swift update. However, this caused a side-effect.
Grav v1.7.23 - Admin v1.10.23 - Typhoon 2.1.4

I've created some modular twig-templates, such as `competences.html.twig`, `about.html.twig`, etc.
The modular twig-templates are located in `\templates\modular`.

However, with typhoon 2.1.4 and a "`slug: xxx`" present in the modular md-files, I'm receiving an error like
**ERROR: competences.html.twig template not found for page: /home/business-segments**
where "**business-segments**" is my slug.

If I move the modular-twig-templates to `\templates`, the twigs are picked up correctly and the error is gone.

Would you be so kind to have a follow-up look into this?

Thank you,
Andy
