### ISSUE TITLE
[NextGen Editor] not loading in Mac Safari/Chrome and JS Console error

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-premium-issues#158]
I am (finally) getting around to work on supporting embedded media with NextGen and my Quark Open Publishing Theme, but for some reason I cannot seem to load pages in my local skeleton with the NextGen Editor enabled - below is a screenshot, any ideas (most recent Grav/Admin/etc)?

<img width="1200" alt="2021-09-27_09-05-54" src="https://user-images.githubusercontent.com/1812771/134944723-a9e7baf9-b7ee-4afb-9d3f-b21fd0239804.png">

I've tried a manual remove/add of the NextGen Plugin and still no luck.

Thanks very much!
Paul

**Comment by w00fz** [comment]
Hello @paulhibbitts,

I believe this is related to a bug I introduced with #151 although specific to the Images it looks somewhat related. I have now resolved that issue and preparing for releasing but I would like to know how to reproduce your issue exact as it seems related to custom buttons.

Could you share what you have that triggers that error?

**Comment by paulhibbitts** [comment]
Thanks @w00fz , you've given me lead so I will loop back once I follow that (re: custom buttons)...

**Comment by paulhibbitts** [comment]
Ok, no luck @w00fz I thought it might have been a missing NextGen shortcode file but they all look there. Here are the three Shortcodes I add to the NextGen toolbar:
https://github.com/hibbitts-design/grav-theme-quark-open-publishing/tree/master/nextgen-editor/shortcodes

And here is the load in the theme PHP:
https://github.com/hibbitts-design/grav-theme-quark-open-publishing/blob/master/quark-open-publishing.php#L27-L36

I tried to downgrade the NextGen Plugin and even a few versions back this JS error comes up. Any other info helpful? I can also share the `user` folder if helpful etc.

Thanks very much,
Paul

**Comment by w00fz** [comment]
I'm assuming this is an issue even if you have only 1 of those shortcodes? I am going to try and replicate locally the problem. Thanks

**Comment by paulhibbitts** [comment]
I found the issue @w00fz ! I had a localhost folder that had an older NextGen config file that looks like it was not updated etc.

**Comment by w00fz** [comment]
Oh! glad it wasn't another issue I introduced!

Thanks for the update!
