### ISSUE TITLE
Typhoon Theme - Dropdown Menu

### ISSUE THREAD

**Issue by and-42** [getgrav/grav-premium-issues#16]
After creating 3 pages using the Default Template with following structure

Parent
  - Child1
  - Child2

the Dropdown menu in the Navbar is not shown.

**Comment by rhukster** [comment]
The pages need to have numeric prefixes which allows ordering in the menu and automatically makes them visible to the menu.  Alternatively you can set visible to true in the advanced tabs but loose ability to order.

i recommend turning on numeric prefixes and ordering.

**Comment by and-42** [comment]
Thanks, numeric prefixes does the trick.
Is there any documentation for things like this?

**Comment by rhukster** [comment]
This is in the regular grav documentation. 

https://learn.getgrav.org/16/content/content-pages#folders
