### ISSUE TITLE
[lightbox-gallery] Video thumbnail playing, fullscreen not

### ISSUE THREAD

**Issue by martinzbinden** [getgrav/grav-premium-issues#160]
It seem's that Gallery template shows videos now. But: when I click on the video to see title and description, video is not loading.

For example here:
https://agff-tagung.ch/mlt21/posten-2 
Video is a 11MB mp4 H.264 file, uploaded to the same page above.

![image](https://user-images.githubusercontent.com/8795851/135256003-39f4ba3d-2455-487a-b363-298143f46417.png)

**Comment by rhukster** [comment]
I have tested this and it works fine with my sample test:

```md
## Local Video Test

[lightbox video="sample.mp4"]
![Mars Lander](sample-thumb.png?cropZoom=330,200)
[/lightbox]
```

Plays just fine:

<img width="1268" alt="CleanShot 2021-09-30 at 09 58 33@2x" src="https://user-images.githubusercontent.com/1084697/135490256-1eb27062-aae0-4515-aa03-1f5223a39b5e.png">

What does your code look like to setup the video in your page?

**Comment by rhukster** [comment]
I think you are just doing this wrong.  You should set a thumbnail for your image and provide a video attribute with the name of the video:

<img width="1190" alt="CleanShot 2021-09-30 at 22 13 23@2x" src="https://user-images.githubusercontent.com/1084697/135564233-5ce5451f-1844-44b9-86ea-0312c975cc2b.png">

**Comment by martinzbinden** [comment]
Yes, I did wrong. Thank you for help!
