### ISSUE TITLE
[typhoon] overflow in base.html break sticky behaviour

### ISSUE THREAD

**Issue by danjames68** [getgrav/grav-premium-issues#164]
I've updated Typhoon and am re-building my theme and noticed that the 'sticky' behaviour no longer works. The line change in _base.html.twig_ from:

`x-data="{ show_mobile_nav: false, theme: typhoonRetrieve().theme, appearance: typhoonRetrieve().appearance }">`

to 

```
      x-data="{ show_mobile_nav: false, theme: typhoonRetrieve().theme, appearance: typhoonRetrieve().appearance }"
      :class="[ show_mobile_nav ? 'overflow-hidden' : '', theme ]" class="overflow-x-hidden">
```
break the sticky behaviour because of the overflow setting. How can I fix this?

**Comment by rhukster** [comment]
What exactly is the sticky behavior you are talking about? What is sticky? Typhoon has never had a sticky main menu built into it, unless you mean the fixed behavior of the mobile menu?

**Comment by rhukster** [comment]
Yes I see, it's a custom thing you've added in the sidebar.  Unfortunately i'm not able to know every custom thing that's being done on top of Typhoon, and ensure compatibility.  I'm glad you found a solution!
