### ISSUE TITLE
[nextgen-editor]  Extra '/' added at the start of url when image uses 'image://' type url

### ISSUE THREAD

**Issue by angusmcb** [getgrav/grav-premium-issues#167]
Nextgen editor currently seems to break images which are added using the `image://` type url by adding a `/` at the start of the url.

For example:

```![](image://image-name.svg)```

is changed to:

```![](/image://image-name.svg)```

**Comment by slwa-epowell** [comment]
We are also having this problem. I ended up writing a cron job to go through and correct the links every 5 minutes, but it would nice to have it resolved. Thanks very much!

**Comment by w00fz** [comment]
This is resolved now, will be available in the next release.

Thanks
