### ISSUE TITLE
[nextgen-editor] feature suggetion: filter 'media picker' to show only media from the current page folder

### ISSUE THREAD

**Issue by angusmcb** [getgrav/grav-premium-issues#168]
Currently, the media picker shows all the media from the whole site.

It would be good if this could be filtered (either by default or optionally) to only show media from the current page folder.

My site has a lot of media on many different pages, and showing all of this mixed together in the media picker dialog makes it very difficult to find the required file.

**Comment by angusmcb** [comment]
Thanks for the response!

The use case is a bit more niche I suppose. I have a modular page with a 'features' section, where each feature can have some text which uses the editor. In this case there are multiple editors on the same page, so (as far as I can tell) there is no way to use the Page Media section as normal.

**Comment by w00fz** [comment]
This is now handled a bit better. When you open the media picker you are greeted by only the media files from the current page. Additionally, there is now a navigational sidebar with all the page structure of your site, that can be interacted with to  select and load media from other pages.

<img width="1169" alt="CleanShot 2022-01-10 at 20 47 13@2x" src="https://user-images.githubusercontent.com/11734/148884942-cb8f44ee-01e2-4fce-8e8c-5edda7f036e4.png">



This is how it was intended to be to begin with but nobody expressed interest so far so, thank you for the feedback!

**Comment by angusmcb** [comment]
Thank you, that looks great!
