### ISSUE TITLE
[nextgen-editor] Label is not shown when defined in blueprint

### ISSUE THREAD

**Issue by fdruide** [getgrav/grav-premium-issues#17]
First of all, congratulations for releasing Grav 1.7. It is such a joy to use.

I noticed a small change when editing pages with nextgen-editor compared to the default one. The label defined in a blueprint is not showing up when editing the page. If I deactivate the nextgen-editor plugin and use the default editor, it is showing up. 

 Tested with a clean install :
- Grav core + Admin (v1.7.0)
- NextGen Content Editor (v1.0.3)

Here is a simplified blueprint to test :

> extends@: default
> 
> form:
>   fields:
>     tabs:
>       type: tabs
>       active: 1
> 
>       fields:
>         content:
>           fields:
>             content:
>               type: Markdown
>               label: Content
>             header.media_order:
>               unset@: true

I included two screenshots to show the output when nextgen-editor is inactive and active. I would expect to see “Content” as a label when the plug-in is active.

Thank you for your time!

<img width="600" alt="nextgeneditor-inactive" src="https://user-images.githubusercontent.com/32466736/105218991-e8a45980-5b23-11eb-9233-d28a81591d75.png">
<img width="600" alt="nextgeneditor-active" src="https://user-images.githubusercontent.com/32466736/105219011-f35eee80-5b23-11eb-97e6-467792400a1a.png">

**Comment by w00fz** [comment]
Thanks for the letting us know, I will add it in the list of fixes for the next release.

**Comment by w00fz** [comment]
This is now working in 1.0.5.

Cheers,
