### ISSUE TITLE
[seo-magic] Generating SEO Magic data causes gateway timeout

### ISSUE THREAD

**Issue by hdwebpros** [getgrav/grav-premium-issues#174]
When I click on the button that processes pages and generates SEO data, I get this error:

> 504 Gateway Timeout
Gateway Timeout
The gateway did not receive a timely response
from the upstream server or application.
Additionally, a 504 Gateway Timeout
error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by hdwebpros** [comment]
I emailed you the credentials and another error we are hitting now :(

**Comment by hdwebpros** [comment]
I'd be glad to provide other details if needed via email (SSH / FTP / etc)

**Comment by rhukster** [comment]
can't login with creds provided...

**Comment by hdwebpros** [comment]
Sorry, fixed the issue. Please try again

**Comment by rhukster** [comment]
I think this is sorted.  Please let me know and i'll reopen if needed.
