### ISSUE TITLE
[lightbox-gallery] Assistance in migrating to lightbox-gallery

### ISSUE THREAD

**Issue by Gymnae** [getgrav/grav-premium-issues#175]
Hi there, 

just purchased the plugin today. I am currently using photoswipe and want to migrate. My workflow is to define a folder in the frontmatter header and have a twig template parse the content of the folder to build a slide show. This way grav simply consumes content of folders I can manage elsewhere (like Lightroom export destinations) and I do not have to manually add new photos to a gallery in grav. It works for me. Whenever I need a new album, I generate a new .md file, assign it the fitting gantry page template, define the the source folder in the header and that's it. 

In addition, I add EXIF based title and description to my photos as consumable metadata. This way I can manage descriptions used for captions in Lightroom or any other image manipulation software without needing a sidecar file or any other source for a caption. I would like to keep it this way. 

flexbin is a "pure css" approach to a gallery layout. It served my kinda well so far.  

My question would be how to migrate this setup to lightbox-gallery?
I added the css given in the documentation as an scss file part of my custom.scss

I am not sure if this is the right place to request assistance with this, I currently lack the time to dive deeply into the matter myself, unfortunately. 

My twig code looks like this: 

```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block particle %}

{# either accept a variabel set inn via 'imagefolder: <path>' in front matter, or take the chosen variable from gantry5 in the particle config #}
{% set foldervariable = page.header.imagefolder|default(particle.folder) %}
{# split the path into an array, delimited by '/' #}
{% set folder_array = foldervariable|split('/') %}
{# strip out '/user/pages' and the file chosen in the file picker #}
{% set folder_array = folder_array|preg_grep('/user|pages|[0-9a-zA-Z :\\-_!@$%^&*()]+(.png|.PNG|.mpg|.mp4|.m4v|.mov|.jpg|.JPG|.jpeg|.JPEG|.bmp|.BMP|.gif|.GIF|.psd|.PSD)/', 'invert') %}
{# create a gallery using photoswipe out of each image, ignoring other media #}
    <ul class="gallery-item">
      {# use flexbin for a nice justified grid #}
      <div class="flexbin">
        {# recreated a proper path for grav to find image files #}
  {% for image in page.find('/' ~ folder_array|join('/')).media.images %}
	{# tempory disabled exif caption textracion due to php7.x exception #}
                {% set data = exif(image.filepath, true) %}
	{# individual images #}
    <li  data-gallery="gallery-item" title="greatgallerywow" class="flexbin">
      <figure>
          <img alt="{{ data.IPTC.title }}" src="{{ image.cropResize(1200,600).url|raw }}" />
        <figcaption>
            <h3>{{ data.IPTC.title }}</h3>
            <p>{{ data.IPTC.caption }}</p>
            <a rel="lightbox" href="{{ image.url|raw }}" title="{{ '<b>' ~ data.IPTC.title ~ '</b>   ' ~ data.IPTC.caption  }}">View</a>
        </figcaption>
      </figure>
    </li>
{% endfor %}
</div>
  </ul>
{% endblock %}
```

**Comment by Gymnae** [comment]
Sorry for the delay in my reply.

This is how an .md file looks. It's very short, since I assign a gantry template to it, which does the magic. That is what the twig code above does.
```
---
title: Example album title
subtitle: Example album sub title
imagefolder: user/pages/mymedia/nextcloud/2021/example
---

##<span class="pagetitle">Example album title</span> 
some text to appear
```
Here's a link with images with exif based caption: https://cloud.grundstil.de/index.php/s/TwkL9Ym3pcD7zds

**Comment by Gymnae** [comment]
@rhukster , @w00fz  - I hope I provided more info now.

**Comment by rhukster** [comment]
I’ll take a look after the holiday weekend.

**Comment by rhukster** [comment]
@Gymnae sorry this one slipped by on my radar.  is it still an issue?

**Comment by Gymnae** [comment]
Hi @rhukster , yeah it is sill an issue, or more likely a nut I'd like to crack in order to use the plugin. I am not sure if my complicated method of parsing a given folder with the filtering and stripping and page.find() is still required - it worked fine when I created this method a couple of years ago

**Comment by rhukster** [comment]
Your configuration is a bit to specific for me to easily test.

1. I created a folder in my user/pages and set the path in the page header:
```markdown
---
title: Example album title
subtitle: Example album sub title
imagefolder: /image-media/lightbox-gallery-175
---
```
2. I created a twig template file that was a regular Grav style, not a Gantry particle, but you can edit this easily:
```twig
{% extends 'partials/base.html.twig' %}

{% block content %}

  {% set page_route = page.header.imagefolder|default(particle.folder) %}
  {% set media_page = page.find(page_route) %}

  <ul class="flexbin">
    {% set gallery = md5(media_page.url) %}
    {% for image_obj in media_page.media.images %}
      <li  data-gallery="gallery-item" title="greatgallerywow" class="flexbin">
        {% set data = exif(image_obj.filepath, true) %}
        {% set title = data.IPTC.title %}
        {% set desc = data.IPTC.caption  %}
        {% set content = image_obj.cropResize(600,400).html(title, title) %}
        {% set image = image_obj.url %}
        {% include "partials/lightbox.html.twig" %}
      </li>
    {% endfor %}
  </ul>

{% endblock %}
```
3. I simplified a lot as you had a lot of regex and stuff that seemed unnecessary to me. 
4. I removed all the figure/caption stuff as that just gets in the way of glightbox.

Anyway this works for me (albeit without any grid styling), but I can click the thumb an it launches the lightbox no problem.

**Comment by Gymnae** [comment]
Hi @rhukster, thanks for spending time on this. I am not sure what needs to be done to adjust the twig code to work as a gantry particle. I added @nucleus for the include declarations. I tried the code, but it doesn't pick up any images in defined folders for me. The page is empty:
```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block particle %}

  {% set page_route = page.header.imagefolder|default(particle.folder) %}
  {% set media_page = page.find(page_route) %}

  <ul class="flexbin">
    {% set gallery = md5(media_page.url) %}
    {% for image_obj in media_page.media.images %}
      <li  data-gallery="gallery-item" title="greatgallerywow" class="flexbin">
        {% set data = exif(image_obj.filepath, true) %}
        {% set title = data.IPTC.title %}
        {% set desc = data.IPTC.caption  %}
        {% set content = image_obj.cropResize(600,400).html(title, title) %}
        {% set image = image_obj.url %}
        {% include "@nucleus/partials/lightbox.html.twig" %}
      </li>
    {% endfor %}
  </ul>

{% endblock %}

```
This is what the <bods> source code section of the rendered HTML looks like:

  ```
  <body class="gantry g-helium-style site default dir-ltr outline-iframe-gallery g-default g-style-preset6">
        
                    

        
        <div id="g-page-surround">
                                    

                                            
                <section id="g-expanded" class="g-flushed">
                <div class="g-container">                                <div class="g-grid">                        

        <div class="g-block size-100">
             <div id="lightbox_folder-9255-particle" class="g-content g-particle">            <ul class="flexbin">
           </ul>
            </div>
        </div>
            </div>
            </div>
        
    </section>
            
                        

        </div>
                    

                <script src="/user/plugins/gantry5/assets/js/main.js" ></script>


    

        
    </body>
```

**Comment by Gymnae** [comment]
Just to add to the video issue: The above happens with all formats I tried: mp4, m4v, webm - the behavior of the Browser remain the same. Only Safari does a good job - a first.
