### ISSUE TITLE
[site-toolbox] Add option to toggle between 'head' and 'get' requests

### ISSUE THREAD

**Issue by angusmcb** [getgrav/grav-premium-issues#177]
Hello,

My hosting provider uses [litespeed cache](https://docs.litespeedtech.com/lscache/) on their servers. 

Unfortunately, this cache responds only to 'get' requests. Please would it be possible to add an option so that warm cache can continue to use 'get' rather than 'head' requests?

Thank you!

**Comment by rhukster** [comment]
I'll take a look at this soon

**Comment by rhukster** [comment]
Added this for next release
