### ISSUE TITLE
[typhoon] Cover image fits the height of the screen

### ISSUE THREAD

**Issue by rfvallina** [getgrav/grav-premium-issues#179]
Hello,
I'm using typhoon theme one-page design.
I would like the cover image of the Top subpage to fit the height of the screen, no matter what size it is. Is that possible from the grav admin plugin? Or it has to be done by css? Could you please explain how to achieve this?

**Comment by rhukster** [comment]
See my answer here: https://github.com/getgrav/grav-premium-issues/issues/181#issuecomment-965733472
