### ISSUE TITLE
[nextgen-editor] Cannot be used in a list

### ISSUE THREAD

**Issue by robertbak** [getgrav/grav-premium-issues#180]
When used inside a blueprint list item, after adding a new item,  the editor never loads inside it (works after the refresh).

**Comment by w00fz** [comment]
I can see that happening, lists are a bit outdated in their codebase and require a lot of logic on the developer side to make complex JS work to auto-initialize. I'll look into it.

**Comment by robertbak** [comment]
Great. I managed to patch the code with an ugly hack, but if I can add my 2 cents - it's a common issue when extending the admin panel - interaction between fields and their values. Would be nice to have some sort of subscription model for value changes (broadly, so that includes uploads and list elements being added/removed)

**Comment by w00fz** [comment]
Finally managed to get this sorted, will be available in next version.

FYI the subscription model you mention I implemented in the early days with Grav Admin in the form of an observer. It is a bit of an unknown but you can listen to the global Grav Admin event `mutation._grav` (`jQuery('body').on('mutation._grav', (event, target) => {})`). 
This will be triggered anytime there is a list field change, then you can check if the target children have the field of your interest and usually what I do is initialize the element i need.

> Note: You have to listen to the jQuery event because that's how the original admin was written with.
