### ISSUE TITLE
[typhoon] How to make hero image bottom aligned with min-height 

### ISSUE THREAD

**Issue by JvanDee** [getgrav/grav-premium-issues#181]
Not sure if this is the right place to ask, because it maybe more of a tailwind question but i'll give it a try:

I’m fiddling around with the typhoon theme and tailwind for a while now, adjusting the typhoon theme to me needs.

One thing i really can’t wrap my head around is adjusting the hero’s background image properties. As i said, i'm afraid this is mostly a tailwind question though:

The hero image height is depending on the content (title, content, …). I would like to
a) have the background-image always ‘bottom-aligned’, meaning it only cuts off at the top with the bottom always visible.
b) having a minimum height even if there is almost no content (e.g. a one-line header). For example showing always 50% height at minimum.

I tried out many different tailwind classes without luck for the hero section:

![image](https://user-images.githubusercontent.com/844032/140571251-886dbfc5-d74d-4646-98e1-b6cc9c63507e.png)

It would be really awesome if someone could give me a hint in the right direction how to achieve this.

**Comment by rhukster** [comment]
To bottom align the image, on that `<img>` tag where it has `object-cover` simply add `object-bottom`.  This will force the object to cover the space but align bottom.

To set a min height for the hero to be 100% of the viewport height, you could simple add `h-screen` to the classes of the `section#hero`.  For 50% height, you can use of dynamic classes using the `[]` syntax to add `h-[50vh]` which is 50% of the viewport height.

of course you will need to make sure that tailwind recompiles to pick up these new classes.

**Comment by JvanDee** [comment]
@rhukster ,  thank you very much!
