### ISSUE TITLE
[seo-magic] Every page seems to generate with og:type website

### ISSUE THREAD

**Issue by hdwebpros** [getgrav/grav-premium-issues#182]
I was going mad trying to figure out why my only site with SEOMagic kept having Facebook images disappear.

Then, I looked at the code. When I have SEO Magic enabled, it generates `<meta property="og:type" content="website" />` HTML for _every_ page.

That HTML / og:type should really only be on the home page. The `content` should be `"article"` for interior pages.

Related post: https://stackoverflow.com/questions/7572441/facebook-like-showing-cached-version-ogimage-way-to-refresh-or-reindex-it#answer-57827591

Plugin v. 4.0.0
Grav v1.7.24

**Comment by rhukster** [comment]
hmm.. I will look into this first thing next week.

**Comment by rhukster** [comment]
This has been fixed in 4.0.1 which should show up shortly.
