### ISSUE TITLE
[cloudflare] Cant save MX record. Failed to parse. priority must be a number.

### ISSUE THREAD

**Issue by hotdoy** [getgrav/grav-premium-issues#183]
![image](https://user-images.githubusercontent.com/11572524/141519546-6f2faa5f-2467-43d7-bf0e-4ced08025489.png)

Whatever number I put in the priority field is not validated properly.

**Comment by w00fz** [comment]
Interestigng. I suspect I’m not forcing it as a number value but string.

I’ll check this out today.

**Comment by w00fz** [comment]
@hotdoy this is sorted now in v1.0.2 which should be available in GPM soon.

Cheers
