### ISSUE TITLE
[typhoon] Italics not showing on rendered page

### ISSUE THREAD

**Issue by PalmTreeVI** [getgrav/grav-premium-issues#184]
Italics text does not show as Italics on the rendered page.  The ```<em></em>``` tags are in the generated code, but the text does not display italicized.  It does show/work properly in the editor, just not in the produced page.

Grav 1.7.24
Typhoon Theme 2.1.4

![Screenshot_2021-11-15_07-22-40](https://user-images.githubusercontent.com/64500998/141782593-fa70d7dd-a32b-4108-bbd5-b78675ca3b96.png)

**Comment by rhukster** [comment]
Hmm.. I thought we addressed this already. I'll test and get back to you.

**Comment by rhukster** [comment]
<img width="732" alt="CleanShot 2021-11-16 at 16 08 50@2x" src="https://user-images.githubusercontent.com/1084697/142080774-16dc1da7-93a9-4578-bdbb-9f17feab2400.png">

I can't reproduce this.. Works fine with default Typhoon and `Inter Var` font.
