### ISSUE TITLE
[typhoon] usage of Native Lazy Loading of Images

### ISSUE THREAD

**Issue by Aminejohda** [getgrav/grav-premium-issues#186]
Currently, the Typhoon Grav theme does not use lazy loading markup. however, Grav 1.7, has built-in configuration support for this (see https://github.com/getgrav/grav/issues/2910 and https://github.com/getgrav/grav/search?p=2&q=lazy).

and for this, I want to ask if there is some reason behind the decision not to implement it?

thank you

**Comment by rhukster** [comment]
Typhoon is intended to be used as a basis for your own custom theme.  If you want to use it, you can simply enable the Grav system option, or use the markdown syntax in your content.

**Comment by Aminejohda** [comment]
@rhukster but as I understand it's just a flag under `config.system.images.defaults.loading` that could be used in twig/markdown and not Globally in the Grav system option right ?

```TWIG

{{ (page.media|first).loading(config.system.images.defaults.loading).html() | raw }}

OR

{{ (page.media|first).loading('lazy').html() | raw }}
```

**Comment by rhukster** [comment]
If you set `images.defaults.loading: lazy` it should make all 'content' based images to be lazy loading.  If you wanted to set images that are loaded via Twig, then you are correct, you will need to explicitly set `.loding('lazy')` on the media object.

This is not really something that is commonly requested, but if you want to do it, simply copy the Typhoon theme and edit the twig templates to your needs.
