### ISSUE TITLE
[seo-magic] Facebook preview images disappear only on site with SEO Magic

### ISSUE THREAD

**Issue by hdwebpros** [getgrav/grav-premium-issues#187]
We have dozens of Grav sites, almost all of them have Facebook posts that link to them. In every case, the preview image shows correctly. However, for the lone website that we have that has the SEO Magic plugin, the Facebook preview image goes to blank white constantly. 

Here is the Facebook page: https://www.facebook.com/hoistdigitalagency 

You can see many post preview images that are blank.

Here is the kicker: If we ask Facebook to refresh the preview image, it shows properly. If I inspect the code, the image shows properly. If I use their [official debugger](https://developers.facebook.com/tools/debug/), the images show properly. The code and site looks set up properly. However, this is literally the only Grav site we have tried SEO Magic on and literally the only Grav site that has these preview image issues. There are no other plugins on the Grav site that would cause issues, it's fairly bare bones.

Versions
SEOMagic: 4.0.1
Grav v1.7.25 - Admin v1.10.25

**Comment by rhukster** [comment]
I hear what you are saying but it really sounds like a facebook problem.  The image is there, facebook even finds the image when you refresh it.  The debugger shows it, and any other debugger shows it. I think you'll find if you use anything else (twitter etc) it will work fine too.  Everything points to a problem with facebook. 

However, i just did some googling and I might have a workaround for you to try... stand by.

**Comment by rhukster** [comment]
Ok so if you open up `classes/SEOMagic.php` and line 160 should be something like:

```php
$metadata['og:image'] = $metadata['image'];
```

after that add:

```php
if (Utils::startsWith($metadata['image'], ['https://', '//'])) {
    $metadata['og:image:secure'] = $metadata['image'];
}
```

I read that a workaround for this HTTPS bug with Facebook specifically is to add an `og:image:secure` to the same image (assuming its an HTTPS image).  let me know if this works. 

Alternatively you could try `og:image:url`.. but I think `secure` could be the one.

**Comment by rhukster** [comment]
@hdwebpros ???

**Comment by hdwebpros** [comment]
Hey, @rhukster! For some reasons I didn't get these notifications. I'll add that code and let you know the results

**Comment by hdwebpros** [comment]
Over the weekend about 20% of the preview images turned to white.

**Comment by hdwebpros** [comment]
One answer shows:

> The main problem is URIs using HTTP works just fine and URIs using HTTPS do not. So first of all, you should try to change your og:image:secure property to og:image:secure_url, because due to documentation there is no og:image:secure property.

**Comment by rhukster** [comment]
best way to test this is to mess about with line 162 in `SEOMagic.php`.  Currently it's:

```php
$metadata['og:image:secure'] = $metadata['image'];
```

but you can try: 

```php
$metadata['og:image:secure_url'] = $metadata['image'];
```

also you can add one for `og:image:url`also.  Let me know if any of those help?

**Comment by hdwebpros** [comment]
Okay. I edited that code and refreshed the attachments. I'll check back in a few days to see if they went blank or not

**Comment by hdwebpros** [comment]
@rhukster a few images went white again already. I checked a WordPress client of ours and the difference in the markup is that it has the width and height defined.
```
	<meta property="og:image" content="https://frador.com/wp-content/uploads/2013/07/firepit_1.jpg" />
	<meta property="og:image:width" content="518" />
	<meta property="og:image:height" content="393" />
```

How would I get that part of it figured out?

**Comment by rhukster** [comment]
in that same `SEOMagic.php` file, i've now replaced that whole if block with:

```php
if (isset($metadata['image'])) {
    $metadata['og:image'] = $metadata['image'];
    $metadata['og:image:width'] = $this->config->get('plugins.seo-magic.images.size.x');
    $metadata['og:image:height'] = $this->config->get('plugins.seo-magic.images.size.y');
    if (Utils::startsWith($metadata['image'], ['https://', '//'])) {
        $metadata['og:image:secure'] = $metadata['image'];
    }
}
```

**Comment by hdwebpros** [comment]
Thank you. I inserted that code, fought with Facebook for an hour, and for now my images all show. I think this is the right path and will ultimately at least help. Please leave this open for a few more days, I'll check again and confirm that the fix is working.

**Comment by rhukster** [comment]
Good to hear!  It's commited as you see it above.  It will be part of the next release anyway.

**Comment by hdwebpros** [comment]
I just checked again. All images still show. Closing. Thanks for your efforts!

**Comment by hdwebpros** [comment]
I checked again and images are missing again. I dug into this further and perhaps found another thing to button up.

I'm not sure how the code that starts with `<script type="application/ld+json">` is generated, but I compared it to websites with working preview images on social media and noticed a few differences. I keyed in on `"@type": "ImageObject"` for this:

- It doesn't use the resized cached image that is on the article, it uses the large, original image
- It is missing `"inLanguage": "en-US",` and `"contentUrl": "",` attributes

Also, if you look at the entry under `"@type": "Article"` it is missing the `"thumbnailUrl":` attribute, among others that aren't likely as important.

**Comment by rhukster** [comment]
What is this script tag you are mentioning? It's not something SEO-Magic is outputting (at least i don't recall it).

**Comment by rhukster** [comment]
please reopen this if you have any more info.  Cheers.

**Comment by rhukster** [comment]
I think that the latest 5.5.0 version of SEOMagic will address your issues.  Via another ticket it was determined that facebook is caching the filename of the image, and when you clear cache, that file is deleted, and FB is not smart enough to look at the tags again.  We now proxy the image via a consistent URL.
