### ISSUE TITLE
[site-toolbox] Make HTTP connection timeout configurable in warm cache

### ISSUE THREAD

**Issue by bvboldrik** [getgrav/grav-premium-issues#189]
I have a website with 400 pages and each page takes a couple of seconds to load, because it needs to do various image transformations. It seems like warm cache is unable to "warm" all pages because it hits a connection timeout? if this is the case, is it possible to make this configurable?

side request: is it possible to write the "PLUGIN_WARM_CACHE.SUCCESS_MESSAGE" to the log, because the alert you get when it finishes disappears, and I am not waiting for warm cache to finish : )

**Comment by rhukster** [comment]
Connection timeouts were added in 2.0.1 and the log message added in 2.0.2
