### ISSUE TITLE
[algolia-pro] Trigger search modal using ctrl+k

### ISSUE THREAD

**Issue by hotdoy** [getgrav/grav-premium-issues#193]
In a lot of productivity app, it is now custom to trigger the search functionality using ctrl+k.
While it might not be good for every project, it could be a quick and easy QoL feature to be able to set a keyboard shortcut trough the plugin config.

**Comment by w00fz** [comment]
Good point, I have arrow navigation as upcoming feature in the [FAQ](https://getgrav.org/premium/algolia-pro#faq:what-is-coming-next-for-algolia-pro), will definitely look into adding the ctrl+k/cmd+k shortcut.

Cheers!

**Comment by hotdoy** [comment]
Pressing ENTER after typing in the search bar should probably go to the first result as well while we're at it.
