### ISSUE TITLE
[algolia-pro] Hit preview enabled even when set to false (duplicate preview setting in blueprint)

### ISSUE THREAD

**Issue by hotdoy** [getgrav/grav-premium-issues#197]
There is a duplicate Hit Preview setting in `algolia-pro.yaml` and setting it to false only (or true) only affect one of those, making it impossible to disable preview from the admin.

![image](https://user-images.githubusercontent.com/11572524/148615604-05dd815d-bbfb-4697-9dd6-70a8e1e613fe.png)

**Comment by w00fz** [comment]
I believe the only used one is the one in the interface group.

**Comment by hotdoy** [comment]
Works great if I switch them all to false in the yaml file.

**Comment by rhukster** [comment]
It was the blueprint.. Fixed for next release.
