### ISSUE TITLE
[seo-magic] Using a Specific Image Meta Image produces an error image

### ISSUE THREAD

**Issue by ptarmic** [getgrav/grav-premium-issues#20]
On a page I have added a screenshot png file to the Page Media. In the Meta Image section I added a Specific Image.

![unknown](https://user-images.githubusercontent.com/72616419/105381268-bd466b00-5c06-11eb-9197-ea4e7401eb47.png)

 When I view the page the image link is an "error". Its also "error" on the OpenGraph tab

![error](https://user-images.githubusercontent.com/72616419/105381308-c7686980-5c06-11eb-8e29-0b5d9091e993.png)

I have tried rerun generating the seo data after making my changes.
After reading through the docs I renamed my filename to `og-image.png` without success.

EDIT: forgot to mention I'm on grav 1.71

**Comment by ptarmic** [comment]
I've also tried selecting `Auto-Select available image` with the same "error" message. 
I generated the seo data again too.
The only three images in Page Media are `og-image.png` and my own named screenshots `og-image-en.png` and `og-image-fa.png`

**Comment by rhukster** [comment]
I'll take a look at this one today.  Thanks for bringing it up!

**Comment by rhukster** [comment]
Sorry will look at this plus your other one on monday.

**Comment by rhukster** [comment]
I've tested this and it looks like it's working for me.  Please now however, you must first set the "Image Type" to "Specific Image", then the "Specific Image" takes effect:

<img width="1027" alt="CleanShot 2021-01-25 at 15 49 32@2x" src="https://user-images.githubusercontent.com/1084697/105776024-0e1ad400-5f25-11eb-8d1a-1e0f96b6ce48.png">

![CleanShot 2021-01-25 at 15 50 43@2x](https://user-images.githubusercontent.com/1084697/105776061-225ed100-5f25-11eb-9fb5-5bb1ca79d9d1.png)

Also tested with PNG file.

I did notice that `Auto-Select...` does not use the specified image if it exists however, I will add this.

**Comment by rhukster** [comment]
btw @ptarmic please upload the actual PNGs you are having trouble with. I suspect that error is related to them being invalid PNGs more than anything.

**Comment by ptarmic** [comment]
I have updated plugin, deleted the cache, regenerated the seo data, created a new sceenshot and I'm still getting that "error" image.

![image](https://user-images.githubusercontent.com/72616419/105840780-79b77c80-5fcb-11eb-8a32-626a83e4fe3a.png)

creates a link with this `/images/f/a/l/l/b/fallback.jpg`


This is the image, I created it using the built in screenshot tool in FF.
![screenshot](https://user-images.githubusercontent.com/72616419/105840974-cd29ca80-5fcb-11eb-8546-45fc6ce5b7e8.png)

**Comment by rhukster** [comment]
i'll test this image later.

**Comment by rhukster** [comment]
<img width="1080" alt="CleanShot 2021-01-26 at 10 44 03@2x" src="https://user-images.githubusercontent.com/1084697/105882877-6dc7bc80-5fc3-11eb-87b6-0fdf19f117e6.png">

Using my own test bed, I uploaded your PNG and specified it in the SEO magic config.  And it works fine. 

My hunch is that you actually have a problem with PHP/Grav rendering PNG images on that machine.  If you added that PNG as an image in a bit of markdown content, it would probably also have the error.  THat usually means that you are missing a PNG library, or PNG support in PHP itself.

**Comment by ptarmic** [comment]
I have many png images throughout the site without any issues.

I've tried a jpg and am still getting the same error.
![image](https://user-images.githubusercontent.com/72616419/105974482-dd05e500-6085-11eb-8d86-095303e6c65c.png)

**Comment by rhukster** [comment]
I think this might be related to some other plugin you have installed. Which plugins do you have on your system?  I know that `imagecreate` has caused problems already in Grav 1.7 and even disabling it is not enough, but there are probably others that have not made their plugins 1.7 compatible yet.

**Comment by ptarmic** [comment]
I have created a new dev server instance, installed grav (1.7.3), admin panel and seo-magic. No unrequired plugins, no theme, no files from dev or live. And am still getting the same "error" image. I've tried using .jpg and png files, choosing specific image or auto select, even using a file from the images folder and every result is the /images/f/a/l/l/b/fallback.jpg

I'm running php 7.4 on dev and live

I don't really use media functionality in grav except for responsive images (retina@2x.jpg) which seems to work fine.
These are the plugins from live - nothing that uses images.
![image](https://user-images.githubusercontent.com/72616419/106034135-6dfeaf80-60ca-11eb-9652-75a51d7a4f2f.png)

**Comment by rhukster** [comment]
can you please create a quick test page and upload both the PNG and the JPG images.  Then in the content put something like this:

```md
![Screenshot PNG Image](screenshot.png?cropZoom=400,300)

![Screenshot JPG Image](screenshot.jpg?cropZoom=400,300)
```

Then view this page in Grav's frontend (or preview in admin). This will tell us if the image processing is broken for Grav or not.

**Comment by ptarmic** [comment]
Looks like image processing is working fine. I'm not really sure what to look at next. I've tried so many different filenames,types and locations I don't know what else to try but maybe its an issue with finding the file? I've put the file in the page and then used the filename on its own. I've put a file in an "images" page and used `page://images/screenshot.png`

![image](https://user-images.githubusercontent.com/72616419/106154508-942e5900-6177-11eb-8d91-1b490e0800c9.png)

**Comment by rhukster** [comment]
Did you ever look in grav.log to see if there are errors there?

If not the last resort is to zip up the user folder and let us download it and try to recreate the issue.

**Comment by rhukster** [comment]
Also don’t recall if you mentioned what platform this is on. Is it windows???

**Comment by ptarmic** [comment]
You can close this ticket, I've given up on getting this to work and have focused on improving the look of the tops of the pages instead.

To answer your questions - no errors in the grav log and I'm on linux (Ubuntu for dev not sure about the live server) and php 7.4. Thanks for your effort.

**Comment by rhukster** [comment]
Strange, i'll close, but if it occurs again, we can try digging deeper.
