### ISSUE TITLE
[nextgen-editor] Feature request: Auto Text Transformations adjustable based on page's language

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#203]
Hello,

- It would be good to have **Auto Text Transformations** activated or not, **based on the page's language**.
- Also, to **add user-defined transformations** for a **specific language**.

**For example**, quotation in « French » in some countries require unbreakable space after/before open/end quotation marks; and the apostrophes are different than “English.”

Thank you very much! :-)

**Comment by w00fz** [comment]
This is now available with release v1.1.10.

https://getgrav.org/premium/nextgen-editor/docs#transformations-per-language

Cheers!

**Comment by w00fz** [comment]
I guess I misunderstood what you were trying to do originally. Although, I just released v1.1.11 which makes it possible to  do what you are trying to do. It enables the possibility to declare custom transformations via regex transformations. 

This is to be considered an advanced feature and so it won't be available in admin. I have, however, documented it here: https://getgrav.org/premium/nextgen-editor/docs#advanced-transformations

**Comment by aleclerc7** [comment]
Oh yes, this is a very flexible solution, easy to configure (if you can figure out regex), and will work very well.

One can even add other peculiarities like non-breaking spaces before : ; ! ?.

**Q. Are the advanced custom transformations run before or after the standard transformations of the editor? (I guess they are after, which I think would make sense.)**

Thank you very much for the example with French quotes. :-) 👍

**Comment by w00fz** [comment]
Yes they are run after, they are actually run last, after also the regular custom transformations.

Glad this is what you were looking for!
