### ISSUE TITLE
[typhoon] DOC suggestion — Inheriting from Typhoon

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#204]
Hello,

Here is a suggestion to add few details if someone **inherits** from Typhoon instead of using **Copy**. A few more steps are required to make things run when modifying CSS.

Here are the proposed additions. While writing this, I also created a theme from scratch to make sure this was all that was necessary. It might be possible that a line or two in `tailwind.config.js` are not required. (Like `'./available-classes.md',`?)

Kind regards.

PS. Here is a .md file with the suggestions: [suggestions.md](https://github.com/getgrav/grav-premium-issues/files/7901769/suggestions.md).

**In: Theme Modification / Create a Custom Theme from Typhoon**

**(1) Command line should be:** (new-theme, not newtheme)

`bin/plugin devtools new-theme`

**(2) Add the following text after the paragraph on "Copy". (Just before Modify the CSS.)**

If you prefer to inherit from Typhoon and you want to configure your theme with the same features as Typhoon in Grav Admin Panel, you must copy the `form:` section of `typhoon/blueprints.yaml` into your new theme `blueprints.yaml` file. It is also recommended to copy the `dependencies:` section.

**In : Theme Modification / Modify the CSS**

**(3) Maybe after the last instruction about "npm update", add another sub-section:**

##### In your theme inherits from Typhoon

If you choose to inherit from Typhoon when creating your theme, a few more steps are required for NPM to work properly.

Before running npm install, do the following :

1. From the Typhoon theme folder, copy the following files into your new theme's folder: `tailwind.config.js, package.json, postcss.config.js`

2. In your new theme folder, modify `tailwind.config.js` to add your theme name, and add entries to point to Typhoon's resources.

`
  content: normalize([
    '../../config/**/*.yaml',
    '../../pages/**/*.md',
    './blueprints/**/*.yaml',
    '../typhoon/blueprints/**/*.yaml',
    './js/**/*.js',
    '../typhoon/js/**/*.js',
    './templates/**/*.twig',
    '../typhoon/templates/**/*.twig',
    './__your_new_theme_name__.yaml',
    '../typhoon/typhoon.yaml',
    './__your_new_theme_name__.php',
    '../typhoon/typhoon.php',
    './available-classes.md',
    '../typhoon/available-classes.md'
  ]),
`

3. Finally, create a new file in `css/site.css` with the following content: `@import '../../typhoon/css/site.css';`

You will also be able to add your own CSS declarations in this file.

Now, if you run `npm install` and `npm run build` or `npm run watch`.

**Comment by w00fz** [comment]
Thank you for taking the time to move it from discord to here, as well as the effort in putting this together.

I’ll add it to the official docs tomorrow!

Cheers!

**Comment by aleclerc7** [comment]
Just saw two typos. Here is a new .md file. :-)
Best regards!
[suggestions.md](https://github.com/getgrav/grav-premium-issues/files/7901796/suggestions.md).

**Comment by w00fz** [comment]
I integrated this in the official docs:

* https://getgrav.org/premium/typhoon/docs#create-a-custom-theme-from-typhoon
* https://getgrav.org/premium/typhoon/docs#installing-npm-to-compile-css

**Comment by aleclerc7** [comment]
This is well integrated and flows very well. Great job; and thank you!
