### ISSUE TITLE
[typhoon] Feature suggestion: fixed on-top menu with two color profiles

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#205]
Hello,

One feature I miss from Quark theme is the possibility to have an always **visible on-top menu** when scrolling down. Such a feature would be much appreciated in Typhoon.

### Colors:

- It would be great to have **two colour profiles** (background color, text menu colors with different states). One color profile for _when the menu is not floating_, but at the real top of the page, and another profile for _when the menu is actually floating_.
- Such scenarios would then be possible:
  - transparent menu background and white/grey text when over a Hero section,
  - then a white menu background with black/red text when floating over content.

### Light/dark mode:
Of course, these two color profiles should be customizable for light/dark mode.

### Height:

- Optionally there could be a **different menu height** when _on top_ and when _floating_.
- Taller when at the top, smaller when floating.
- For example, Quark theme was allowing a bigger website icon in the menu bar when at top, then a smaller menu when floating, including the website icon.

Thank you very much for your consideration.
Kind regards.

**Comment by rhukster** [comment]
This is something I plan on adding, but it does make things more complicated especially when the menu is transparent, and it needs to switch to a solid bg on scroll.

**Comment by aleclerc7** [comment]
Just saw that tailwindcss gets the trick done this way, but was not amble to see how to implement it. Maybe some structural changes are required. It will be nice to have the "on top" feature.

`sticky top-0 z-40 w-full backdrop-blur flex-none transition-colors duration-500 bg-white/95 supports-backdrop-blur:bg-white/60`

Kind regards.

**Comment by rhukster** [comment]
There's definitely more to it than just the sticky option.  Sticky only works if there are no overflows and the menu needs to support light and dark, and potentially transparent modes.

**Comment by gldtn** [comment]
I was looking all over for this, but this explain why I couldn't find it. Hope it gets implemented :)

Quick question, how you edit nav menu colors?

**Comment by rhukster** [comment]
This is ready to go for the next release

**Comment by aleclerc7** [comment]
I am eager to try out the new release! Thank you very much! 👍😎👍
