### ISSUE TITLE
[typhoon] Feature suggestion: allow pages or modular pages to customize the color profile of on-top menu

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#206]
Hello,

Some pages have Hero header, some other no.

- With Hero header sometimes a transparent menu with menu colors adapted with the Hero image is nice.
- But on pages with no Hero header, a different menu background and text color is better.

Suggestion:

- An easy way to override or redefine menu color per page, or define different menu “themes” and then specify the menu “theme” to use for a specific page would be very nice.
- This would also increase a lot the standard customization possibilities of Typhoon theme with no need customize the default theme.

Thank you very much and kind regards.

**Comment by rhukster** [comment]
You can already configure the "Header Configuration" page's Advanced properties?

<img width="1313" alt="CleanShot 2022-01-28 at 11 12 03@2x" src="https://user-images.githubusercontent.com/1084697/151599587-e5303536-af3d-4f77-88f0-688ba406d462.png">

**Comment by aleclerc7** [comment]
Maybe? I am speaking of the actual menu bar that has the site logo, and text menus. I would like to have the background, text, mouse over colors personalized for some pages. Depending on the Hero section (or module), it is required for these pages only to have better visibility.

And in doing so I suggested a kind of "theme" so to switch from one to another. But I think this part can be done with personalized CSS. I get this now.

I the provided screenshot I am not sure to understand where I could put special css classes to achieve this.

Thank you very much!
