### ISSUE TITLE
[typhoon] Feature suggestion: new modular page type to display blog posts

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#208]
Hello,

I do not know if this is possible, but I would like to suggest adding **modular page that can display a collection of items**, specifically **blog posts**, like the actual blog page.

This modular page would ask the **location of the collection** to use as blog posts, then the **number of posts** to display in a given **number of columns**. Like, display the 3 latest posts of that blog.

**Many such sections could be added** to a modular page. Like another one to display two posts of a blog entry filtered on a **taxonomy** item. (This could be done in “advanced mode” to hack the collection’s content manually.

_This modular page could also have a title, subtitle, a text section, then displaying these posts._

Thank you very much and kind regards.

**Comment by rhukster** [comment]
Are you looking for a mini-section/block that shows latest blog posts? It's pretty easy to create a little twig file that you include where you want that just does a quick collection query and then iterates over them in a list.

Here's a simple example: https://learn.getgrav.org/17/cookbook/twig-recipes#list-the-last-5-recent-bl

This is really beyond the scope of Typhoon which is to be a base-theme for custom theme development.

**Comment by aleclerc7** [comment]
OK, I see. Yes I was thinking of that, but using the actual style of the blog page. Same nice big rectangles that display the picture, tags, dates, etc. Maybe some copy-pasting of the blog twig page will work. I will look into that.
