### ISSUE TITLE
[nextgen-editor] Loading editor fails (Cannot read properties of null (reading 'push'))

### ISSUE THREAD

**Issue by JvanDee** [getgrav/grav-premium-issues#210]
Hi there!

i bought the nextGen editor a while ago and i used it a few times. It stopped working at some point while i was working on a derivative typhoon theme of my own.

I tried to use it again today without luck. Maybe you can give me a hint, how i could fix this:

![Bildschirmfoto 2022-02-01 um 18 44 29](https://user-images.githubusercontent.com/844032/152021904-987a0a62-9673-45ed-9513-9d72bc3901a3.png)

Thanks in advance for any help!
Bernhard

**Comment by w00fz** [comment]
Hey @JvanDee , sorry about the issue.

Unfortunately the error is not helping much. Would you be willing to reach out to me via DM in [Discord](https://getgrav.org/discord) and share a login so I can inspect directly?

**Comment by rhukster** [comment]
@JvanDee If you have `shortcode-core` installed, have you updated it along-side `nextgen` editor?

**Comment by JvanDee** [comment]
> @JvanDee If you have `shortcode-core` installed, have you updated it along-side `nextgen` editor?

It's installed. Everything is up to date so far.

**Comment by JvanDee** [comment]
Fyi: it was an empty toolbar.
![Bildschirmfoto 2022-02-01 um 20 13 22](https://user-images.githubusercontent.com/844032/152036201-9a16c441-e191-4cce-afa2-812794aa11dd.png)

Thanks for the super fast help  @w00fz

**Comment by w00fz** [comment]
Thanks with the help fixing the issue.

This is now also handled better in the plugin, will be available on next release.
