### ISSUE TITLE
[typhoon] Social media links in footer gone

### ISSUE THREAD

**Issue by JvanDee** [getgrav/grav-premium-issues#212]
I developed a custom theme deriving from typhoon and i always had social media links within my footer
(old functional version: [https://dev1666.web3.biohost.de](https://dev1666.web3.biohost.de)

For more comfortable development i created a git repository from this state following the grav github instructions (using the stated ignore list, [https://getgrav.org/blog/developing-with-github-part-2](https://getgrav.org/blog/developing-with-github-part-2))

I then realized that the repo version is missing the media links. No other missing stuff as far as i can see
(new broken version: [https://grav.explorlings.com/](https://grav.explorlings.com/))

I copied some user/data files from old to new and tried switching to typhoon and back to my custom theme and reinstalling. 

Would be awesome if someone could provide me with a hint how to fix this.
Thanks in advance!

**Comment by JvanDee** [comment]
I think the problem is with the svg plugin. The language icon is gone as well.
I tried to reinstall the plugin but i get an error because of a misspelled url (HTTP/1.1 404 Not Found returned for "https://getgrav.org/download/pluginss/svg-icons/2.0.1".)

**Comment by w00fz** [comment]
That URL is mispelling plugins (double `s`), where is the error coming from?

**Comment by JvanDee** [comment]
> That URL is mispelling plugins (double `s`), where is the error coming from?

It's shown when i try to reinstall the svg plugin in the admin panel
![Uploading Bildschirmfoto 2022-02-04 um 23.49.05.png…]()

**Comment by JvanDee** [comment]
FYI: I fixed the issue by removing and reinstalling my theme, typhoon and the svg plugin
