### ISSUE TITLE
[downloads-pro] RuntimeException (400) Template "downloads/404.html.twig" is not defined.

### ISSUE THREAD

**Issue by tomamr** [getgrav/grav-premium-issues#213]
Always get above Runtime Exception, when trying to enable a page with downloads-pro.
It seems that twig file is missing - where to get it from and where to copy it. 

Thanks, Tom

**Comment by w00fz** [comment]
Thank you @tomamr, looks like we have a typo in loading that template, let me fix it real quick.

**Comment by w00fz** [comment]
Actually @tomamr can you check if you have that file under `user/plugins/downloads-pro/templates/downloads/404.html.twig` ?

**Comment by tomamr** [comment]
@w00fz Yes, that file is there.

**Comment by mahagr** [comment]
Does this in admin or in the site after enabling downloads?

It would help us if you could describe step by step what you're doing, thanks!

**Comment by tomamr** [comment]
@w00fz, this happens, as soon as I enable a page containing the download plugin, configured with a file name and a route. When I hit save, the Crikey page appears and I cannot access the page anymore. Need to disable the download-pro plugin, then remove the reference to the plugin in the page, then download-pro can be enabled again. Hope this helps?

**Comment by tomamr** [comment]
@mahagr , did this help to track the issue?

**Comment by mahagr** [comment]
What I understood is that the issue happens in admin..? Unfortunately, I cannot replicate the issue.

Can you join to discord and ping me?

**Comment by w00fz** [comment]
@tomamr If you can connect with either @mahagr or myself on [Discord](https://getgrav.org/discord), and share a login we can reach, that would be great.

We are having a hard time replicating this. 

Thanks!

**Comment by tomamr** [comment]
@mahagr @w00fz could you connect and replicate with the account I prepared for you?

**Comment by w00fz** [comment]
We can definitely connect and at least try to see why the error is happening. We just don’t want you to share sensible information like accounts or zip of your site, here on GitHub.

If you can share that via Discord to me or send it via email: premium [at] getgrav.org

Thanks!

**Comment by tomamr** [comment]
@w00fz Sent the information to Matias, think 2 days ago. I'll forward, 2 minutes.

**Comment by w00fz** [comment]
Got it @tomamr , thanks - we are looking

**Comment by w00fz** [comment]
Hey @tomamr 
I tried creating a new Page (no worries, made it hidden and non-routable) as `default` type. Saved, then I enabled Downloads and I didn't get any error.

I then tried loading your existing "Files" page, enabled Downloads there and was able to save successfully.

Am I missing something or is there a particular page that is triggering that runtime error?

**Comment by tomamr** [comment]
Hi @w00fz , thanks for solving this, seems to work.
Now arises on other question: when I want a central folder (with subfolders for different topics), where would that need to be located? I have a files folder that seems in the root of the page, but if I referent it with the route option (/files/) it will complain, that it cannot find it...

Will look into SEO Magic - looks good!

**Comment by w00fz** [comment]
Hey @tomamr 

Do you mean doing something like we are showcasing in our [demo home-page](https://demo.getgrav.org/downloads-pro) (ie, https://demo.getgrav.org/downloads-pro/#cards-grid-layout) ?

If so, I think you are on the right track and perhaps your Files folder is just not of type `downloads` (see https://github.com/trilbymedia/grav-skeleton-downloads-demo/blob/main/pages/02.downloads/downloads.md). You can't really just load files from a non-downloads type.

**Comment by tomamr** [comment]
Hey @w00fz 
Yes, exactly. Seems changing the type has done something. But I don't get that good looking style you have. I only get this brown button saying download. Probably I'm doing something wrong.
In your demo page you have:
[downloads route="/downloads/photos/urban" layout="grid-files" width="300" /]

is /downloads/photos/urban an ordinary folder on the webserver? Or do you create it on the Grav CMS via "Pages -> Add" and then select Template Download?

**Comment by w00fz** [comment]
Yes that is an actual downloads type page (see https://github.com/trilbymedia/grav-skeleton-downloads-demo/tree/main/pages/02.downloads/01.photos/02.urban)

In your case this could be a downloads type page under the /files parent

**Comment by tomamr** [comment]
Great, thanks @w00fz - it seems I need to have both pages (where the file is stored and where it is shown as a download) configured with "Enable Downloads" --> Yes.
Can you tell me where to change the style of the download icon? Mine is brown and not nice looking, yours is modern bleu / white? Also the "new" label is just plain text....

**Comment by w00fz** [comment]
What's the path to the page you are seeing that ? I have your site but can't find that page.

Downloads Pro comes with its own built-in CSS, you can always disable that and do your own if it's not compatible with your theme. Or you can just style on top of the built-in one. I think it might be just a matter of inherited styling conflicting.

**Comment by tomamr** [comment]
Hi @w00fz 

/company/downloads shows that button.
