### ISSUE TITLE
[downloads-pro] Unable to use Downloads from Modules

### ISSUE THREAD

**Issue by mrmstn** [getgrav/grav-premium-issues#216]
Hi there :smile: !

I would like to add a small download section to one of my modules in a product landing page. 

What did I do?

- Create a Module (`/products/_productone`)
- Enable Download
- Upload some Files
- Set ` Include all media ` to true
- Use the Shortcode `[downloads="/products/_productone"/]` on the same page
   NOTE: without the specific route, it looks like downloads-pro will use the Parent Page, where the Module is included
- Save.
- Open the Website, scroll to the Module and look for the downloads

Result: I see the following error message
```
ERROR: Cannot find any downloads for page: /products/_productone
```

After some debugging, I stumbled upon the following line:
`user/plugins/downloads-pro/classes/plugin/Downloads.php:252`
where the following function can be found: `\Grav\Plugin\DownloadsPro\Downloads::isEnabled` 

It looks like the downloads pro plugin checks for the ` $page->routable()` properties, which is false for modules. And therefore the downloads won't be rendered and returns a 404 – which will result in the error message that I got.

**Comment by mahagr** [comment]
Like the error says, the page you use needs to exist (as a real route), so the module doesn't work as it is not a real page.

That said, I probably should disable downloads from modules.

**Comment by mahagr** [comment]
Option will not be there anymore for module pages.
