### ISSUE TITLE
[typhoon] Suggestion : feature.html.twig : if few features, no more columns than features

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#217]
Hello,

I would like to make a small suggestion:

In features.html.twig, when setting the column number, the number of columns should not exceed the number of features if there are fewer than 4 features. 

For example if there are only 2 features, the maximum number of columns should always be 2, whatever the screen size.

Thank you and best regards.

**Comment by aleclerc7** [comment]
Here is a code change suggestion:

**features.html.twig (about at line 3):**
```
{% set fcount = page.header.features|length %}
{% set columns = page.header.variation == 'vertical' ? 'grid-cols-' ~ min(2,fcount) ~ ' sm:grid-cols-' ~ min(3,fcount) ~ ' lg:grid-cols-' ~ min(4,fcount) : 'md:grid-cols-2 xl:grid-cols-3' %}
```

The user can play with the padding in the "Section Classes" to make it look nice depending on the screen width, but at least, one is not forced to use a certain minimum number for it to look "OK." :-)

Kind regards.

**Comment by rhukster** [comment]
The problem with this approach is that the way tailwind JIT works, it searches your files for matching classnames, if you build your classname with `'grid-cols-' ~ min(2,fcount)...` it won't find that match and potentially won't add the support for that class (unless you have already used somewhere else).  We would. need to use a technique where all (or at least most) of the classnames or configurations are output somewhere, and you pick from among those.

This is why we typically have logic that picks from between explicit class groupings:

```
{% set columns = page.header.variation == 'vertical' ? 'grid-cols-2 sm:grid-cols-3 lg:grid-cols-4' : 'md:grid-cols-2 xl:grid-cols-3' %}
```

One option is to provide a field that lets you explicitly set your column classes.  However you would still need to run `npm run watch` for Tailwind to pick those classes up, and compile into CSS.

Of course you could always modify the `modular/features.html.twig` file in your version of the theme with the classes you want to use.

Another solution is to simply create a new Twig template (for example `modular/my-features.html.twig`), and extend the current `modular/features.html.twig` but change the `columns` variable for you needs. Something like:

```twig
{% extends 'modular/features.html.twig' %}

{% set columns = page.header.variation == 'vertical' ? 'grid-cols-2 sm:grid-cols-3 lg:grid-cols-4' : 'md:grid-cols-3 xl:grid-cols-4' %} // or whatever
```

**Comment by aleclerc7** [comment]
For such basic tailwind classes, they could be added to `available-classes.md`. They are so basic that they are used by the text-column template.

The code could also use explicitly named classes to avoid that, it would just be longer to write, but bug free indeed.

I indeed overloaded the template but only to add this feature. (I am inheriting from Typhoon.) I did not see the problem of not having the class. Probably used somewhere else. But I get you point. I will add them into a custom `available-classes.md` of my own.

I thought that having this already as a default feature would be nice.

**Comment by rhukster** [comment]
I've added optional configurable classes fields for both horizontal and vertical layouts for next release:

<img width="1075" alt="CleanShot 2022-03-10 at 15 15 42@2x" src="https://user-images.githubusercontent.com/1084697/157763943-c7e0ee67-6413-4a09-9554-bfabbeea922c.png">

**Comment by aleclerc7** [comment]
This is a very nice way to implement this functionnality, and follows the general class personalization behaviour one expects. Great!
