### ISSUE TITLE
[typhoon] Set two times same css property

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#218]
Hi,

I encountered some cases where the same css property is set twice in Typhoon. Maybe this is on purpose for whatever reason. Anyway, here are some I saw:

**footer.html.twig line 21: (mb-2, mb-6)**
`<div class="flex social mb-2 space-x-2 items-center justify-center mb-6 md:mb-0 md:justify-start">`

**hero.html.twig line 87: (mt-5 mt-8)**
`<div class="mt-5 mt-8 flex space-x-4 {{ button_classes }}">`

**mobile-navigation.html.twig line 41 (doubles): transition duration-500 absolute**
`     class="mobile-nav invisible z-20 overflow-hidden transition duration-500 h-screen w-screen absolute top-0 flex flex-col items-center justify-around absolute opacity-0 bg-gray-800 transition duration-500">`

**post-item.html.twig line 5 (doubles): flex flex-col**
`<div class="blog-item flex flex-col items-stretch bg-white dark:bg-gray-700 h-full flex flex-col shadow-lg rounded-md overflow-hidden">`

Kind regards.

**Comment by w00fz** [comment]
Thanks
