### ISSUE TITLE
[seo-magic] Error Message at install: TypeError Argument 1 passed to Grav\Common\Utils::basename() must be of the type string, null given, called in /home/DIRECTORY/user/plugins/admin/admin.php on line 534

### ISSUE THREAD

**Issue by tomamr** [getgrav/grav-premium-issues#220]
When trying to install the plugin from the License manager, above error message appears. The plugin does not install.

**Comment by w00fz** [comment]
I’m assuming you are all up to date with Grav and Admin?

**Comment by tomamr** [comment]
Yes, no updates available for Grav and admin.

**Comment by w00fz** [comment]
Do you get the same error if you install through the plugins page? Is it specifically via license manager the issue, that you can tell?

**Comment by tomamr** [comment]
Cannot install via plugins page, as I only see the button "Buy Now"...

**Comment by w00fz** [comment]
If you see Buy Now it sounds like the license key inserted is not matching accordingly.
Can you double check in license manager you have `seo-magic` as key and that your license is the same as the one you received via email? No spaces too

**Comment by tomamr** [comment]
That was it - thanks. There was no hyphen "seo magic" replaced to "seo-magic". Thanks @w00fz

**Comment by w00fz** [comment]
Glad it was an easy one 👍
