### ISSUE TITLE
[typhoon] Hardcoded section class py-12 in blocks/base.html.twig

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#221]
Hello,

It has been long to track down.

There is a hardcoded class in the **templates/blocks/base.html.twig** that hinders using this class afterward.

**Line 35:**
`  <div class="{{ theme_var('wrapper_spacing') }} {{ theme_var('section_classes')|e }} py-12">`

py-12 hinders any other "py" classes to be used. It should either be removed, or put first in the class so that it can be overridden.

Thank you very much and best regards!

**Comment by w00fz** [comment]
Thanks @aleclerc7 that seems to have been a leftover that can be removed.

**Comment by rhukster** [comment]
Actually seems this is needed for backwards compatibility. 

You can also force an override with `!py-10` or whatever in your `wrapper_spacing` or `section_classes`.
