### ISSUE TITLE
[typhoon] layout.html.twig pr-8 not at the right place

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#227]
Hello,

**layout.html.twig line 7**:
`    <div class="{{ item_col }} md:pr-8 text-left">`

The `md:pr-8` class **should be set in line 1** like so:
`{% set item_col = show_sidebar ? 'w-full md:w-9/12 md:pr-8' : 'w-full' %}`

This way the padding-right is only visible when the sidebar is actually displayed. Otherwise the margins are not balanced on pages without the sidebar.

Kind regards.

**Comment by rhukster** [comment]
Thanks, fixed for next release
