### ISSUE TITLE
[typhoon] Suggestion for title.html.twig — if no title: no title at all

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#228]
Hello,

I would like to make a suggestion to **modular/partial/text-columns.html.twig**:

If there is:

- No title
- No subtitle
- No content

Then, do not output anything.

At the very first line of the file, the following if could be added:

`{% if page.header.title or page.header.subtitle or (include_content != false and page.content) %}`

and an `{% endif %}` at the last line.

This would allow more precise adjustment when there is no title without any need to overload the template.

Thank you and kind regards.

**Comment by rhukster** [comment]
I think you meant this for `modular/partials/title.html.twig`?  Anyway i've added this there so it will skip everything if none of the title-related fields are set.  thanks.

**Comment by aleclerc7** [comment]
Yes, `modular/partials/title.html.twig`. Thank you very much!
