### ISSUE TITLE
[typhoon] Unnecessary mt-3, and use prose_style in text-columns.html.twig

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#229]
Hello,

In **modular/text-columns.html.twig line 19**:

**Suggestion 1:**
```
    <div class="mt-3 prose {{ column_classes }}">
```

I did tests with and without the `mt-3`.
- It does not make a difference at all if it is there or not when there is a title or subtitle (or both).
- It does make a difference when there is no title and/or subtitle at all.

Removing this class would give better control when there are no titles. (One does not have to counteract the mt-3.)

I would like to suggest removing the class and leave the user with adjusting the spacing as he wants with the section_classes.

**Suggestion 2:**
Instead of `prose` class, the `{{ prose_style }}` var should be used as I see is normally the case everywhere (?).

Thank you and kind regards.

**Comment by rhukster** [comment]
Correct on both counts.. fixed for next release thanks.
