### ISSUE TITLE
NextGen: Unexpected location of initial Shortcode properties dialog (top of screen)

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-premium-issues#23]
When I page is first opened for editing, taping on a Shortcode edit button seems to have the property dialog appear at the very top of the screen:

<img width="1440" alt="2021-01-24_14-46-29" src="https://user-images.githubusercontent.com/1812771/105646192-713c3600-5e53-11eb-8cad-fddf1df52178.png">

However, if I scroll down the page (not the content area) and then re-try, the same property dialog box get displayed where expected (down in the page content area).

<img width="1440" alt="2021-01-24_15-10-06" src="https://user-images.githubusercontent.com/1812771/105646712-46071600-5e56-11eb-913a-c557514a36c1.png">

Please let me know if more info etc. is helpful. BTW, Mac Firefox and Google Chrome.

Thanks very much,
Paul

**Comment by w00fz** [comment]
hey @paulhibbitts, I can't seem to be able to reproduce this issue. Is this only happening with your button shortcode? I tested with the mark shortcode and when I edit the page and hit the gear, it always displays aligned.

**Comment by paulhibbitts** [comment]
Sorry for not getting back to you sooner @w00fz ,SnagIt has decided to stop recording videos on my Big Sur Mac! Attached is a video to try to show this behaviour, this time with Page Inject blocks:

https://user-images.githubusercontent.com/1812771/105893192-a5386800-5fc7-11eb-8649-2d3c88f80800.mp4

**Comment by w00fz** [comment]
Got it, I can reproduce now. 

Will take a look soon, thanks!

**Comment by paulhibbitts** [comment]
Oh good that you can reproduce, thanks for your patience as I go through the NextGen Editor for my upcoming presentation (if it gets accepted).

**Comment by w00fz** [comment]
This is now fixed in v1.0.6

**Comment by paulhibbitts** [comment]
Thank you @w00fz for this quick fix👍
