### ISSUE TITLE
[nextgen-editor] Question: Shortcodes - where are they documented?

### ISSUE THREAD

**Issue by tomamr** [getgrav/grav-premium-issues#230]
Shortcodes seem interesting and give possibilities, but cannot find information about. Where are they documented?
Thanks!

**Comment by rhukster** [comment]
Shortcode core is here and it provides the key info: https://github.com/getgrav/grav-plugin-shortcode-core

there are also a number of other plugins that provide their own set of shortcodes and of course you can create your own as needed.
