### ISSUE TITLE
[downloads-pro] Download button displays "File not found"

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#232]
Hello,

- Just installed the plugin. Left the config as-is I think.
- Opened a post.md page (blog post).
- Enabled Download. (Default is no for “all media.”)
- Select “button” layout.
- Add one file in the “File Overrides” (pdf).
- Add [download /] and [downloads /] in content to test both.

In both cases, the button outputs “File not found.”
If I change the layout for:
- “list”, “list-files”, “grid”, “grid-files”: it workds (even if the layout is not fantastic in a Typhoon/prose section).
- “button”, “card”: do not work. One displays nothing, the other a button with “File not found.”- “list-folders”, “grid-folders”: do not work, but these are files, not folders. So it is OK I guess.

The **[download /]** shortcode always displays a button with the error message.

The **[downloads /]** adapts to the layout. But displays absolutely nothing with “card” (and folders, of course). Otherwise it works, except for the “button” layout which has “File not found.”

Thank you and kind regards.

**Comment by aleclerc7** [comment]
Another detail.

According to documentation, **[download /]** requires an argument. But it should pick up the first file in the “File Overrides” if no argument is provided. (Otherwise it defies the purpose of defining the file in the FileOverrides.)

Also, if using **[download="file.ext”]** it does not work. But using **[download="/file.ext”]** does work (taking the file in the actual folder, which is counterintuitive).

Maybe this detail can help to nail down the issue here with “File not found”.

Kind regards.

**Comment by w00fz** [comment]
The issue is that you are not supposed to be able to select inline layouts from that list. We need to remove `card` and `button`. 

To use a single button you need to specify the filename for it, like this: `[download filename="sample.pdf" /]`

**Comment by aleclerc7** [comment]
Since [download="file"] uses the details provided in the File Overrides it would also have been nice if the first file would have been selected if no filename was provided. It would be a fantastic shortcut.

[download /] equivalent to [download="file.pdf" /] with file.pdf described with download name, etc.

Kind regards.

**Comment by w00fz** [comment]
I fixed this by removing the 2 entries from that list, regarding falling back to the first override, we need to see if this makes sense for the plugin.

Thoughts @mahagr ?

**Comment by aleclerc7** [comment]
Of course, the moment you want to change what's displayed on the button instead of "download", this becomes not very useful as shortcut. 😊

Kind regards.

**Comment by w00fz** [comment]
It’s super easy to create custom layouts or overriding the current ones. I would just override the button layout an change the wording to anything you like: https://getgrav.org/premium/downloads-pro/docs#create-custom-layout

**Comment by rhukster** [comment]
My concern with that kind of shortcut is that this is a download, and you might accidentally upload another file which might be picked up 'accidentally'.   Really a download should be explicit to ensure you are actually downloading what you intend.

**Comment by mahagr** [comment]
The fix looks good to me.

I agree with @rhukster that you really want to specify the file to be downloaded, which is true with the rest of the plugin, too. It is designed to be strict to ensure that the right people see the right files.

**Comment by aleclerc7** [comment]
@w00fz Oh! I just took a look at the button.html.twig and indeed, this is very easy to make the button appear to one's liking.

@rhukster, @mahagr, I get what you say and your concern.

For me, the file is already defined in the "File Overrides", and one can set the security features, etc.
- OK, if set to "all media" then this is another issue; there is a big risk.
- But if specifically set in File Override, this is something else.
- You could even check if there is only one file (since this is a button/card) in the File Overrides. In that case, assume that this is the desired behaviour from the user.
- The user is already used with this behaviour with the **[downloads /]** shortcode. The same logic could apply if there is only one file, specifically set (i.e. "include all media" is off, and there is one (1) file defined—the user wants a button; a list of one).
- 
Being obliged to declare the file by picking it in a list, then type the filename again in the shortcode (especially with long filenames) felt uselessly tedious for something that looked evident (that this is the only file I want to make available for download). This is just user experience feedback. :-)

But I get what you say and the risks. I think there is a very low risk of error if the user has manually set a file override, and there is only one, and there is one [download /]. It is safe to assume this is the user's purpose.

**Another solution: list of buttons**

That being said. The other option would be to support a **list-buttons.html.twig** layout.
- It would simply list buttons side by side.
- So in such a case with one file only, at least, the **[downloads /]** shortcode could be used
- The user set only one file.
- And the end result would be the same, and the user would knowingly take the risk.

Maybe the later makes more sense if you do not want to code a specific 1-on-1 use case for the [download /] shortcode.

Kind regards!

**Comment by rhukster** [comment]
it's easy enough to create a simple 2 column layout with just shortcodes in your content:

```md
[div class="flex"]
[div class="col1 flex-1"]

[download="file1.zip" /]
[download="file2.zip" /]
[download="file3zip" /]

[/div]
[div class="col2 flex-1"]

[download="file4.zip" /]
[download="file5.zip" /]
[download="file6.zip" /]

[/div]
```

A 2 column list of download buttons is a layout that you may want but perhaps no one else does.  This plugin provides easy ways to add download buttons in any content layout because it provides shortcodes. For complete control, you should use Twig templating and follow the guides in the documentation.

As stated, we don't believe it's ever a good idea to have a `[download /]` shortcode without specifying the download.  If I needed LOTS of pages where this was the case, i would do it with a custom Twig template and save myself the hassle of even writing `[download /]`.

**Comment by aleclerc7** [comment]
Thank you for your answer!

I do not want to get into an argument here. The issue is not that you cannot do it another way, even easily, but rather about user readiness. The easier to use, and less prone to need personalization, the better it is. :-)

When [download="**Your 20220309 filename, is long—or simply ugly and full of numbers.pdf**" /], and you already have set everything in _File Overrides_, this would be nice not to be obliged to type it all “again”, The [downloads /] shortcode already allows that, but not for buttons.

Kind regards.
