### ISSUE TITLE
[typhoon] Use page.summary() instead of truncate in post-item.html.twig

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#233]
Hello,

In post.html.twig line 21: `{% set summary_size = bg_image ?  page.summary|truncate(170, true) : page.summary %}`

Suggestion to use : `{% set summary_size = bg_image ?  page.summary(170, true) : page.summary %}`

I would suggest using **page.summary()** method instead of truncate because in some cases it will generate incorrect HTML (html tags not closed properly). The page.summary() method seems to do a correct job with closing opened html tags.

Kind regards.

**Comment by aleclerc7** [comment]
Hello,

In fact, if you want to fully support the `===` delimier in all cases, a check could be made. I just realized that calling page.summry() does not limit itself to the summary delimiter. *(Should this be a suggestion for Grav core?)*

The following code will handle properly all the cases.

```
{% set summary_size = bg_image ? (page.summary|length < 170 ? page.summary : page.summary(170, true)) : page.summary %}
```

Kind regards.

**Comment by rhukster** [comment]
Yes, your last suggestion is best. Thanks.
