### ISSUE TITLE
[typhoon] Sidebar: add a {% block sidebar_content %}

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#235]
Hello,

I would like to suggest adding a very simple feature in **sidebar.html.twig**: a `{% block sidebar_content %}`.

- This is a fantastic way to `{% embed 'partials/sidebar.html.twig' %}` and completely customize it in any template.
- This would make the template very flexible without even overloading it. (For those who inherit the theme.)

Code change suggestion:
- Insert after line 5 (after `<aside>`): `{% block sidebar_content %}`
- Insert before line 48 (before `</aside>`): `{% endblock %}`

Kind regards.

**Comment by aleclerc7** [comment]
A side note.

If this suggestion is implemented, I would also suggest to have the classes of `<aside>` set differently for customization.
- Have the `{{ prose_style }}` in a div instead.
- Have `col-count-2 md:col-count-1 max-w-none` as a theme_var() from the theme config page. So the right behaviour can be adjusted. (For example, only have one column at all time, instead of a split in two. — It does not look very nice in some sizes.)

I realize that this suggestion may be slowly going into the customization terrotiry. :-)

Like:
```
...
<aside class="theme_var('sidebar_classes', 'col-count-2 md:col-count-1 max-w-none')">
{% block sidebar_content %}
<div class="{{ prose_style }}">
...
</div>
{% endblock %}
</aside>
...
```

Best regards.

**Comment by rhukster** [comment]
I really don't want to add another configuration option, but i've made it so you can pass in a variable called `sidebar_classes` while embedding/including the `partials/sidebar.html.twig`.  This is a solution I often use as it means you can reuse something and easily pass in params to modify it:

```twig
{% embed 'partials/sidebar.html.twig' with {sidebar_classes: 'foo bar' %}
  {% block sidebar_content %}
  ....
  {% endblock %}
{% endembed %}
```

**Comment by aleclerc7** [comment]
Alright, I will see how it is implemented. The problem I encountered with `prose` is that it makes it difficult to apply specific layouts when the content is not general markdown text.
