### ISSUE TITLE
[seo-magic] uses cached images for og:image, facebook shares break when cache is flushed.

### ISSUE THREAD

**Issue by rotanadan** [getgrav/grav-premium-issues#237]
Since facebook keeps track of the og:image filename, the file goes away when grav cache is refreshed and the name changes on the site.
There will have to be a way to use non cached images for open graph, which is unfortunate because you would lose auto resizing.

**Comment by rhukster** [comment]
Thanks for reporting this.  We are already looking into possible solutions.

**Comment by rhukster** [comment]
I have a solution already developed that uses an internal image-proxy to provide a standardized `og:image` path that will always be valid, and then handle the image processing based on configuration when that image is requested.  This will solved the facebook issue. it will be available in the next release of seo-magic.

**Comment by hdwebpros** [comment]
@rhukster do you have any docs or code snippets on how we should fix our sites to use this new method?

**Comment by rhukster** [comment]
It automatic.  The image url should be different now referencing an image path which serves as the proxy to your configured image option.
