### ISSUE TITLE
[typhoon] Add support for tooltips

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#239]
Hello,

A suggestion to add support out of the box for "Tailwind CSS Tooltip — Flowbite".
https://flowbite.com/docs/components/tooltips/

Kind regards.

**Comment by rhukster** [comment]
Those are great, but really it's something that should be added if needed.  I don't want Typhoon to get bloated with things you have to remove if you don't want.  Better to add things you do. 

Thanks for linking this though.. I will probably make us of them in a future project!
