### ISSUE TITLE
[typhoon] Links generated by features / hero buttons / footer do not have the language code in URL

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#242]
Hello,

In a modular page, when using feature.md and hero.md (when creating buttons), the links are not generated properly in multilingual sites.
- Instead of: /en/page, or /pt/page
- Result is: /page

Same thing for footer _Menu Links_ section.

All other links in the website are correct, having the language prefix.

In admin panel, having **Configuration->Languages->Include default language** to **true** changes nothing, except that the same behaviour is seen on the default language. The language prefix in URL is not added.

Thank you for your help and best regards.

**Comment by aleclerc7** [comment]
I would like to add another issue that might be related to this one.

Making the following collection search only work in the main site language:
```twig
  {% set episodes = page.collection({ items: {'@page.siblings': page.parent.url}, 'filter': { 'type': 'podcast-episode', 'published': true }, 'order': {'by': 'date', 'dir': 'desc'}} ) %}
```

The reason is that the url has `/en/blog`

But if the same code is used without the `/en`, it works, and returns the pages in English or whatever the language.

```twig
  {% set episodes = page.collection({ items: {'@page.children': '/blog'}, 'filter': { 'type': 'podcast-episode', 'published': true }, 'order': {'by': 'date', 'dir': 'desc'}} ) %}
```

I definitely see there is a problem with the presence and absence of `/[lang]` codes in the site in general.

Thank you again for your help.
Best regards.

**Comment by rhukster** [comment]
This is because i'm liberally using the Twig `url()` function all over the place to automatically handle local/relative links so that they work in any scenario. Unfortunately when it comes to multi-lang pages, more logic is needed, such as the `Page::url()` function that can take an optional language string. 

This definitely needs addressing but I think it needs to have some thought about the best approach.

BTW, your second comment relates to another issue and potentially a bug in how collections find pages.  Do you have a sample "user" folder that already has this multilang configuration I can test with?  If so, PM me on discord with the zip file.  Thanks!

**Comment by rhukster** [comment]
Can you try something for me?

In `Utils.php` line 81 add:

```php
        // is this a page?
        /** @var Pages $pages */
        $pages = $grav['pages'];
        $page = $pages->dispatch($input);
        if ($page) {
            return $page->url($domain);
        }
```

This works for me!

**Comment by aleclerc7** [comment]
Thank you very much for all your help on this! The patch works.

There is only one problem still with the language switcher coming with Typhoon. It does not give me a correct URL for the default language of the site when the **Configuration->Languages->Include default language** is set to **OFF**.

In such a case, when I am:
- In EN, the link to switch to FR has /en instead of /
- In PT, the link to switch to FR has /pt instead of /
- All other cases work fine.

I am unable to see what it is.

I sent you my `/user`. You will be able (hopefully) to see the behaviour.
- It is the default Typhoon menu, and langswitcher, no changes.
- My theme is inherited.
- Do not be distracted with langswitcher.html.twig templates and macros, they are only used for the footer menu, which works properly. Tyhoon makes no use of these.

Thank you and best regards.

**Comment by rhukster** [comment]
what does your language config look like in system.yaml?

**Comment by rhukster** [comment]
Yes, that option is typically the favored way of handling multilingual. 

Is this the latest version of typhoons langswitcher partial?

**Comment by sebastian0119** [comment]
Alright - switched it to true.

And yes, it is the latest version of typhoones langswitcher partial. Just compared it to code in the grav-plugin-langswitcher repository.

**Comment by aleclerc7** [comment]
Hello @sebastian0119,

This behaviour has not been fixed/changed yet. Instead I made a .htaccess that handles and correct the problem (because I am using 3 different domain names in 3 languages, so this was an easy fix). But I certainly would have like it to work properly with include_default_lang=false.

So my site uses include_default_lang=false and handles the language switching partly with .htaccess. Doing so gives the desired behaviour.

But if I had only one domain name and multiple languages (like my local dev. env.), I would have liked to have the default language not visible in the URL, but only the other languages.
- I am sure it would work very well, but **there is a little glitch in the way the langswitcher generates the urls**.
- It does not work for the default language: since include_default_lang=false, **it forces the current language**.
  - If it is pt or en, then instead of a simple / it "fills in" with /[current language].

Kind regards.
