### ISSUE TITLE
[seo-magic] misstyped language constant for Twitter card type.

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#244]
Hello,

In SEO plugin config, there is a misstyped language constant in

![image](https://user-images.githubusercontent.com/66482588/158714927-811a4f8a-eb00-4dfb-b1dd-52a3ee990090.png)

Twitter Card Type: TPLUGIN_SEOMAGIC.WITTER_CARD_PLAYER
Should be (I guess): TPLUGIN_SEOMAGIC.**T**WITTER_CARD_PLAYER

Kind regards.

**Comment by rhukster** [comment]
Should of been: `PLUGIN_SEOMAGIC.TWITTER_READING_TIME_HELP`

Fixed. thanks.
