### ISSUE TITLE
[seo-magic] Enable Webshot Feature and multilingual domain names

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#245]
Hello,

My website has 3 localized second-level domain names.
- But this is the same Grav installation.
- All 3 domains point to the same site.

How can the Webshot Feature be activated for these 3 domains (and maybe more coming)?

Thank you very much!

**Comment by w00fz** [comment]
We don’t support multiple domains. For that we’ll have to make an exception and manually add your sub domains.
Please list all the domains you are using with this one instance in DM to me on discord, and I’ll get them added for you.

**Comment by w00fz** [comment]
This has been dealt with.
