### ISSUE TITLE
[seo-magic] Image type / Automatic: possible to have WebShot in the fallback?

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#246]
Hello,

When selecting how images should be provided, could it be possible to have the **WebShot Automatic Screenshot Service** somewhere in the fallback options?

I would insert it just before "First image found". So at least there would be a fair range of good options picking random stuff.

**Another possibility: customizable selection and order**

Needs will differ from one site to another and specifying the order and options desired could be the most flexible improvement to this feature.

Example of a user selection for _Image Type_:
1. Specific filename
2. Specific attribute
3. OG-Image
4. WebShot (if activated and registered)

If nothing is found, then it mean "nothing" because the user would not have chosen "First image" or "URL".

Kind regards.

**Comment by rhukster** [comment]
Custom ordering will be an option in next version:

<img width="1049" alt="CleanShot 2022-03-22 at 18 32 31@2x" src="https://user-images.githubusercontent.com/1084697/159598787-ab46ab92-c9dc-4189-ab62-5672bc55bba0.png">

**Comment by aleclerc7** [comment]
Very good new! :-) I saw that the PHP code was already ready to implement such a feature. Thank you very much!
