### ISSUE TITLE
[seo-magic] Language specific global keywords

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#248]
Hello,

It would be nice to have the possibility to set language-specific global keywords.

In the meanwhile, with language-specific domains there is the possibility to have specific config files for different domain names. Will it work if specific SEO Magic config entries in for these domains?

Kind regards.

**Comment by rhukster** [comment]
Hmm.. i think this is a bit too much of an edge case. It would require a specific format of the the configuration files with different keywords per language.  As this is not a defined thing and more of a free-form thing it would require imposing some rules.  Global keywords are generally not a good idea for SEO anyway, so not really something we want to encourage.
