### ISSUE TITLE
[seo-magic] Suggestion for Image type (image name) and multilingual sites

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#249]
Hello,

For multilingual pages, I would like to suggest adding some automatic logic for **Image Name** option.

Check in the folder if the image name is available in a specific language first.
- Same logic as Configuration -> Languages -> Include default language in file extension
- Check if `og-image.fr.jpg` exist (or `og-image.en.jpg` if in English).
- If no, check for `og-image.jpg`.
- If no, then fallback to another method.

Kind regards.

**Comment by rhukster** [comment]
I'll add this as an enhancement idea when i look at the configurable fallbacks logic.

**Comment by rhukster** [comment]
have added custom language version of the og-image in the format `og-image.XX.png` and `og-image.XX.jpg` if active language is `XX`.
