### ISSUE TITLE
[seo-magic] Description for fb/tw: possibility to use specific data

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#250]
Hello,

I tried both options for **Meta Auto-Generation -> Description Summarization**.

Both give very poor results (unreadable blog of words).

Thus, OpenGraph tab gives unintelligible text for description.

I would like to suggest giving another option, in the same mindset as the **Meta Images**: to give the possibility of a fallback system, or (as suggested for the Meta Images) to select and order the way descriptions should be generated.
1. Give an option to use a description coming from a **Specific attribute from page header**.
2. Fallback on automatic page.summary(200,true), which is not possible for blog page type, so then:
3. Fallback on automatically generated description.

This would give excellent results.

Best regards.

**Comment by rhukster** [comment]
I know the automatic descriptions need some improvements, I think some of your ideas are good, but i'm also looking into using AI generated descriptions which would produce amazing results for any page type. This is definitely something that I want to pursue for a future version. 

However, do know that meta description is not really used anymore in SEO as it's so easily manipulated, its purpose these days is mainly in how a link is displayed in search results. This makes it of less of a priority for good SEO results.

**Comment by aleclerc7** [comment]
This is nevertheless a problem because the description is being used in the FB and Twitter preview (OpenGraph).

Since I already write a short "card summary", if I could tell SEOMagic to use this summary to put in the FB and Twitter, this would do the job. Hence, the suggestion to use a Specific attribute from page header.

Later, better logic could be added. AI stuff would be great (if it works in other languages than English alone). But it would be nice to have something until this time comes.

Kind regards.

**Comment by rhukster** [comment]
I will look at this option for the next update.

**Comment by aleclerc7** [comment]
Hello,

Part of the unreadable descriptions was due to the fact that by default, `post.html.twig` in **Typhoon** theme does not have the `magic-content` class. Once added, it gives much better results! Yet, the possibility to tell SEO Magic to use a specific page header attribute is a must-have. :-)

Kind regards.

**Comment by rhukster** [comment]
FYI you can provide multiple selectors as this is an array field:
<img width="806" alt="CleanShot 2022-03-22 at 20 30 34@2x" src="https://user-images.githubusercontent.com/1084697/159612265-5c1df0d5-2381-48f2-a070-ec706bc47d21.png">

I will check Typhoon Post template.

**Comment by rhukster** [comment]
FYI I also looked into some AI options for summarization, but they are all quite expensive and not really an option for us at this time.  I have added a new option for "Header Attribute" though, so you can use an existing header attribute for your summary. This is also overridable at the page level.  So that's new.

**Comment by aleclerc7** [comment]
Thank you very much Andy! This will do the job very well.
