### ISSUE TITLE
[typhoon] mobile nav issue / no mobile navigation / big space after footer

### ISSUE THREAD

**Issue by 4glide** [getgrav/grav-premium-issues#251]
Hi all,

since I updated my theme to 2.3.0.1 and also grav to 1.7.31, my mobile navigation isnt working anymore and is giving me a big space in the normal desktop view after footer.
![2022-03-17 11_13_03-Neuigkeiten _ DPSG St  Georg - Stamm St  Georg und 5 weitere Seiten - Persönlich](https://user-images.githubusercontent.com/74159657/158788412-06d74e15-175a-425d-b8b7-c87908caf7a0.png)
mobile nav will not be displayed.
![2022-03-17 11_23_11-NVIDIA GeForce Overlay DT](https://user-images.githubusercontent.com/74159657/158789190-2b5a9a71-2163-4aaa-9a57-06f31ddaccd3.png)

![2022-03-17 11_25_35-NVIDIA GeForce Overlay DT](https://user-images.githubusercontent.com/74159657/158789538-b97a6960-be37-497d-9d77-a1e8baa0a653.png)

![2022-03-17 11_25_51-NVIDIA GeForce Overlay DT](https://user-images.githubusercontent.com/74159657/158789544-bb34d6ad-dc49-4636-a83d-aae6c5daba5a.png)

Maybe its an issue?

thx for support!

**Comment by aleclerc7** [comment]
Do you have a personalized template for your body or menu? Because on my side it was a seamless upgrade with no issue. The new fixed-to-top menu works quite well. Things have changed for the menu since the last version.

Kind regards.

**Comment by rhukster** [comment]
That sort of sounds like some files were updated and some not.  Did you create a new theme with the Typhoon theme as parent?  If that's the case you might of overidden a twig template that had changes in as part of this update.  Quick test is if you have Typhoon installed in parallel, quickly change the theme to Typhoon and see how things look?

**Comment by 4glide** [comment]
> Do you have a personalized template for your body or menu? Because on my side it was a seamless upgrade with no issue. The new fixed-to-top menu works quite well. Things have changed for the menu since the last version.
> 
> Kind regards.

its ootb, no customizing or something else.


> That sort of sounds like some files were updated and some not. Did you create a new theme with the Typhoon theme as parent? If that's the case you might of overidden a twig template that had changes in as part of this update. Quick test is if you have Typhoon installed in parallel, quickly change the theme to Typhoon and see how things look?

seems so... ive tried to pipeline the css and now its working. i dont know whats the problem. maybe there is one css file not updated or maybe the sorting or something else. but with css pipeline "active" its working. cache refresh and its working.
maybe thats the workaround. if somebody else have this issue too

![2022-03-17 20_30_17-NVIDIA GeForce Overlay DT](https://user-images.githubusercontent.com/74159657/158881237-bd31d137-64d7-4e94-a10f-acf98ce22587.png)

**Comment by rhukster** [comment]
Probably just need to clear your cache in the browser.  SHIFT-Reload.

**Comment by key-notes** [comment]
I'm afraid I'm having the same issue (as well as two others since updating Typhoon). Mobile navigation does not respond at all, even using the unmodified Typhoon theme.

Clearing the browser's cache and trying different browsers and devices did not work.

**Comment by key-notes** [comment]
Also, enabling the CSS pipeline feature (then clearing the cache) failed. I'm afraid this update "bricked" the site on mobile.

**Comment by key-notes** [comment]
Update (and another bug report): Editing /user/config/system.yaml and setting `css_pipeline: true` evidently failed to activate pipelining, even after clearing the browser's cache.

However, turning on this feature in the admin panel (Configuration -> System -> Assets -> CSS Assets -> CSS pipeline for anyone looking for it) and then reloading the page (without having to clear the cache) did work.

There is now a new bug in that on mobile, the opened menu (after tapping the hamburger icon) is now centered vertically. Maybe there's a CSS incompatibility somewhere?

**Comment by rhukster** [comment]
I can't replicate this issue on my local installations, and combined with the evidence that pipeline seems to resolve it, then I think the issue is that your CSS/JS is cached.  Usually my solution for this is to turn on "Asset timestamps". This adds a timestamp as a query string to the end of the <link> and <script> urls.  Causing the browser to refresh the cached copy when the timestamp changes.  So a quick cache-clear is all that's needed to get the browsers to refresh.
