### ISSUE TITLE
[typhoon] Mobile menu centering issue 

### ISSUE THREAD

**Issue by key-notes** [getgrav/grav-premium-issues#252]
With the latest Typhoon update, the mobile menu is centered vertically when opened. This evidently has to do with a `justify-around` CSS line. Could anyone please let me know where exactly the CSS file is located that contains this line, and the steps needed to change the justification without affecting future theme updates? Thanks so much in advance.

**Comment by key-notes** [comment]
P.S. Could this perhaps be an option added to the theme settings for those who wish to choose the vertical alignment of the mobile menu items?

**Comment by aleclerc7** [comment]
You have to modify the template `/theme/typhoon/templates/partials/mobile-navigation.html.twig`.

In **line 41** change `justify-around` to `justify-start` and you will have the menu at the top (or `justify-end`).

You will lose your changes on the next update. But you can also create a new theme inheriting from Typhoon and only modify this one file. Then after new updates, simply compare that template file with the new one to apply any changes.

Kind regards.

**Comment by rhukster** [comment]
I think this kind of modification is best left at the template level.  I will reiterate that we strongly recommend not using theme inheritance, but rather 'copy' option to create a custom theme, and you should be modifying that to your needs.  I could easily add configuration fields for every element in the theme but it really just gets further away from the core goal of this theme (which is to serve as a base-theme for developing custom themes, not a mega theme that you modify entirely through options).
