### ISSUE TITLE
[seo-magic] SEO Magic support: magic-content class not in post.html.twig

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#253]
Hello,

The `magic-content` class for SEO Magic will only appear in standard pages.
- It never displays inside **blog post** pages.
- Not in **modular** pages.

It should be added inside `post.html.twig` (**line 25**).

And maybe in the `{% block body %}` in partials/base.html.twig (**line 66 or 67**). (And perhaps the hero section too?)

Kind regards.

**Comment by rhukster** [comment]
Fixed this in a few places in Typhoon
