### ISSUE TITLE
[seo-magic] Images not working if Image Size Y not explicitly set

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#254]
Hello,

The Meta Images will always fail for fb/twitter if the `Image Size Y` is not explicitly set.

The problem is in `SEOMagic.php` line 270 after an image is picked:
```php
            $image = $image_media->cropZoom($image_x, $image_y)->url();
```

Whatever 'cropZoom' does, it is the culprit. It returns `error` image and fallback.jpg.

If the code is changed for:
```php
            $image = $image_media->url();
```

Everything works.

Then I realized that `$image_y` is not set by default.
- The config page says 600 (in gray).
- But it leads to the error at line 270 with cropZoom().
- If explicitly set to 600, then no more bug, everything works.

I guess the purpose was to keep the original image symmetry.
- So only one variable should be set, but the other one should be calculated proportionately.
- I guess the final code correction has to be made at **line 270** to calculate $y or $x according to the case.

Kind regards.

**Comment by rhukster** [comment]
This is fixed for next release. It will use X if Y is not set and Y if X size is not set.
