### ISSUE TITLE
[seo-magic] Suggestion for Meta Images / Specific filename : multiple names

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#255]
Hello,

I would like to suggest allowing a list of coma separated filenames.

![image](https://user-images.githubusercontent.com/66482588/159360193-553a79e0-8e95-4b21-bb32-2ea084fedafe.png)

This would give more flexibility for default behaviours.

Kind regards.

**Comment by aleclerc7** [comment]
I would also suggestion multiple page header attribute list.

![image](https://user-images.githubusercontent.com/66482588/159361250-d3a85549-85a8-4877-bdc1-2cf6cc359e63.png)

Kind regards.

**Comment by aleclerc7** [comment]
Hello,

Here is a code change suggestion for **seo-magic/classes/SEOMagic.php line 238**, function **getPageImageByType**().

```php
            case 'image_name':
                $images = array_map('trim', explode(',', $this->pluginVar($page, 'seo-magic.images.image_name')));
                foreach($images as $value) {
                    if (isset($media[$value])) {
                        $image_media = $media->get($value);
                        break 2;
                    }
                }
                break;
```

This little change will support 1 or many filenames separated by commas. Works very well.

Usage example: `header.fr.jpg, podcast.fr.jpg, header.jpg'.

I hope it can make it (or something similar) 😊.

The same logic can be used for `case 'image_attribute'`, but I do not know how to make multi-level attributes work. (Like `hero.image`.

Kind regards.

**Comment by rhukster** [comment]
Sounds like a decent idea.. i'll take a look.

**Comment by rhukster** [comment]
This is complete and ready for next release for `image_name` and `image_attribute`
