### ISSUE TITLE
[seo-magic] Meta Images and multilingual/domain site, a little glitch

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#257]
Hello,

My site has 3 domains for 3 languages. This is the same site, just overriding the /lang prefix for a domain.

For the Meta Images of SEO Magic:
- The option for a specific filename has been selected for the main site (header.fr.jpg).
- In /user/domain-pt/config/plugins/seo-magic.yaml then single entry has been added to override:
```yaml
images:
  image_name: 'header.pt.jpg'
```
- Same thing for the domain in pt.

But it looks like when it is time to process this setting it is not taken into account.

But if I login in the Admin panel on domain-pt, then I see that the override for that domain is properly displayed inside SEO Magic. So the admin panel displays the 'localized' config, but this actual output does not work for FB/Twitter image in the correct language.

Is there a way to make this work?

Thank you very much for your help.

**Comment by rhukster** [comment]
This sounds like the same issue as #258 

Again doesn't sound like an seomagic issue, more like a config/setup/admin/expectations issue.

**Comment by aleclerc7** [comment]
Hello,

After a good night rest, I do not know what has changed, but everything is working. There might have been something with cache or whatever things my host is using to maybe optimize php or whatever. Anyways, this is working as expected. SEO Magic is responding correctly responding to domain-specific config.

Kind regards.
