### ISSUE TITLE
[downloads-pro] Possibility to have a fake file extension on downloads

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#260]
Hello,

I use Downloads Pro for podcast, and it works well with some players. But some others are confused by the fact that there is no file extension (after the ID).

Would it be possible to use a fake file extension after the ID and downloads pro know about this and simply ignore the extension to serve the file. This would allow users to append random file extensions to the file ID and it would work.

For example:
```pages/id:31dac26e22d3c5766c86134e2a1bb8b0```
would become:
```pages/id:31dac26e22d3c5766c86134e2a1bb8b0.mp3```

Yet, Downloads Pro would know, and simply ignore whatever comes after the "." in the request so to get the ID and deliver the file as expected.

Doing so would allow template designers to append any desired file extension, and everything would still work well.

Thank you and kind regards.

**Comment by rhukster** [comment]
shouldn't be too hard to do.. i would suggest using the native file extension at the end so you don't have to configure anything special.

**Comment by aleclerc7** [comment]
Absolutely, it is my intention to `filename|split('.')|last` to avoid issues. But on the plugin's side, it should not matter what extension it is. :-)

Thank you very much to look into this!

**Comment by rhukster** [comment]
This functionality has been added for next release. This next release does require latest Admin which in turn requires latests Form release. All those are going to be released on monday so that's when I expect this to be released also.  Cheers.

**Comment by aleclerc7** [comment]
Great news! I am looking forward to this specific feature.
