### ISSUE TITLE
[seo-magic] Crash: Undefined variable: summary

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#262]
Hello,

SEO summary description:
- Meta Auto-Generation -> Description Auto-Summarization: Page Header Attribute(s)
- Summary Header Attribute/s: card_summary, hero.content

In the Admin, if opening a page where none of the "Header Attributes" are found, there is a crash in `SEOMagic.php` line 364 "Undefined variable: summary." (Also makes the same crash on the website when trying to open the page.)

![image](https://user-images.githubusercontent.com/66482588/160475969-bc4069be-a5af-4c6f-bf2d-8dfbacae9875.png)

Kind regards.

_PS. A fallback mechanism, like for images, would have been nice for the summaries._

**Comment by rhukster** [comment]
link 327 add:

```php
$summary = '';
```

**Comment by rhukster** [comment]
BTW, i think in terms of summary it will be confusing to fall back to other approaches.  Better to display empty so that you realize your attributes are not working as intended. If it fell back to something else transparently, you might not realize why the summary was the way it was if you were expecting something else.

**Comment by aleclerc7** [comment]
Thank you! It works. 👍

For the no-fallback, I understand what you say.

Maybe a special attribute name to tell SEO Magic to pick up its calculated summary? Like `hero.content, [seo-magic]`? :-) So it would be a purposeful opt-in for this behaviour. When the auto-summary becomes very good, the header attributes will (could) become overrides when needed. (I was seeing the attributes more as overrides, not as a fully independent system in itself. The attributes would be the primary source, then the automatic stuff, then the manual per-page overrides if needed.)

Kind regards.
