### ISSUE TITLE
[seo-magic] Data refresh: HTTP 503 after few pages

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#263]
Hello,

Using SEO Magic 5.0. I get a 503 error when clicking on refreshing SEO Data, the task is never completed. The HTTP 503 error is always displayed after a certain time (maybe a minute or so?). (The issue was there in the previous version.)

This problem is on the production server (hosted).

When I look at Tools -> Log, and Tools -> Report, I see that SEO Magic is **parsing only 2 pages** (in the about section), and that is it. 

I also see in the LOG that it is looping on some pages, for whatever reason.
```
March 28th at 7:21pm | NOTICE | SEOMagic: processed https://domain.com/a-propos-de/page (200)
March 28th at 7:21pm | NOTICE | SEOMagic: processed https://domain.com/a-propos-de (200)
March 28th at 4:59pm | NOTICE | SEOMagic: processed https://domain.com/a-propos-de/contact (200)
March 28th at 4:59pm | NOTICE | SEOMagic: processed https://domain.com/a-propos-de/page (200)
March 28th at 4:59pm | NOTICE | SEOMagic: processed https://domain.com/a-propos-de (200)
```

This log is complete. It hangs there with the 503 error. It takes about a minute.

Kind regards.

**Comment by rhukster** [comment]
503 is service unavailable, so probably related to hosting, webserver, security settings etc. This can definitely happen if you have cloudflare or some other security system in between your webserver and the browser. These might consider the crawler that SEO-Magic is using to be a DDoS attack.  If you know what's limiting your access, you might be able to whitelist the Crawler's user agent, or configure SEO magic to use a custom one.

**Comment by aleclerc7** [comment]
Oh! Very good point, I did not know about these possibilities. I will close this ticket and contact my hosting provider about this and see with them how this can be fixed. Thank you for your input on this issue. Best regards.

**Comment by aleclerc7** [comment]
I am sorry, I mistakenly tested my local devel server. The production server is still not working despite the sitemap correction. False flag. I do not know what is going on. The Warmup cache plugin works well. On my cPanel I see nothing that would cause issues. I need to further investigate.

**Comment by rhukster** [comment]
It is still coming from the web server. The server sends those 503 responses either by being overworked or as ddos protection. 

One suggestion is to disable the link checker. It does add many more requests as it has to try to hit all the links in a page. The same urls are cached so the same ones are not checked every page but it still can be a lot.

you can also try reducing the concurrent connections.  This will our less strain in the server but will make things run slower. 
 
The last thing it could be is related to the fact that very slow to build/cache pages might timeout before a reposnse is received. You can increase the connection timeout to address this.

**Comment by rhukster** [comment]
Seems you sorted it yourself.

**Comment by aleclerc7** [comment]
Yes, thank you @rhukster! I saw that there was artificial limits. But at least SEO Magic works even on the lowest of the low! :-)

I will think about the possibility of upgrading my plan. Especially since I now host podcasts. I saw that this is much more demanding for this low budget option.

Thank you for your help and feedback!

**Comment by rhukster** [comment]
Not to push our own stuff but we do offer managed hosting where we have staging plus production environments and tweak for performance and  security.  And we can host at data centers all over the world. https://trilby.media/services/hosting
