### ISSUE TITLE
[seo-magic] Page keywords not generated?

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#268]
Hello,

The keyword generation is active in the plugin, but it looks like it does not compute keywords anymore. If I go to a page where there are no keywords and click save, none are generated. (And there is a lot of text in the page.)

`autogenerate_keywords` is set to true.

I saw this behaviour because some pages had keywords from the same page in but in the main site language instead of the actual page language. When saving these page again, nothing changed in the keyword list; still the same list in the main site language. It is neither cleared nor regenerated—unless it actually looks at the page in the main site language, but I would be surprised.

Then I tried other pages. Upon saving, no keywords are generated. Most of the pages have no keywords.

Kind regards.

**Comment by rhukster** [comment]
sorry just realized these tickets existed!  just catching up now.

I will investigate.
