### ISSUE TITLE
[typhoon] Mobile Navigation stopped working after upgrading to v2.3.2

### ISSUE THREAD

**Issue by mcanfieldus** [getgrav/grav-premium-issues#269]
Current version Grav v1.7.32 and using Typhoon Premium v2.3.2 theme.  

Mobile Navigation stopped working on https://www.mudtrucknation.com after upgrading Grav and Typhoon.  If I click on mobile navigation, nothing happens and then I am unable to scroll down on the page.  I have tested this on multiple mobile devices.  I am not positive if this started with Typhoon v2.3.0 or v2.3.2.

This was not an issue on previous versions of Grav/Typhoon.  I have not made any template/layout changes.

**Comment by w00fz** [comment]
hey @mcanfieldus 
I think the issue on your site specifically is that you don't have the updated compiled class. This step is necessary to ensure classnames used (such as `fixed`) are available to the browser for rendering.

I'm not sure how you upgraded your site but copying over just some of the templates is not enough to inherit also all of the stylesheets.

See this guide on how to do that: https://getgrav.org/premium/typhoon/docs#building-tailwind-for-production


If this is an issue with the way the typhoon release ships the stylesheets, then that would be a different issue that probably @rhukster would know about.

Hope this helps.

**Comment by mcanfieldus** [comment]
Hello @w00fz 

I updated the template directly from Grav's Admin plugin console.  Shouldn't that update the entire template correctly?

Thank you for your time.

**Comment by w00fz** [comment]
If you want to move it to production, there is a Synchronize button below your logo, that's what takes the staging changes to production.

![CleanShot 2022-04-06 at 11 43 21@2x](https://user-images.githubusercontent.com/11734/162046140-3ec1dd34-2029-48ce-8bf9-43a3557919f7.png)


Is that what you are trying to do?

**Comment by mcanfieldus** [comment]
I do not use a child theme or a created copy.

![image](https://user-images.githubusercontent.com/103128805/162046439-f19fcdf1-50b7-4648-a6ab-fb14583dcfcb.png)

**Comment by mcanfieldus** [comment]
Also, I do not know where that synchronize button is.  My apologies I am a basic Grav user.

**Comment by w00fz** [comment]
Side note: Sorry for the confusion @mcanfieldus , i wrote that now deleted reply in the wrong issue :)

**Comment by rhukster** [comment]
It sounds like a cache issue to me.  However a theme update is a 'copy' and not a 'replacement' like a plugin update.  It's possible that something didn't get updated due to file permissions. If you have not made changes, i suggest removing and fully reinstalling.
