### ISSUE TITLE
[lightbox-gallery] Adding additional Shortcode attributes

### ISSUE THREAD

**Issue by PeterB513** [getgrav/grav-premium-issues#270]
I tried to add additional (Shortcode) attributes  in this plugin.  I tried to add a attribute: year. What i did:
1 Added a field in the gallery.yaml:
. year:
     type: number
     label: number 
2 Added a field in the partials/lightbox.html.twig:
{% if year %}data-year=“{{ year }}”{% endif %}
3 In the gallery.html.twig I put an extra line under the line where the variable title is defined:
{% set year = item.year %}

I tested this solution but I didn’t get the attribute year when I select a photo.what should I do to get this attribute displayed? I am not that good in this but I like to present my family photos with additional info in a grav enviroment.

**Comment by w00fz** [comment]
Hey @PeterB513, 

It doesn't quite work like that, the `data-X` are not customizable, they just come from the underlaying library we use and `data-year` is not something the library is aware of.

However, what you did in `gallery.html.twig` is correct. What you can do is to add the year in the title, for example `My first car (2011)`.

To do so, you can change line 11 in `partials/lightbox.html.twig` from:

```twig
{% if title %}data-title="{{ title }}"{% endif %}
```

to:

```twig
{% if title %}data-title="{{ title }} ({{ year }})"{% endif %}
```

**Comment by PeterB513** [comment]
Thanks it works. I was thinking of combining this solution with flex objects so that I can store and search my photos in a json database.  Because of the library restrictions this is however not possible. Or is it?
