### ISSUE TITLE
[algolia-pro] Broken Link to Reviews Zip File on Backend Docs Page

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-premium-issues#271]
In the [Crawl Page Search (Intermediate) section](https://getgrav.org/premium/algolia-pro/docs/backend#crawl-page-search-intermediate) of the Backend Docs page, the [download some sample code](https://getgrav.org/premium/algolia-pro/docs/backend/reviews-plugin.zip) link is broken.

**Comment by rhukster** [comment]
Thanks for reminding me!  I need to bundle up that code and make it available.

**Comment by Sogl** [comment]
Still an error 404

**Comment by rhukster** [comment]
Fixed the broken link
