### ISSUE TITLE
[nextgen-editor] Page picker can't add a link inside a paragraph or to existing text

### ISSUE THREAD

**Issue by pieter91** [getgrav/grav-premium-issues#272]
While editing a page I try to add a link to an internal page using the page picker. I select the existing text I want to make into a link and get this error in the console:

```
CKEditorError: model-position-before-root {"root":{"data":"Page-title"}}
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-position-before-root
```

Here, "Page-title" is the automatically generated slug for the page. 

After the error occurs the whole editor stops working. The error also occurs when trying to add a link without having text selected. 

Grav v1.7.32 - Admin v1.10.32 - NextGen Content Editor v1.1.11

**Comment by w00fz** [comment]
This is now fixed in the v1.1.12 release.

Thanks!
