### ISSUE TITLE
[nextgen-editor] Feature request: Choose image manipulation options through GUI

### ISSUE THREAD

**Issue by pieter91** [getgrav/grav-premium-issues#273]
For some of our users it would be helpful to be able to limit the size of images that are placed on pages to reduce load times. 

Adding ?cropZoom(800,800) or similar isn't such a big deal for some, but not for all. 

Or will this functionality be built into the upcoming Image Optimize plugin?

**Comment by w00fz** [comment]
This is issue specifically is related to https://github.com/getgrav/grav-premium-issues/issues/148 and depends on upstream to be able to customize that input field.

Also, although not planned with the Image Optimize plugin, we are actively working on something great called Cloud Media which will completely take over Grav's current media management and will support S3-compatible storage. We will also have support for remote image operations such as resize, compress, etc, for services such as ImgIx, ImageKit and such.

This will dramatically improve the loading time of media assets for Grav sites and integrate with the services Edge cloud which will provide faster access from any part of the world. This is a generic limitation with Grav, more than NextGen, and we are working on it.
