### ISSUE TITLE
[nextgen-editor] Feature request: Separate summary field

### ISSUE THREAD

**Issue by pieter91** [getgrav/grav-premium-issues#274]
It would be more user friendly to have a way to enter a `page.summary` without needing to add the delimiter `===`. This might be achieved by adding an optional field below the main content.

**Comment by w00fz** [comment]
The `===` delimiter is core to Grav and applies to the content field. Unfortunately we can't really split that, not with the way Grav content works.

One thing you could do is to create your own implementation of summary and add a second NextGen Editor field for the summary. It could be `header.summary` and you could treat this as if it was summary, completely bypassing Grav's one (as long as you dont use the `===` delimiter).
