### ISSUE TITLE
Wrong variable used in theme name after copy of Typhoon

### ISSUE THREAD

**Issue by jproto7** [getgrav/grav-premium-issues#275]
New to Grav and just purchased the Typhoon theme. Followed instructions for installing and likewise for making a copy of Typhoon which I named patthana. Things worked fine and results also seem okay except for one minor issue:  The 'typhoon' part of all links has been replaced by 'patthana' as in "https://getgrav.org/premium/patthana/docs".

**Comment by rhukster** [comment]
Are you talking about in the Blueprints? That's the expected behavior of the devtools plugin.  It assumes you are going to adjust those links for your own needs.

**Comment by jproto7** [comment]
So devtools is expected to generate non-functional links? Sorry for thinking it was either a bug or a momentarily lapse of reason on the developer's side. 

I didn't even know about the very existence of Grav until three days ago and allthough I've spent a couple of days reading the great documentation and checking out a large number of free themes and plugins I have yet to learn what exactly the term 'blueprints' refers to. So, I'm not talking about blueprints, I'm talking about my actual customer experience who found the working links in the original theme a handy way to reach the docs for the freshly purchased theme as well as the other links to the getgrav site.

I can understand, though, that longtime grav developers would consider those for newbies useful links just as dummy urls, not worth bothering to get right. No offence meant - apart from this totally negligible flaw I'm extremely well pleased with everything else and look forward to learn about the ins and outs of the Grav source.
