### ISSUE TITLE
[typhoon] Page menu reordering not working with page redirects

### ISSUE THREAD

**Issue by spencergoldade** [getgrav/grav-premium-issues#278]
**Theme**: 
Typhoon, fresh child

**Site**: 
bugandclaw.com

**Issue description**:
- Admin menu plugin in use
- Two menu items (Shop, Contact) redirect to external locations
- With redirects on, pages can no longer be reordered based on number prefixes causing navigation to appear in the incorrect order

<img width="559" alt="Screen Shot 2022-04-17 at 4 16 37 PM" src="https://user-images.githubusercontent.com/23743752/163734282-729c3127-2144-49ab-a27c-f6f68da8a665.png">

**Comment by rhukster** [comment]
@spencergoldade do you mind opening this up on https://github.com/getgrav/grav-plugin-admin/issues ? This is not a Typhoon issue but sounds more like an admin issue.  Cheers.
