### ISSUE TITLE
[seo-magic] Characters like "ë" are not included in keywords

### ISSUE THREAD

**Issue by AquaL1te** [getgrav/grav-premium-issues#28]
When viewing [this](https://www.zeitgeistbeweging.nl/contact) page source, the keywords are: `<meta name="keywords" content="orintatie,zeitgeistbeweging,meetings,raak,betrokken,blog,zday,chapter,home,series" />`

However, "orintatie" is incorrect. This should be "oriëntatie". Is UTF8 used for this? It seems this error is only triggered when auto-generating the keywords. When I add this keyword manually the output is: `<meta name="keywords" content="oriëntatie,orintatie,zeitgeistbeweging,meetings,raak,betrokken,blog,zday,chapter,home" />`

Using PHP 7.4.14 with Grav 1.7.3 and using seo-magic 1.0.3.

**Comment by rhukster** [comment]
SEO-Magic is currently 'Multilanguage-aware', which means it doesn't break hard with multilanguage, but then again, it doesn't really know that multilanguage is enabled either.  This is something we plan to address in the next major version.  It requires support for indexing a multi-language site 'per' language and also needs to support UTF8 and specifically special characters properly. Also the description generation via the **PHP.Science Textrank** algorithm needs to be integrated into the current language. 

It shouldn't effect any 'manual' settings for things, just auto-generated things.  This is definitely next on our list of things to work on, but I'll see if I can find a quick fix for the keywords first.

**Comment by k8n** [comment]
I would add that seo-magic strips accented characters from generated summaries as well (instead of at least stripping just the accents).

Perhaps a stop-gap solution could be to do a poor man's transliteration before feeding the texts to the algorithm? E.g. https://stackoverflow.com/q/1017599

**Comment by joschavdlinden** [comment]
We have the same problem with auto generated tags and description with German special chars ä ö ü etc. They are striped out of the words. Would be great to have a fix soon. Thank you.

**Comment by rhukster** [comment]
Sorry for the delay with this, it's definitely on my short list to address now.

**Comment by rhukster** [comment]
This is now fixed.. I plan on releasing this tomorrow

**Comment by rhukster** [comment]
I'll leave it open until confirmed by you guys :)

**Comment by rhukster** [comment]
tested and released

**Comment by joschavdlinden** [comment]
@rhukster Many thanks for the update! Works now fine! 👍
