### ISSUE TITLE
[nextgen-editor] Feature suggestion: add toolbar button for subscript and superscript

### ISSUE THREAD

**Issue by rouben** [getgrav/grav-premium-issues#288]
Thank you for fixing superscript and subscript tag parsing support in the next-get editor, issue #231.

This is a request to please add the buttons for inserting sup/sub tags into the next-gen editor toolbar to allow end-users to highlight text and mark is as super/sub script by clicking the appropriate button.

**Comment by w00fz** [comment]
You should be able to already do this by customizing the toolbar from the nextgen settings.
You should be able to use the `subscript` and `superscript` entries.

**Comment by rouben** [comment]
Thanks, that did it!
