### ISSUE TITLE
[instagram-feed] Show likes + Profil Followers + Link to follow ???

### ISSUE THREAD

**Issue by prinla** [getgrav/grav-premium-issues#289]
Any possibiliy to include the number of "likes" under each image?
And maybe the profil info on top of the images as well as a driect follow Button?

**Comment by w00fz** [comment]
This is unfortunately not possible as those information are not available to us via the Instagram Basic Display API. You can see [what's available for each insta](https://developers.facebook.com/docs/instagram-basic-display-api/reference/media#fields) from the official documentation, and it's very little.

There was a big discussion about this in #126 but we still haven't had the time to concretize or put any effort into moving to the more advanced Graph API.

Sorry this is not the answer you were looking for!
