### ISSUE TITLE
[seo-magic] WebShot Automatic Screenshot Service not creating an image

### ISSUE THREAD

**Issue by ptarmic** [getgrav/grav-premium-issues#29]
I'm getting a red box in the OpenGraph tab and on the page itself I'm getting a url like this which is link back to the page not an image.

`<meta name="image" content="https://mysite.com/?url=aHR0cHM6Ly9qYWFtLnByb2R1Y3Rpb25zL2NvbnN1bHRpbmc=" />`

![image](https://user-images.githubusercontent.com/72616419/105842465-2266db80-5fce-11eb-8a33-60ec6dc907ac.png)

I tried unregistering / registering the Enable Webshot Feature without any issues
![image](https://user-images.githubusercontent.com/72616419/105842891-d0728580-5fce-11eb-9d7a-ee899d088120.png)

Also if I unregister from the service it deletes the url in the admin panel but does not from the `user/config/plugins/seo-magic.yaml`  If add it in the frontend it gives the tick and everything but doesn't  add the url to the yaml. I have added it myself and regenerated the data but still no image gets created.
 
```
images:
  type: webshot
  webshot_url: ''

```

**Comment by rhukster** [comment]
I'm a bit confused why it says `mysite.com`, did you change that for privacy?

I replace it with your registered domain name: https://jaam.productions/?url=aHR0cHM6Ly9qYWFtLnByb2R1Y3Rpb25zL2NvbnN1bHRpbmc=

and it works fine.  

NOTE: that it might take a few seconds to generate the first time, after which it's cached.

**Comment by ptarmic** [comment]
Yeah I changed the url for privacy and to try and also to make it a little more generic as this is happening on my dev and live site which use different urls.

That image link works as a link to my site but I was expecting a link to a screenshot / image file. That's what it sounds like the service does in the docs.

**Comment by rhukster** [comment]
If your dev machine doesn't have a publically accessible URL it won't work. This is because webshot.getgrav.org is an external server we have and it has to be able to hit the page and automatically take the screenshot.  If it can't reach the URL from the internet then it won't be able to take that screenshot.  Also to try to stop abuse, it can only be configured with one URL at a time.

**Comment by ptarmic** [comment]
My dev site url is pubically accessible - when the machine is turned on - I use other online tools just fine so that shouldn't be a problem.

The link above is from the live site so that shoudn't be an issue.

**Comment by ptarmic** [comment]
I removed the plugin completely, deleted all the data I could find and reinstalled.

I'm getting a screenshot. The link is: https://webshot.getgrav.org/?url=aHR0cHM6Ly9qYWFtLnByb2R1Y3Rpb25z

Is it supposed to be a grav url or my own url like I was getting earlier?

**Comment by w00fz** [comment]
Yes it’s supposed to be a Grav url. Webshot is a feature that relies on one of our servers to capture and cache a screenshot of the site so that it can be served as OG media and you don’t have to worry about it. One of the perks that come with SEO Magic plugin.

**Comment by ptarmic** [comment]
Ok well this looks to be working then. I guess some config from dev didn't get updated in live. Thanks for your assistance.

**Comment by ptarmic** [comment]
> 
> 
> I'm a bit confused why it says `mysite.com`, did you change that for privacy?
> 
> I replace it with your registered domain name: https://mysite.com/?url=aHR0cHM6Ly9qYWFtLnByb2R1Y3Rpb25zL2NvbnN1bHRpbmc=
> 
> and it works fine.
> 
> NOTE: that it might take a few seconds to generate the first time, after which, it will be cached for future references.

I think this issue is resolved now, can you take my domain out of the url? Thanks
