### ISSUE TITLE
[typhoon] Using Webp image format in Hero

### ISSUE THREAD

**Issue by danielrpfeiffer** [getgrav/grav-premium-issues#292]
Setting a Hero image using the admin backend works well with jpg, png. 
Webp images don't seem to be supported for selection.

In which file can the filetypes be defined so the admin backend allows selecting uploaded webp files for Hero?

**Comment by rhukster** [comment]
I'll look into this.  Thanks!

**Comment by rhukster** [comment]
Added for next release.
