### ISSUE TITLE
[typhoon] feature request: please make header logo height adjustable

### ISSUE THREAD

**Issue by rouben** [getgrav/grav-premium-issues#295]
I would like to request making the site logo adjustable. At the moment it's hard-coded in logo.html.twig partial template to "h-8," however, that is too small for some logos. Since the header height is already adjustable via the {{ header_height }} variable, could you please consider introducing an additional variable for logo_height and adding it to the theme config screen?

See issue #112 for reference and screenshot.

**Comment by rhukster** [comment]
Added for next update.
