### ISSUE TITLE
[instagram-feed] * BUG? * generating HUGE image file usage?

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav-premium-issues#296]
We have instagram feed working on an incredibly simple one-page site: https://www.tarmachancafe.com

This site has image storage use to be growing out of all proportion to reason! See below...

<img width="514" alt="Zircon-Screenshot 2022-07-18 at 11 41 28" src="https://user-images.githubusercontent.com/6295710/179495363-9d22f224-0915-42e2-bca4-be7b5a644d2e.png">

All of these images seem to comprise repeat saves of the instagram feed content!? The site itself comprises one image only, any other images handled by Instagram feed.

How can I avoid them building up like this?

thanks for your help...

**Comment by MattAppleton** [comment]
Clearing the cache several times seems to have helped here... just wondering what the best approach to running this plugin is — should it be run alongside Warm-cache, and if not what would the correct cache / media file settings be? 

Many thanks!

**Comment by rhukster** [comment]
I need to investigate this to see what's going on. Thanks for bringing it to my attention.

**Comment by MattAppleton** [comment]
After clearing it out 2 dates ago, and not having toughed the site again, I am now seeing this on the server...

1.8Gb image folder...

<img width="665" alt="Zircon-Screenshot 2022-07-20 at 19 22 59" src="https://user-images.githubusercontent.com/6295710/180055372-54821686-64ab-4f24-902c-d611dfa6542e.png">

**Comment by MattAppleton** [comment]
Hi there — just wondered if there was any news here. At the moment I am setting the cache to clear / purge everyday, which for this site is not a problem, but that approach wouldn't work on other sites. Mind you I suppose it might be that the instagram feed only really works if paired up with 'Warm-cache'?

**Comment by rhukster** [comment]
Sorry Matt, got caught up with client projects and a major langswitcher rewrite. This is still very much on my radar.

**Comment by rhukster** [comment]
Took me all day to track this issue down and then backtrack with a simple fix in instagram-feed.  Released as 1.1.0.  Thanks for your patience.

**Comment by MattAppleton** [comment]
thanks! trying that now...
