### ISSUE TITLE
[lightbox-gallery] Mobile: zoom is only possible from the center of image

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-premium-issues#298]
In default mobile gallery app you can zoom image by fingers from any part of image.
In Lightbox Gallery every image zoom resets view to the center of the picture. Only then can you drag to the desired part.

My image line:
```yaml
![](1.jpg?lightbox&resize=600)
```
Lightbox Gallery options by default.
Tested on Android and iPhone.

**Comment by rhukster** [comment]
We're only able to do what GLightbox itself does.  Can you please test here? https://biati-digital.github.io/glightbox/

I thin you will find this is just how the ligthbox works.
