### ISSUE TITLE
[typhoon] No x-axis scroll on large tables possible. Content cut off.

### ISSUE THREAD

**Issue by danielrpfeiffer** [getgrav/grav-premium-issues#299]
Hello!

I'm building a site with a number of large tables.

[large-table.md](https://github.com/getgrav/grav-premium-issues/files/9173733/large-table.md)

Especially on narrow screen sizes and mobile, the content is not horizontally scrollable. Instead, it's cut off. 

**Screenshot: Full width desktop = OK**
![1  Screenshot from 2022-07-23 14-23-48](https://user-images.githubusercontent.com/77896852/180604844-1ded2ed0-01f3-4027-8c8f-ef666140fc49.png)

**Screenhot: Mobile/Narrow = Tables cut off, no horizontal scroll bar**
![2  Screenshot from 2022-07-23 14-24-34](https://user-images.githubusercontent.com/77896852/180604855-daf6d325-5070-4a33-b554-ffcfb0264e7c.png)

It seems to be an issue related to the typhoon theme itself. 

I tried the following:

1. https://stackoverflow.com/a/71485229
2. https://github.com/trilbymedia/grav-plugin-shortcode-nextgen-editor#div

Nothing takes effect. Tables are cut off from the right. (NextGen Content Editor installed as well)

Please advice.

Thank you.

**Comment by rhukster** [comment]
i will take a look.

**Comment by rhukster** [comment]
I was able to get this working quite easily.. First you have to wrap the markdown table in a shortcode `[div][/div]` tag because wrapping in HTML `<div></div>` will disable any markdown inside HTML. That's just part of the markdown specification. So first you will need to install `shortcode-core` plugin then wrap the table with a shortcode div and use the class `overflow-x-auto`.  This will require a recompile of the CSS per the Typhoon documentation: https://getgrav.org/premium/typhoon/docs#developing-custom-css

This will ensure the new class is added to the compiled CSS and you should then see your table with a horizontal scrollbar similar to this:

<img width="997" alt="CleanShot 2022-07-25 at 13 55 53@2x" src="https://user-images.githubusercontent.com/1084697/180863434-7995181c-79a5-4878-a3e2-96d96c60784a.png">

**Comment by danielrpfeiffer** [comment]
Hello,

Good to see it is possible. However, I'm still having trouble managing this.
I've followed the documentation as far as I understood it.


Here is what I tried.

- Shortcode-Core plugin is installed and active
- Wrapped the table in [div class="overflow-x-auto"] [/div]
- Ran "npm run build" in /user/themes/typhoon

What am I missing or doing wrong?


Sorry, I'm not a web developer. Just trying to compile a simple website.
I think overflow shall be the default. Who wants to cut off content?

**Comment by rhukster** [comment]
what was the output of your `npm run build` ? had you alrady done an `npm install`?

**Comment by danielrpfeiffer** [comment]
npm was installed already for another purpose.

The output is:

$ npm run build

> postcss8-tailwind@1.0.0 build
> NODE_ENV=production tailwindcss -i ./css/site.css -o ./build/css/site.css --postcss --minify


Done in 326ms.

**Comment by rhukster** [comment]
if you run `npm run watch` it will watch and detect changes.  If you make a change in your page where you have the table, does it show you it recompiled?

**Comment by danielrpfeiffer** [comment]
Shows me that:

Output:

$ npm run watch

postcss8-tailwind@1.0.0 watch
tailwindcss -i ./css/site.css -o ./build/css/site.css --postcss --watch --minify --verbose


Rebuilding...
Done in 888ms.

Rebuilding...
Done in 481ms.

Rebuilding...
Done in 413ms.

**Comment by rhukster** [comment]
Ok, so that shows that it's recompiling when you make the content changes, so the new `overflow-x-auto` should be being picked up and available.  Then it should just work.  Try hard-refreshing your browser to make sure the new CSS is loaded?

**Comment by danielrpfeiffer** [comment]
I changed the syntax

from 

[div class="overflow-x-auto"]

to

[div table class="overflow-x-auto"]
TABLE
[/div]

After recompiling it worked.

Should not make a difference from my shallow understanding. However, I'm happy that solved the problem.

Thank you for your support!

---

Summary:

To add a horizontal scroll to a large markdown table: 

Wrapping the markdown table in

`[div table class="overflow-x-auto"] TABLE [/div]`

then running
 
`$ npm run build" in /user/themes/typhoon`

npm must be installed of course...

**Comment by rhukster** [comment]
in your syntax `table` in `[div table...` will be ignored, i think it just triggered the recompile for you.

```
[div class="overflow-x-auto"] TABLE [/div]
```

is the correct syntax.
