### ISSUE TITLE
Custom Social Network in Footer

### ISSUE THREAD

**Issue by srameko** [getgrav/grav-premium-issues#3]
I would like to add other social network, which is not listed, to the footer. Is it possible?

**Comment by rhukster** [comment]
Are you talking about Typhoon theme specifically? What network are you looking for?

**Comment by srameko** [comment]
Yes, Typhoon Theme. I would like to have 500px, gitbook (some icon for document).

**Comment by rhukster** [comment]
Ok, i'll look at adding these two

**Comment by rhukster** [comment]
You know what @srameko, 500px is already available in latest version of "brands". 

```
[svg-icon icon="500px" set="brands"]
[svg-icon icon="gitbook" set="brands"]
```

Going to update SVG Icons with these

**Comment by rhukster** [comment]
1.0.2 has been released with Brand icons updates + Tabler.

**Comment by srameko** [comment]
@rhukster Would be possible to add these icons to Social Links part of the theme?

**Comment by rhukster** [comment]
Yes I will add them to typhoon blueprint.

**Comment by rhukster** [comment]
I've added this functionality as part of an upcoming 1.0.7 release.
