### ISSUE TITLE
NextGen: Linked page title on Page Inject blocks missing Grav site/folder name within URL?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-premium-issues#30]
I've noticed that clicking on the linked page title on Page Inject blocks (super handy!) gives a bad URL on both my local and production sites - the URL seems to be missing the Grav site folder name?

<img width="1440" alt="2021-01-26_10-23-05" src="https://user-images.githubusercontent.com/1812771/105888022-466ff000-5fc1-11eb-8246-1b5ccc343519.png">

<img width="1440" alt="2021-01-26_10-23-27" src="https://user-images.githubusercontent.com/1812771/105888028-48d24a00-5fc1-11eb-9ec7-aae21cdb7037.png">

Notice that the URL above does not include the Grav site folder.

Please let me know if any more info is helpful etc.
Paul

**Comment by w00fz** [comment]
This is fixed in https://github.com/getgrav/grav-plugin-page-inject/commit/21eaafdf7e196c0032b25c8466c02b5d0bd0fab4 - should be available at next release!

**Comment by paulhibbitts** [comment]
Awesome, thank you so much for fixing this @w00fz !

**Comment by paulhibbitts** [comment]
FYI, I've had a chance to now also test the Develop branch for this and it works great on my local setup too🙂
