### ISSUE TITLE
[typhoon] Incorrect rendering of highlighted inline code

### ISSUE THREAD

**Issue by danielrpfeiffer** [getgrav/grav-premium-issues#301]
Grav v1.7.35 - Admin v1.10.35 - Typhoon Theme 2.3.6

Hello!

Inline code highligting unsing backticks works correctly in the admin preview but not in rendered page using the Typhoon theme.
The rendered page shows the backticks where no backticks are expected.

Example:
MD Editor (Content)
![Code-high1](https://user-images.githubusercontent.com/77896852/183400710-58598b95-5f0e-4a44-8162-76f3483902c4.png)

---

<br>
<br>

Preview in Admin (correct no backticks visible)
![Code-high2](https://user-images.githubusercontent.com/77896852/183400766-05ec2e9c-eb4f-4605-88d8-63a7c624b212.png)

---

<br>
<br>
Render on Page (backticks rendered)

![Code-High3](https://user-images.githubusercontent.com/77896852/183400892-78726835-42d9-41ec-a6fb-9038196128fe.png)

**Comment by rhukster** [comment]
This is actually a feature and the default style of Tailwind Prose plugin (https://tailwindcss.com/docs/typography-plugin).  You can remove them with this code in the `tailwind.config.js` file (will require an `npm run watch` or `npm run build` to recompile the CSS though:

```js
module.exports = {
  theme: {
    extend: {
      typography: {
        DEFAULT: {
          css: {
            'code::before': {
              content: '""'
            },
            'code::after': {
              content: '""'
            }
          }
        }
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
```
