### ISSUE TITLE
[lightbox-gallery] Problem with gallery

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-premium-issues#302]
Tried to create gallery using [instruction](https://getgrav.org/premium/lightbox-gallery/docs#gallery-lightbox-with-shortcodes):
```md
[lightbox image="11.png" gallery="gemangioma"]
    ![](11.png?resize=400)
[/lightbox]
[lightbox image="12.png" gallery="gemangioma"]
    ![](12.png?resize=400)
[/lightbox]
```

Result (full image works fine):
![image](https://user-images.githubusercontent.com/7556290/183919689-d41264df-7b65-4cfb-b545-f86b93f99c5e.png)

DOM for 1st image:
```html

<a href="/user/pages/02.lekciya-5-pechen/01.vvedenie/11.png" class="glightbox " data-gallery="gemangioma" data-type="image">
    <pre>
        <code class="hljs less">
            !
            <span class="hljs-selector-attr">[]</span>
            (
            <span class="hljs-number">11</span>
            .png?resize=
            <span class="hljs-number">400</span>
            )
        </code>
    </pre>
</a>
```

**Comment by rhukster** [comment]
Try without indention as it looks like that indention is being treated like a code block:

```
[lightbox image="11.png" gallery="gemangioma"]
![](11.png?resize=400)
[/lightbox]
[lightbox image="12.png" gallery="gemangioma"]
![](12.png?resize=400)
[/lightbox]
```

**Comment by Sogl** [comment]
Thx, it works... but looks the same as before, no gallery view.

No built in gallery DOM/CSS support?
My images are scattered throughout the text, I can't declare them in the frontmatter.
