### ISSUE TITLE
[lightbox-gallery] Can't use with animated gif

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-premium-issues#305]
Animated gif line:
```
![](1.gif?lightbox)
```

Result on page:
![image](https://user-images.githubusercontent.com/7556290/184935882-0823be7c-88ef-40d8-be20-98be6235a564.png)

Full view works fine.

**Comment by rhukster** [comment]
An animated GIF is considered a file because it's not a traditional image that can be resized without breaking the animation.  Best option is to manually create a thumbnail and use that to link from.

**Comment by Sogl** [comment]
Standard Grav/twig `resize` works fine for animated gifs, so it's problem with lightbox or something...

**Comment by rhukster** [comment]
what does it do if you disable `lightbox-gallery` plugin completley? I think you'll find it renders exactly the same.  meaning it's Grav not able to output the thumb for gifs properly.

**Comment by Sogl** [comment]
> what does it do if you disable lightbox-gallery plugin completley? I think you'll find it renders exactly the same.

Yeah, the same. 😞 

>meaning it's Grav not able to output the thumb for gifs properly.

Why? It can resize, but can't create thumb?

**Comment by rhukster** [comment]
it's a weird case that gifs are not supported by lightbox.. it's been a long-standing issue with Grav media, nothing related to lgihtbox-gallery.   Closing here.
