### ISSUE TITLE
[typhoon] [bug] Fix two URLs for additional language

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-premium-issues#306]
Related issue: https://github.com/getgrav/grav-plugin-langswitcher/issues/65

I found what was the problem and found a solution. Just because login and langswitcher menus dynamically creates from `themes/typhoon/typhoon.php` in `onSiteThemeMenu($event)` function, we need to change these lines:
```php
155 | $base_lang_url = Utils::url($language->getLanguageUrlPrefix($lang));
156 | $lang_url = $base_lang_url . $langswitcher->page_route . $page->urlExtension();

```

on those:
```php
if ($langswitcher->translated_routes[$lang]) {
    $lang_url = $langswitcher->translated_routes[$lang] . $page->urlExtension();
} else {
    $base_lang_url = Utils::url($language->getLanguageUrlPrefix($lang));
    $lang_url = $base_lang_url . $langswitcher->page_route . $page->urlExtension();
}

```

according to new changes in langswitcher: https://github.com/getgrav/grav-plugin-langswitcher/blob/master/templates/partials/langswitcher.html.twig#L10

Need to somehow keep such parts of the code in sync with plugins changes 😄

**Comment by rhukster** [comment]
Makes total sense now, i forgot to update those are part of the langswitcher revamp.

**Comment by rhukster** [comment]
Fixed in next release.
