### ISSUE TITLE
[typhoon] TypeError Typhoon 2.4.0 with Grav 1.7.37

### ISSUE THREAD

**Issue by carstenfeller** [getgrav/grav-premium-issues#312]
Just to let you know, activating Typhoon 2.4.0 on Grav 1.7.37 throws this error:

Grav\Common\Page\Pages::getPagesCacheId(): Return value must be of type string, null returned

![05-10-2022_23-16-05](https://user-images.githubusercontent.com/6400691/194165334-47f6e04f-a65f-495f-976a-d52a6619f199.png)

**Comment by rhukster** [comment]
Thanks, I've just released Grav 1.7.37.1 with a fix to address this. Should show up in GPM in a few mins.

**Comment by rhukster** [comment]
BTW, temp fix is to turn system cache back on.
