### ISSUE TITLE
Recompiling CSS fails since upgrade to Grav 1.7.37.1

### ISSUE THREAD

**Issue by danielrpfeiffer** [getgrav/grav-premium-issues#313]
Hello,

Yesterday, I upgraded to the latest Grav v1.7.37.1

I wanted to recompile the CSS using npm, but now it fails.

I'm not sure if this has to do with the upgrade as this relates to the theme by my understanding. Just realized at that moment...

```
/user/themes/typhoon $ npm run watch

> postcss8-tailwind@1.0.0 watch
> tailwindcss -i ./css/site.css -o ./build/css/site.css --postcss --watch --minify --verbose

**sh: tailwindcss: not found**
```

"./css/site.css" and all files mentioned in the file do exist.

**Comment by rhukster** [comment]
the `npm run watch` command is 100% node, and nothing to do with Grav.  I suspect you just need to install the npm modules:

```
rm -Rf node_modules
npm install
```

**Comment by rhukster** [comment]
I just replicated that same error when i updated some NPM modules, and the solution above was the fix.

**Comment by danielrpfeiffer** [comment]
Ok, thanks for the hint.

**Comment by danielrpfeiffer** [comment]
In my case, I had to reinstall npm completely.
Now works again. All good now.

Thanks again for the hint about npm!
