### ISSUE TITLE
[instagram-feed] Error 401 when updating to v1.1.0

### ISSUE THREAD

**Issue by FabriceJoseph** [getgrav/grav-premium-issues#314]
Hi, 

When I click the Update Plugin button of the plugin admin panel, I receive an error 401 like this below : 

![image](https://user-images.githubusercontent.com/26174710/194728453-6338ec10-d235-4c9f-80d5-942ed8c4045c.png)

Is there an issue with the license ?

**Comment by rhukster** [comment]
It looks like it, can you confirm the license is installed?

**Comment by FabriceJoseph** [comment]
@rhukster  thanks for your response. 

Indeed, I don't see any license in the admin license-manager panel. I think so no license is currently installed (maybe accidentally erased ?!).
I am going to see with my friend (the website owner) to get back the license he had bough (hope he still has it).

**Comment by w00fz** [comment]
Know you can also retrieve a license any time from our recovery link: https://getgrav.org/premium/recover

**Comment by FabriceJoseph** [comment]
Thank you both. 
I retrieved the license and then installed the update like a charm. 
I close the issue.

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
