### ISSUE TITLE
[nextgen-editor] Underline text functionality does not work

### ISSUE THREAD

**Issue by WhiteboxSoftwareLtd** [getgrav/grav-premium-issues#315]
I would like to report an issue with the Underline text functionality.

Whenever I underline text in the editor using the Underline text icon, the text becomes underlined, however after saving the page the text reverts back to being not underlined, and the text is not underlined on the frontend either.

Before save:

<img width="552" alt="before-save" src="https://user-images.githubusercontent.com/101148085/194831256-2743f095-13a7-45dc-b14a-4242a402dbd0.png">

After save:

<img width="552" alt="after-save" src="https://user-images.githubusercontent.com/101148085/194831287-0c0a7465-6841-4426-b143-5c318f84c3c0.png">

As rendered on the frontend:

<img width="195" alt="as-rendered-on-site" src="https://user-images.githubusercontent.com/101148085/194831321-6320a3b4-48f7-45c5-904a-c8a003acbac1.png">

Used versions:

- PHP: 8.1.10
- Grav CMS: 1.7.37.1
- Admin Panel: 1.10.37.1
- NextGen Editor: 1.1.12

**Comment by w00fz** [comment]
Markdown does not support `underline` and probably that toolbar entry shouldn't be there. I recommend you install shortcode-core instead and use the built-in Underline Text option:

![CleanShot 2023-05-09 at 21 19 44@2x](https://github.com/getgrav/grav-premium-issues/assets/11734/3210d89a-954c-4269-9fea-9984ab8f3a22)
