### ISSUE TITLE
[typhoon] Mobile menu open state by default

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-premium-issues#318]
What I see if I click on hamburger on mobile devices:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/7556290/199037902-ab66edc5-1836-495e-9e88-d2bb266919a8.png">

What I want by default:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/7556290/199038144-15e70a6b-9731-4ce5-af27-5489f7f4f52d.png">

**Comment by w00fz** [comment]
You can achieve this by overriding the mobile menu twig Template `templates/partials/mobile-navigation.html.twig` and replace the constant `MENU_STATE` to `true`.


Around line 20:
```twig
parent: 'x-data="{ selected: MENU_STATE }"',
```

**Comment by Sogl** [comment]
Thanks, it works.

**Comment by Sogl** [comment]
@w00fz Can this be done with an option in the Admin panel?

**Comment by rhukster** [comment]
No needs to be done in the template twig that djamil referred to.
