### ISSUE TITLE
[lightbox-gallery] Title and description on hover?

### ISSUE THREAD

**Issue by key-notes** [getgrav/grav-premium-issues#320]
Would it be possible to add an option for the title and description of a video to appear when hovering over its thumbnail? This could make quite a big difference in usability for some use cases. Many thanks in advance.

**Comment by rhukster** [comment]
while it is possible, it's really not a feature of lightbox-gallery, which is purely a way to link something (image, hyperlink, button, etc), to a modal gallery popup.  What happens before you click that element and get to the lightbox-gallery itself is beyond the scope of this plugin.

It sounds like you just want some form of tooltip? There are lots of JS libraries out there, and even some solid CSS approaches to achieve this.  A quick google resulted in: https://blog.hubspot.com/website/html-tooltip
