### ISSUE TITLE
[typhoon] reCAPTCHA on Contact Form

### ISSUE THREAD

**Issue by HelterSkelter5** [getgrav/grav-premium-issues#322]
Hi,

How do you add reCAPTCHA to one of the template's contact forms?  Adding the following code doesn't appear to work:

`    recaptcha:
        version: 2-invisible
        theme: dark
        site_key: 6Lc7...
        secret_key: 6Lc7...`

and

`process:
        captcha: true`

No sign of any captcha presence at all and nothing logged in reCAPTCHA stats.

TIA

HS

**Comment by HelterSkelter5** [comment]
Just to add to this, I know the settings are supposed to be invisible but there should be some evidence that reCAPTCHA is there?  Anything dodgy entered into the form just produces a red notice but the form still sends so the reCAPTCHA doesn't appear to be having any effect on the form action.

**Comment by rhukster** [comment]
Problems with recaptcha would be outside of the theme itself, it's usually a form plugin configuration thing.  

Does basic captcha work for you? Also in latest Form, we have implemented Turnstile captcha which in our testing is more transparent and more reliable than Google.  Regarding Google reCaptcha, you should use Version 3.

**Comment by HelterSkelter5** [comment]
Documentation at https://learn.getgrav.org/16/forms/forms/fields-available is inconsistent and results in a Captcha failed error.  Yes, it is set up at Cloudflare end.

**Comment by w00fz** [comment]
what kind of error ?

**Comment by HelterSkelter5** [comment]
It looks like it was a latency issue with Cloudflare. I'd updated forms.yaml with the parameters but nothing was displaying at the foot of the form.

It is a much more elegant solution than reCAPTCHA.

Is there any way to increase the size of the box to match the form field width?  Aside from that niggle, Turnstile is a bit of a dream!
