### ISSUE TITLE
[typhoon] Modular Page containing Blog + Gallery

### ISSUE THREAD

**Issue by mfuggle** [getgrav/grav-premium-issues#323]
Hi Folks,
I am a Grav Newbie but spending a lot of time learning. I am using the Typhoon Blog skeleton and want to be able to display a Gallery immediately below the Blog. I think I need to create a Modular page and include type Blog and Type Gallery. However when I create a Modular Page I am not able to see type Blog to add to the page.
I am probably failing to explain myself well but that's because I haven't yet managed fully understand Grav as well as the Typhoon theme.
I just need to be pointed in the right direction because I am floundering right now.
Regards
Martin Fuggle

P.S. I have also posted this on the Typhoon github. Where should  I post Grav Typhoon issues/questions?

**Comment by mfuggle** [comment]
Anyone going to respond?

**Comment by rhukster** [comment]
I will respond after the thanksgiving holidays.

**Comment by mfuggle** [comment]
Many thanks...
I want to display a gallery at the bottom of a blog post. My folder structure is:
Pages Folder

![Pages Folder](https://user-images.githubusercontent.com/1777429/204068244-e51c753b-4263-4b8d-9603-3f8e15612c4a.png)

and my gallery.md, post.md and blog.md are shown below:

![gallery md](https://user-images.githubusercontent.com/1777429/204068259-842abff3-aa18-498a-a026-8f05d84d16e6.png)
![post md](https://user-images.githubusercontent.com/1777429/204068260-5efbff1c-bb5d-4697-a374-f0e75471174e.png)
![blog md](https://user-images.githubusercontent.com/1777429/204068261-fe60b334-c73c-4ed1-93a3-a49dfedfa145.png)

I have removed as much as possible from the .md files to simplify things. My issue is that the Blog displays with its child posts but the child post does not display the gallery. I have tried to track this down but have failed. If someone could point me in the right direction I would be most grateful.
Cheers
Martin Fuggle

**Comment by mfuggle** [comment]
Has Thanksgiving finished yet? It would be really helpful to get some assistance after 7 days.

**Comment by rhukster** [comment]
yes, it's finished :)

the problem is that the post page doesn't know it should do anything with the gallery modular sub-page. 

I see you have attempted to create a collection in `post.md` but the syntax is incorrect, it should be:

`post.md`:
```yaml
content:
  items: self@.modular
```

Then the `post.html.twig` template needs to be modified to display any pages from the modular collection below the post:

`post.html.twig`:
```twig
...
{% block items %}
    ...

    {% for module in page.collection() %}
    {{ module.content|raw }}
    {% endfor %}
{% endblock %}

{% block sidebar %}
    {% include 'partials/sidebar.html.twig' %}
{% endblock %}
...
```

That should do it.

**Comment by mfuggle** [comment]
Great - I just needed to put the lightbox.html.twig in the theme folder and
everything worked as planned.

Many thanks
Martin Fuggle
0408 265 586
***@***.***

**Comment by rhukster** [comment]
👍🏻
