### ISSUE TITLE
[typhoon] site.css - "Unknown at rule @tailwind Ln 11 Col 1

### ISSUE THREAD

**Issue by mfuggle** [getgrav/grav-premium-issues#324]
When I open sites.css using Visual Studio Code I see the following problems reported. Is this expected? 
![image](https://user-images.githubusercontent.com/1777429/205517632-271a5d75-dbb4-44d3-a72d-281791e93ee0.png)
Cheers
Martin Fuggle

**Comment by w00fz** [comment]
The output css served on the frontend is actually in the `css-compiled` folder, you are looking at the `css` folder which is the source code. We use tailwind and postcss which actually allows the syntax highlighted in the error you highlighted. 

If your VSC doesn’t know how to handle postcss, it will error out like that. 
Try installing a plugin for postcss/tailwind and the error should go away.
