### ISSUE TITLE
[nextgen-editor] Enhancement. Using in frontend forms.

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-premium-issues#327]
Any idea how to use this plugin in frontend forms? I want to add/edit rich markdown texts from frontend (Flex objects).

**Comment by w00fz** [comment]
Unfortunately this is really not possible as NextGen is not implemented to work with frontend at all.

**Comment by Sogl** [comment]
No plans to add support in the future?

**Comment by w00fz** [comment]
NextGen is very tied to Admin hooks so porting to frontend is not trivial. I wouldn't dismiss this entirely but I have to be honest and don't want to give you false hopes and so to answer your question no, not in the foreseeable future unfortunately, sorry.
