### ISSUE TITLE
[instagram-feed] Feed Sorts by filename and not by date

### ISSUE THREAD

**Issue by bjoernbohr** [getgrav/grav-premium-issues#329]
Hello,
like the Title states i got the Feed up and running but it's currently sorted by file name. I am aware that it should be possible to do this via a Twig sorting function, but it would certainly make more sense if this would be done directly by the plugin. 

Have I done something wrong with the integration, are there perhaps already some Paramater for it or must the sorting be done via twig?

**Comment by derhamproductions** [comment]
I was having the same issue, but I've just used a slightly different code to the documentation and it's sorted correctly.

`{% for image in instagram.getInstagramMedia(0,false).all|slice(0, 12) %}`
