### ISSUE TITLE
[typhoon] H1 not shown in safari 13.1

### ISSUE THREAD

**Issue by gfvh** [getgrav/grav-premium-issues#330]
HI

Using mac osx high sierra. Issue is that H1 is shown as regular font. Using typhoon latest theme. I cannot test higher mac os x but on sierra should work also :)

Website where issue can be seen: https://surl.guru/Fza28n7

**Comment by rhukster** [comment]
First sorry for taking so long to get back to you.  I've been super busy!  

OK, first, what do you mean by regular font? size, font-family? etc.

Which part of the page linked to via the URL is not as expected? Please provide some specifics preferrably in some annotated screenshots or at least a description, so I know where to look.

Thanks!
