### ISSUE TITLE
[nextgen-editor] feature-request: Fixed header toolbar.

### ISSUE THREAD

**Issue by duronflo** [getgrav/grav-premium-issues#332]
Hello guys,

it would be nice to have the feature that the toolbar is fixed to header for editing long text or artictles.

Is something like that planned for upcoming releases?

Regards,
Florian

**Comment by duronflo** [comment]
push...

**Comment by w00fz** [comment]
This is already the case but only fixes the toolbar when the editor is in focus (your cursor is actually editing the editor).
