### ISSUE TITLE
[typhoon] Notice for specific page

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-premium-issues#335]
According to documentation I can put notice only for main or on every page:
https://getgrav.org/premium/typhoon/docs#notices

But how put it for specific page?

**Comment by rhukster** [comment]
I've added support for this for the next version. Summary of important changes:

in `typhoon.yaml`:

<img width="976" alt="CleanShot 2023-02-03 at 15 27 20@2x" src="https://user-images.githubusercontent.com/1084697/216722993-2aa24457-0905-4e53-85e0-56a6cd5430f2.png">

You can see that `only_homepage` has been replaced by a `route`, then in `partials/notices.html.twig`:

<img width="1008" alt="CleanShot 2023-02-03 at 15 29 11@2x" src="https://user-images.githubusercontent.com/1084697/216723213-f084b7da-1b9f-4df6-bebe-f09471c4ddbc.png">

The only check has been made more dynamic by check that still has support for the old `only_homepage` for backwards compatibility.
