### ISSUE TITLE
[typhoon] Primary Menu Not Displaying Correctly

### ISSUE THREAD

**Issue by Umbyology** [getgrav/grav-premium-issues#34]
**FYI** ... First-off, I'm running a child-typhoon theme for inheritance reasons so I can make adjustments and they won't be overwritten when I update the theme. To set up the child-theme I followed the instructions under GetGrav > Learn ... everything seems to be working fine, but I wanted to add this in case it might make a difference in diagnosing the issue. I haven't made any adjustments to the child-theme thus far.

**The Issue:** Under the Typhoon theme, when I set the Primary Header Levels at 2 the menu goes crazy, see attachments. The mobile version displays fine, but the dropdown positions are off on the desktop, and they are all stuck in the "open" position.

It wasn't displaying like this before the last update to Typhoon 1.0.8., at least not that I know. However, at about the same time this issue seems to have shown itself when I reorganized the pages to better utilize the secondary side-menu. That's when I first noticed the issue; prior to that, I had the levels set to 1.

I've tried clearing the cache, resaving various pages, etc. but no change.

<img width="1371" alt="Screen Shot 2021-01-31 at 1 33 45 PM" src="https://user-images.githubusercontent.com/22547499/106395655-0fd31480-63c9-11eb-8a4b-5d426fc0d7a9.png">

<img width="840" alt="Screen Shot 2021-01-31 at 1 23 57 PM" src="https://user-images.githubusercontent.com/22547499/106395662-195c7c80-63c9-11eb-8d79-813dc78be011.png">

**Comment by rhukster** [comment]
That's a CSS issue, if you have a custom theme that overrides Typhoon, you still need to recompile the CSS (probably dev and prod).

https://getgrav.org/premium/typhoon/docs#developing-custom-css

**Comment by rhukster** [comment]
If that doesn't help, make sure you have updated any other files you might have overridden in the child theme.

https://github.com/trilbymedia/grav-theme-typhoon/compare/1.0.7...1.0.8

**Comment by rhukster** [comment]
might be that I added `header-nav` class in `partials/header.html.twig` that you didn't port over, or that I made use of this new class in the `css/custom/navigation.css` file.  These are the two most likely culprits.

**Comment by Umbyology** [comment]
I'll take a peek and let you know. THX!

**Comment by Umbyology** [comment]
For Inheritance purposes, the only two files I've changed are the Partial "sidebar.html.twig" file, where I simply added some text to the sidebar on the Blog page. And I've created a new Favicon. That's it. No other files have been added or changed to the Child-Theme.

So, I guess I'm a little confused. My question is ... I haven't made any changes to any CSS at all, shouldn't the child-theme be using the unaltered base-theme CSS files from Typhoon?

**Comment by rhukster** [comment]
If that's all you have changed, you will still need to copy over the contents of the `typhoon.yaml` and place this under the `streams:` section of your new theme's .yaml file.

**Comment by Umbyology** [comment]
Ya, I've done everything in the directions under GetGrav > Learn for Inheritance, including what you mentioned. The issue still exists, yet it shouldn't. I've changed nothing else. I've even reinstalled the Typhoon to a previous version, then updated it again just to be sure it wasn't a corrupted file; but no change.

I'm pretty busy over the next few days, I'll take another crack at it towards the end of the week and let you know if I find something. THX!

**Comment by rhukster** [comment]
Strange, i used devtools to create a new theme and used the inheritance option with Typhoon as the base theme.  I switched to the new theme, and it works fine, dropdowns included.  It's using the parent `typhoon` CSS.

**Comment by Umbyology** [comment]
Ya, the only thing I can think of is that a file has gotten corrupted somehow, somewhere, but I have reinstalled the theme already. I haven't tried reinstalling the plugins though. Thx for the look-see.

**Comment by rhukster** [comment]
I actually recommend doing a 'copy' when you are ready.  It will take the current state of typhoon, and then you can manipulate things as much as you like.  YOu can always manually merge changes over if there's something added you really want in the new theme.  Just safer and less complicated this way in general.

**Comment by Umbyology** [comment]
Yep. I thought of that. As long as I only have a few things I've changed that will work fine. I just need to remember to restore the files I've changed after each theme update. LOL

**Comment by Umbyology** [comment]
So, I reinstalled GRAV from scratch; fresh install v1.7.4, only saving my User directory. I then restored my user directory and re-activated my Premium products. Took all of 15 minutes ... lol!

This issue is solved. Most likely a corrupt file somewhere.

THX Andy!
