### ISSUE TITLE
[algolia-pro] HTTP ERROR 500 after plugin install 

### ISSUE THREAD

**Issue by Mass-rj05** [getgrav/grav-premium-issues#344]
Hello,

I just boughta Algolia pro plugin.

I upgraded Grav to 1.7.38
Then I upgraded plugins and themes 
Then I installed license-manager
Then I added my key to plugin in the admin panel
Then I installed algolia-pro
Instalation output:
```
_Preparing to install Algolia Pro [v1.0.8]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!
Clearing cache
Cleared:  D:/Tpay/homepage/cache/twig/*
Cleared:  D:/Tpay/homepage/cache/doctrine/*
Cleared:  D:/Tpay/homepage/cache/compiled/*
Cleared:  D:/Tpay/homepage/images/*_
```

And when I run project as always using "php -S localhost:8000 system/router.php"
I have HTTP ERROR 500 and I can't run the project.

I am using `PHP 7.4.19 (cli) (built: May  4 2021 14:24:38) ( ZTS Visual C++ 2017 x64 )`

I checked logs and this is what I found:
```
[2023-02-20 10:20:02] grav.WARNING: Plugin 'flex-objects' enabled but not found! Try clearing cache with `bin/grav clearcache` [] []
[2023-02-20 10:20:02] grav.CRITICAL: Class 'Grav\Plugin\AlgoliaPro\AlgoliaProFactory' not found - Trace: #0 
```

My first idea is to install flex-object plugin but it is just a warning 
I don't know how to handle tis Critical log about AlgoliaProFactor.

I am quite new in Grav so maybe I am missing something.

Please help me with this topic.

Best regards,
Krzysztof

**Comment by rhukster** [comment]
You should install flex-objects plugin. That should be a CRITICAL message.

**Comment by Mass-rj05** [comment]
I installed flex-objects plugin and the log about this disapeared,  but still have the critial about AlgoliaProFactory

`
 The package flex-objects is already installed, overwrite? [y|N]  (yes/no) [no]:
 > yes

Preparing to install Flex Objects [v1.3.4]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!


Fatal error: Uncaught Error: Class 'Grav\Plugin\AlgoliaPro\AlgoliaProFactory' not found in D:\x\homepage\user\plugins\algolia-pro\algolia-pro.php:325
Stack trace:
#0 D:\x\homepage\vendor\symfony\event-dispatcher\EventDispatcher.php(264): Grav\Plugin\AlgoliaProPlugin->onPluginsInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPluginsInitia...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#1 D:\x\homepage\vendor\symfony\event-dispatcher\EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPluginsInitia...', Object(RocketTheme\Toolbox\Event\Event))
#2 D:\x\homepage\vendor\symfony\event-dispatcher\EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'onPluginsInitia...', Object(RocketTheme\Toolbox\Event\Event))
#3 D:\x\homepage\system\src\Grav\Common\Grav.php(597): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(RocketTheme\Toolbox\Event\Event), 'onPluginsInitia...')
#4 D:\x\homepa in D:\x\homepage\user\plugins\algolia-pro\algolia-pro.php on line 325
PS D:\x\homepage> php -S localhost:8000 system/router.php
`

How can I handle this ?

**Comment by Mass-rj05** [comment]
The root cause was in the project and was not related to the plugin. 
Closing
