### ISSUE TITLE
[seo-magic] Webshot unauthorized (registration sync problem?)

### ISSUE THREAD

**Issue by thomastweets** [getgrav/grav-premium-issues#348]
We are running into a "Webshot Unauthorized" problem, similar to https://github.com/getgrav/grav-premium-issues/issues/297.

We have registered our current review app URL in the SEO-Magic plugin configuration successfully (I even checked the network response to the `POST` to https://getgrav.org/premium/features):
`{"registered":true,"site":"https:\/\/www.review-412-replace-seo-grav.dev.lingoking.com"}`

However, even when manually requesting the webshot image at e.g. https://www.review-412-replace-seo-grav.dev.lingoking.com/de/allgemeines/agb/seomagic-image or the direct request to the base64 encoded URL at your servers at https://webshot.getgrav.org/?url=aHR0cHM6Ly93d3cucmV2aWV3LTQxMi1yZXBsYWNlLXNlby1ncmF2LmRldi5saW5nb2tpbmcuY29tL2RlL2FsbGdlbWVpbmVzL2FnYg== we get the typical "Unauthorized" image. I also cleared the local `cache/seo-magic/images` folder multiple times.

Could the registration sync to the webshot server be broken once more as in https://github.com/getgrav/grav-premium-issues/issues/136? Or maybe there is a caching issue with cloudflare that you are using? Although it also does not work with never-seen-before URLs.

Thanks a lot for (a great project! and) your help!

**Comment by rhukster** [comment]
I don't see the `www.review-412-replace-seo-grav.dev.lingoking.com` entry in the authorized hosts at all.  Can you show a screenshot of it showing registered? Is it possible it's another URL?

**Comment by rhukster** [comment]
IF you PM me on Discord, or send an email to premium@getgrav.org with your licence number for SEO Magic, I can try looking it up that way.  Cheers.

**Comment by thomastweets** [comment]
Thanks for your reply! I have sent you the license number via mail.

The URL we used for testing the plugin was https://www.review-412-replace-seo-grav.dev.lingoking.com and it successfully registered with a response from your server. I did not take a screenshot of the successful registration but even in other internal testing environments (with different URLs) that used the same license key the same URL showed up and the response from your API was successful as well.

By now we had to tear down the review app again and I re-registered the webshot feature to our production website at https://www.lingoking.com (also with a successful response) and now the webshot feature started to work. There was not difference in my usage of the registration and the environments are setup in almost identical ways. Maybe this is still worth investigating?

Thanks!

**Comment by rhukster** [comment]
Based on what you have told me about it working for www.kingoking.com, I think this is probably related to your sublevel in the domain.. ie `x.y.z.com`, where it does work with `x.y.com`. I will investigate this further, but glad you got it working.  

BTW, i found your entry based on your license in the authorized lists, and it correctly says `www.lingoking.com` is authorized, so probably after you updated your registration.

**Comment by thomastweets** [comment]
Thanks for your help here @rhukster  👍
