### ISSUE TITLE
[Lightbox Gallery] Slider options

### ISSUE THREAD

**Issue by and-42** [getgrav/grav-premium-issues#35]
Is it possible to use or enhance the images in a slider fashion? Im looking for a solution to show the gallery as a slider and open the lightbox, if an image is clicked.

**Comment by rhukster** [comment]
Lightbox Gallery is ONLY a lightbox. However it can be used in conjunction with a Slider such as Swiper.js which is one we typically use when we need a slider: https://swiperjs.com/

**Comment by and-42** [comment]
Are there any examples or hints how to integrate?

**Comment by rhukster** [comment]
It's really easy. To get started you can use the CDN approach and follow this guide: https://swiperjs.com/get-started

**Comment by rhukster** [comment]
Plenty of demos too. https://swiperjs.com/demos to show off the various configuration options.

**Comment by and-42** [comment]
👍
