### ISSUE TITLE
[site-toolbox] warm-cache plugin incompatible with gzipped sitemap

### ISSUE THREAD

**Issue by thomastweets** [getgrav/grav-premium-issues#351]
We host our website with Caddy using a `encode zstd gzip` directive (https://caddyserver.com/docs/caddyfile/directives/encode) to ensure efficient content delivery. This does affect the `content-type` for our sitemap.json which becomes `application/json; charset=utf-8` instead of `application/json` as expected by the check in line 182 of `user/plugins/warm-cache/warm-cache.php`:

`$sitemap_response->getHeaders()['content-type'][0] == 'application/json')`

This results in the warm-cache plugin throwing an error. When removing the check above the warm-cache command works fine. We can fix this locally, however, an upstream change would be nice.

Thanks!

**Comment by rhukster** [comment]
no problem, i can fix that.  cheers.

**Comment by rhukster** [comment]
released 2.0.3 wiith a fix

**Comment by thomastweets** [comment]
Thanks a lot @rhukster, that was FAST! I can confirm that it is working for us. 👍
