### ISSUE TITLE
[instagram-feed] Undefined property: stdClass::$access_token

### ISSUE THREAD

**Issue by SjoerdSmeets** [getgrav/grav-premium-issues#355]
Trying to setup a new test website with instagram-feed. Everything done as explained in the docs. After granting access for oAuth via admin of grav, there's a crikey with Undefined property: stdClass::$access_token

Can't get a valid token. 

Grav and all plugins are up to date.

**Comment by rhukster** [comment]
Hmm.. I can't replicate this. When exactly are you seeing this token? 

Also are you sure you have setup the "Facebook" side and the "Instagram" side exactly as outline in the docs. I remember having trouble before realizing that I was using the Facebook token, rather than the Instagram one.

**Comment by SjoerdSmeets** [comment]
Checked app keys are instagram keys. I saw an option to generate a token from within the app settings. After this the link from the plugin admin worked.
