### ISSUE TITLE
[seo-magic] Meta image attribute is "seomagic-image"

### ISSUE THREAD

**Issue by matt-j-m** [getgrav/grav-premium-issues#360]
Hi there, running SEO Magic on latest Grav v1.7.40 - Admin v1.10.40.

No matter what selection I make for "Image Type" under "Meta Images" I end up with a value of "seomagic-image".

For example, if I set it to "The first image found in the current page's folder" then view my homepage in my local environment (which has many images in the page) the meta value comes out as ```<meta name="image" content="http://localhost/seomagic-image" />```

I get the same output when I use the setting "Automatically pick a local image" or "Default URL of a specific image" with a "Default Image" value of "https://via.placeholder.com/1200x630/cccccc/969696"

Am I doing something wrong?

**Comment by rhukster** [comment]
Sorry back from vaction, i'll take a look at this as soon as possible.

**Comment by matt-j-m** [comment]
This is helpful, thank you. After further testing I realised it's working for every page except the homepage, on localhost. Once I deploy to the live server, it works on all pages, including the homepage.

In my local environment when I hit http://localhost/seomagic-image I get the following error:

Call to a member function media() on null

pointing to line 234 of user\plugins\seo-magic\classes\SEOMagic.php:
``` $media = $page->media();```
