### ISSUE TITLE
[nextgen-editor] NextGen-Editor has vanished from the GetGrav.org website and all of it's documentation

### ISSUE THREAD

**Issue by sresicn** [getgrav/grav-premium-issues#361]
The nextgen-editor has vanished from the Grav website and shows a 404 error (See: https://getgrav.org/premium/nextgen-editor)

**Comment by w00fz** [comment]
We are in talks with CKSource to refresh our license to use CK5. We have temporarily disabled NextGen and NextGen purchases, until we are done with the paperwork.

Sorry about the inconvenience. It will be back soon!

**Comment by codingnooob** [comment]
Any updates on this?

**Comment by manemanemane** [comment]
Hi,
Do you have any updates on this plugin? Is it available for purchase?
Thank you in advance :)

**Comment by rkkoszewski** [comment]
> We are in talks with CKSource to refresh our license to use CK5. We have temporarily disabled NextGen and NextGen purchases, until we are done with the paperwork.
> 
> Sorry about the inconvenience. It will be back soon!

Those are certainly some pretty long talks.. Thanks for the update!!
