### ISSUE TITLE
[seo magic] plugin not able to display or save data

### ISSUE THREAD

**Issue by mariekreativ** [getgrav/grav-premium-issues#364]
By "error", I clicked on the "seo-plugin" tab before saving the blog post draft for the first time. This error message was displayed. After saving the blog post, the message continues. I have no other issues with this plugin, i.e. all other pages working fine.

<img width="1550" alt="Bildschirmfoto 2023-05-31 um 10 47 34" src="https://github.com/getgrav/grav-premium-issues/assets/10570878/f61f894d-6ad3-4e44-8181-adc65a3a9998">

I'm updated to the latest version of plugins, excepting "flex objects", somehow the update is not working. Reinstalling also didn't work.

I'm not a developer but a keen learner. Thanks for taking a look.

**Comment by mariekreativ** [comment]
After the last plugin update, the issue continues.

**Comment by rhukster** [comment]
I'll try and recreate your issue but i've never seen it before!

**Comment by mariekreativ** [comment]
Thank you 👍🏻 I also found that I cannot update existing pages' SEO MAGIC properties. 

<img width="1500" alt="Bildschirmfoto 2023-06-06 um 11 09 56" src="https://github.com/getgrav/grav-premium-issues/assets/10570878/affabe70-23ea-41e9-99b1-14c90a166d1c">

This menu seems new, too, probably from the update. But I cannot select a specific image anymore. (This is another issue probably.)

**Comment by rhukster** [comment]
i was able to replicate the primary issue: not being able to save content and update the SEO Magic data. It was not specific to new pages actually, it was all page saves were not functioning correctly.

The second issue you mentioned with image settings not working on the page, this works 100% fine for me:


https://github.com/getgrav/grav-premium-issues/assets/1084697/3d7a7502-d8ca-4381-ba34-a606534742fe

**Comment by mariekreativ** [comment]
Thank you for fixing this issue. The second issue I cannot replicate, due to the fact that I cannot save the page. I guess it will be fixed with the next update then?

**Comment by rhukster** [comment]
I will release SEO Magic, but there is no fix for the page not saving. I'm not sure what that is as I cannot duplicate it.  I think you have some other issue going on there that could be related to content validation failing, or another plugin causing an issue.
