### ISSUE TITLE
[lightbox-gallery] Thumbnails Are Not Correct

### ISSUE THREAD

**Issue by Umbyology** [getgrav/grav-premium-issues#37]
Hiya,

I just installed my first gallery using Premium Lightbox Gallery. Seems to function ok, except the thumbnails are not sizing correctly; in-fact they are not sizing at all to the options I set. No matter what I set the Thumbnail HxW they display the same on the frontpage. Plus, they all seem to be "cut-off" in the exact same manner as they appear in the media section of the page settings ... see attachments for all this.

See how they are cut-off here ...
<img width="1568" alt="Screen Shot 2021-02-03 at 3 32 23 AM" src="https://user-images.githubusercontent.com/22547499/106728415-08cb2280-65d2-11eb-994a-f42445e3a376.png">

The same cut-off here ...
<img width="1752" alt="Screen Shot 2021-02-03 at 3 32 45 AM" src="https://user-images.githubusercontent.com/22547499/106728524-28624b00-65d2-11eb-8e25-ee9624fbca24.png">

Despite the square setting here ...
<img width="1613" alt="Screen Shot 2021-02-03 at 3 33 14 AM" src="https://user-images.githubusercontent.com/22547499/106728593-3b751b00-65d2-11eb-9d43-0adb426b3ffc.png">

Despite the appearance of each logo, they are all perfectly square PNG images. On the frontpage, when I click on the images they all have the zoom effect and appear normal as they should.

Suggestions?

**Comment by rhukster** [comment]
It does appear like the resize is not happening.. let me investigate..

**Comment by rhukster** [comment]
Ok, i found the problem, check this commit out and you can make the simple changes in the blueprint until the next release: https://github.com/trilbymedia/grav-theme-typhoon/commit/a9702816bb1a900d0a61d05aadecefac867ddbd5

**Comment by Umbyology** [comment]
> Ok, i found the problem, check this commit out and you can make the simple changes in the blueprint until the next release: [trilbymedia/grav-theme-typhoon@a970281](https://github.com/trilbymedia/grav-theme-typhoon/commit/a9702816bb1a900d0a61d05aadecefac867ddbd5)

I above link/path to commit might be bad.

**Comment by Umbyology** [comment]
I'll wait until the fix, I've adjusted the logo sizing by hand to compensate for now. THX!

**Comment by Umbyology** [comment]
I'll close this issue since you have a fix coming-out. THX!
