### ISSUE TITLE
[typhoon] Summary of the issue

### ISSUE THREAD

**Issue by Staubgeborener** [getgrav/grav-premium-issues#373]
I am thinking about buying the premium typhoon theme. There is this „license key for 1 site“ note. Currently I am developing my website on a domain dev.domainA.com, later in like 2 weeks I want to use this (only) on my productive domain which is domainB.com. Is this possible or is the key „burned“ with the other domain? What is the correct way to use this theme a couple of weeks on a domain and after that on a completely different domain?

**Comment by rhukster** [comment]
It’s fine. We did try to explain this in the faq, but you can use a single license in development and even a staging type server for the same site/project. You don’t register a
Domain or anything. We’re trusting you not to abuse it.
