### ISSUE TITLE
[site-toolbox] Custom Icons removed when plugin updates

### ISSUE THREAD

**Issue by essboyer** [getgrav/grav-premium-issues#374]
Hi!

Just a question pertaining to the `SVG-Icons` plugin.

Where is the recommended location to place custom icons so that they are not destroyed by an update of the plugin?

**Comment by rhukster** [comment]
You bring up a valid point, there's currenly only the single location that is used for the icon locations.  I'm going to mark this for improvement so that you can put your custom icons in an alternative location and try that first if set.

**Comment by essboyer** [comment]
Ah, that's fantastic! Thank you so much for looking into it and taking the time to implement.

**Comment by aleclerc7** [comment]
A bit late to the party, but thank you for this new feature! It will help greatly!
