### ISSUE TITLE
[site-toolbox] Correct syntax for heroicons

### ISSUE THREAD

**Issue by Staubgeborener** [getgrav/grav-premium-issues#377]
I can use `tabler` icons easily, for example, like this `tabler/home-2.svg` (`modular/features` template in typhoon). But what is the correct syntax for [heroicons](https://heroicons.dev/)? According to the [documentation](https://getgrav.org/premium/site-toolbox/docs#shortcode-for-content) it should be something like this `heroicons\outline/Home.svg` or `heroicons/outline/Home.svg`, but both are not working

**Comment by Staubgeborener** [comment]
Quite annoying, that premium user are **forced** to use the GitHub repository in order to get help, although the feedback here is far less than in the official grav forum.

**Comment by rhukster** [comment]
Sorry, must of missed this..

There's a heroicon example here:

https://getgrav.org/premium/site-toolbox/docs#twig-function-for-templates

```
{{ svg_icon('heroicons/outline/star.svg', 'current-color h-8 w-8')|raw }}
```

I think the issue is your uppercase of `Home.svg`, the files are actually all lower case.
