### ISSUE TITLE
Issue with Double Text Module

### ISSUE THREAD

**Issue by Umbyology** [getgrav/grav-premium-issues#38]
Sorry, not sure if this is a Premium Typhoon module issue, or a new Grav 1.7 module issue.

When I create a Double Text module it splits the frontpage horizontally with a footer in the middle (see below). Also on the backend, there are different/separate editors types for each right & left columns.

![Screen Shot 2021-02-03 at 11 03 36 AM](https://user-images.githubusercontent.com/22547499/106783620-18b62700-6611-11eb-8c4b-927559dfa0a3.png)

![Screen Shot 2021-02-03 at 11 13 34 AM](https://user-images.githubusercontent.com/22547499/106783761-41d6b780-6611-11eb-8ca4-3785f2b1f9f0.png)

**Comment by rhukster** [comment]
It does sound like a theme and specifically a template related issue.  Typhoon doesn't come with a `modular/double_text.html.twig` template, so I'm guessing you created it.  It's possible that when you did create it, you used:

```
{% extends 'partials/base.html.twig' %}
```

which is intended for full page types, not modular page types. If you look in the modular template examples (such as `text-columns.html.twig` you will see:

```
{% extends 'modular/partials/base.html.twig' %}
```

This is what any modular should extend in Typhoon.

**Comment by Umbyology** [comment]
I didn't create it ... In fact, I haven't used Modular pages since GRAV early beta. I've never needed them. I keep my websites pretty basic.  I'm a power user ... lol ... you present me with a feature I'll use it, but I don't mess with Dev stuff that much at all. I usually live within the confines of the CMS and its extensions/capabilities as much as possible.

The Double Text module came from somewhere. The only themes I have installed are Typhoon, a child-theme based upon Typhoon (MyTheme) and I left Quark installed, but have not used it yet.

Odd, considering I just finish a fresh install of GRAV the other day. I'll look around a bit more, try to figure out where it came from.

**Comment by Umbyology** [comment]
I found the Double Text Module in the... Typhoon > Blueprints > Modular folder.

<img width="273" alt="Screen Shot 2021-02-03 at 8 51 20 PM" src="https://user-images.githubusercontent.com/22547499/106838437-ebde3000-6661-11eb-89e6-0abfc00b7b68.png">

<img width="382" alt="Screen Shot 2021-02-03 at 8 50 46 PM" src="https://user-images.githubusercontent.com/22547499/106838453-f39dd480-6661-11eb-8297-93d1471f2888.png">

**Comment by rhukster** [comment]
Ah that must of been from an older version, there is no TWIG so it's defaulting to `default.html.twig`.  I will remove it.
