### ISSUE TITLE
[typhoon] Where/How can I get a specific version of the theme (here v2.0.1 needed)?

### ISSUE THREAD

**Issue by AndeeZee** [getgrav/grav-premium-issues#384]
Dear all!

I inherited a theme customization from a colleague. This customization is based on Typhoon 2.0.1.
I know would like to clean up and updat to the latest Typhoon version and it would help to get the base theme v2.0.1 to compare, what changes were actually applied to it.
Unfortunately, I do not have that specific version of the typhoon theme.
Is there a way to download it/to get it via support?

Thank you,
Andy

**Comment by rhukster** [comment]
please email us at premium at getgrav.org and provide some info about the original purchase?  email/invoice#/license# etc.  Thanks!
