### ISSUE TITLE
[typhoon] updating from 2.3.3 to 2.4.3 breaks buttons

### ISSUE THREAD

**Issue by mcanfieldus** [getgrav/grav-premium-issues#390]
I am a new Grav Newbie so please forgive me.  When upgrading Typhoon from 2.3.3 to 2.4.3, I am unable to see my buttons on all my pages that have them.  Please refer to https://www.mudtrucknation.com/contact . There should be blue submit and reset button in the center.  The buttons exist but you cannot see them.  I have tried to restore and upgrade typhoon a couple times via admin console but get the same outcome every time.  Also all my links are no longer blue.  The screenshots below is v2.4.3 and then 2.3.3

![no buttons](https://github.com/getgrav/grav-premium-issues/assets/103128805/7b5a0f7d-2d69-42d5-970f-7b546aa785a8)

![buttons](https://github.com/getgrav/grav-premium-issues/assets/103128805/dac65cf0-862a-4c08-813b-4a72389ad1f5)

**Comment by mcanfieldus** [comment]
I have another site [GTRforSale](https://www.gtrforsale.com/contact) on 2.4.3 and it's not having this issue. All tags and external links are blue and also mouse over hover shows blue as well.  I tried replacing the typhoon theme folder from this site to the non working one but that did not fix the issue.

**Comment by rhukster** [comment]
I noticed that you are using Typhoon directly.  When you update typhoon, this is going to overwrite any changes you have made. I'm sure your problems are related to something you had changed, being reset by the update.  As per the docs, you really should either use a child theme, or better yet, use a clone of Typhoon and modify your own version of Typhoon.  Using the Typhoon update as a reference point for updating your theme as required.

**Comment by mcanfieldus** [comment]
I created a new beta.mudtrucknation.com site which replicates the production site and everything works great.  Then when i remove the production site and upload the beta site as the production site, the problem still exist.  Any tips would be greatly appreciated.

**Comment by mcanfieldus** [comment]
I was able to promote the beta site successfully and now everything is working as intended again.  Thanks for looking :).
