### ISSUE TITLE
Incorrect constant name for string ressource in blueprints.yaml (Typhoon)

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#393]
Hi,

In Typhoon’s **blueprints.yaml** ’THEME_TYPHOON.NOTICE_ONLY_ON_ROUTE’ has to be changed to ’THEME_TYPHOON.ADMIN.NOTICE_ONLY_ON_ROUTE’.
Same thing for the _HELP one. The `.ADMIN` part is missing in both cases.

Kind regards.

**Comment by rhukster** [comment]
Good catch.. fixed and will be in the next update.
