### ISSUE TITLE
[typhoon] CSS Font Question - custom CSS with no access to npm (simple Webserver install with no root)

### ISSUE THREAD

**Issue by myadminnet** [getgrav/grav-premium-issues#394]
Hi, 

I understand the normal procedure to change the theme-fonts in typhoon, utilizing custom-css + npm...

**But, how can I change the font in an environment with "no SSH/root" / i.e. no possibility to use npm with terminal...?**

Nevertheless, it must be possible... my easy approach would be: _Activating a modified theme version of typhoon, right? We tried already the CSS plugin with individual font settings with no success._

Can anyone please shed some light into this (sorry for not having checked all the code upfront myself ;-) )?

great thx & br

**Comment by rhukster** [comment]
You can install npm and follow the customization instructions on your local machine, and then copy the files up to your "no ssh/root" server.  This is the best solution.  Adding an additional custom css to override the tailwind CSS is possible, but really a bad solution that is not taking advantage of the numerous benefits that the npm build pipeline is providing.

**Comment by myadminnet** [comment]
thx - good point! 

reading your reply, I think its probably the best setup to have a Linode running with a full blown GRAV setup... (for design and tweaking purpose) + Export / Copy to the actual production env (running out of docker resources locally ;-) )
