### ISSUE TITLE
[seo-magic] Saving pages is slow / timing out - I think the plugin is running when saving modular pages too

### ISSUE THREAD

**Issue by ptarmic** [getgrav/grav-premium-issues#4]
Since installing the seo-magic plugin I'm finding making normal text changes on a page is now giving me an error "Save Failed: Idle timeout reached for https://my page url here". and also "You are editing a saved draft." Despite these messages my changes are being saved / pushing through to the frontend.

I tried to run the clockwork debugger but I can't distinguish all the "events" but happy to try again if needed.

**Comment by rhukster** [comment]
Could you have a look in your `logs/grav.log` file and look for any entry with `SEOMagic:` Does it output anything about the URL and does that URL for the page look correct to you?

**Comment by ptarmic** [comment]
Only mention of the seo plugin in the log is from running the process from the cli (I ignored a couple of pages and is working fine now), no other errors.

Actual screenshot in case it helps. I've never received this error before and now when I save any/every page. The url is for the current page and looks fine, no issues there.

![Screenshot_2020-12-17 Media and Delivery](https://user-images.githubusercontent.com/72616419/102524023-4ad6ee00-4090-11eb-9533-a68daa9029f4.png)

**Comment by rhukster** [comment]
This was caused by page crawling on save for modular pages.  I've added a check for `published` and `visible` and pushed this as 1.0.1 release.
