### ISSUE TITLE
Typhoon Theme Backticks rendered

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-premium-issues#40]
![grafik](https://user-images.githubusercontent.com/6888294/106940437-d597a900-6721-11eb-8d09-2cf27287579c.png)

Why are those backticks rendered? I guess that is by mistake!?

**Comment by w00fz** [comment]
No this is a TailwindCSS aesthetic design option that comes with their typography plugin.

It can be disabled, see https://github.com/getgrav/grav-premium-issues/issues/13
