### ISSUE TITLE
[typhoon] List a flex-object directory

### ISSUE THREAD

**Issue by EvgenyADE** [getgrav/grav-premium-issues#408]
Hi

I'm trying to create a directory of links. As I'm a beginner, I've tried to do this by modyfying a "Contacts" directory sample. More or less successfully.

Then I've tried to list fields in the way if is shown here https://learn.getgrav.org/user/pages/08.advanced/01.flex/01.administration/01.introduction/flex-objects-site.png
Also more or less successfully.

But now I'm trying to find out how this listing layout is to be modified. For example in a tabular way. Could you please help to find out what files contain the formatting?

**Comment by rhukster** [comment]
I'm afraid this is beyond the scope of Typhoon issues.  You shoud ask these kinds of questions in the Grav Discord chat. There's a flex-objects specific channel: https://discord.com/channels/501836936584101899/946831962931339325
