### ISSUE TITLE
[typhoon] Header height is somehow ignored wince latest typhoon update (2.4.4)

### ISSUE THREAD

**Issue by lpbellerose** [getgrav/grav-premium-issues#409]
Hi

I've lately updated the theme to the latest version (2.4.4) and somehow the tailwind height class for the header is not taken into account. The custom parameter from the admin is getting into the code alright, but when inspecting, it doesn't appear in the CSS. I've tried to clear the site's cache, but it didn't change anything.

You can see here: https://bellerosexd.com/en 

The class is there in the HTML:
![image](https://github.com/getgrav/grav-premium-issues/assets/29603484/08a1b468-e2bb-4355-8831-84f63085a633)

The logo is currently at a H-6 height, but header should be h-12 (3rem) which it is currently not:
![image](https://github.com/getgrav/grav-premium-issues/assets/29603484/28f80e86-6480-4bcf-bc11-84b7b6820d5e)

Any idea?

**Comment by rhukster** [comment]
Yes, you need to recompile the CSS to pick up any new classes that were not picked up during the initial Typhoon development.

Check out this section of the docs.

https://getgrav.org/premium/typhoon/docs#modify-the-css

If you want to be able to dynamically use some different clases you can put them in the `available-classes.md` file which sits in the root of the Typhoon theme folder.  This is also checked for valid classes during the compile time, so it's a great place to put a variety of `h-X` classes that you might want end users to pick from without having to recompile the CSS every time.

**Comment by lpbellerose** [comment]
Thanks @rhukster, it took me a while debugging and getting everything ready to make the build. From what I can see, the h-12 was not used anymore, which is understandable, but for an admin type of user, it would be nice to have some gradation of heights, widths and so on to use whether or not it is used in the code so we can use it in the admin without going through all the npm process.
