### ISSUE TITLE
Typhoon Rockets Demo defect

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-premium-issues#41]
https://demo.getgrav.org/typhoon/rockets/design
![grafik](https://user-images.githubusercontent.com/6888294/106940603-0aa3fb80-6722-11eb-91d4-cf2167ede047.png)

You can see `[2]` as well as a `[figure]` tag.

---

Another (similar) issue:

> ! Remember, if you change the theme name, you should also change the typhoon.yaml and typhoon.php section in the purge configuration.

https://demo.getgrav.org/typhoon/rockets/start-here

**Comment by w00fz** [comment]
Thank you, I fixed this now :)
