### ISSUE TITLE
[algolia-pro] Prerequisite for Algolia pro ?

### ISSUE THREAD

**Issue by KentousHodo** [getgrav/grav-premium-issues#410]
Hello everyone,

I am currently experiencing problems with my Algolia Pro installation. I may have relied too much on the "No coding needed" and as I'm an amateur website builder I don't understand the problem.

However, I'd like to make sure I've got the basics right so I can understand my mistake, and that's why I've come to ask for your advice. 

I started building my site after watching Kezz Bracey's "Up and Running With Grav CMS" course. However, the course is old (2017) and I'm thinking that maybe I'm missing some basic elements in my theme that must be compounding the problems.

Trying to use the "quark" theme I actually have fewer problems and the front end seems to work much better.

Could you tell me what essential elements of the quark theme I need to include in my theme to enable the plugin to work?

Thank you in advance for your help to someone who misjudged the difficulty of the task (I'm pretty confused, but I really capitalized on the "no coding needed").

_**Some information**_ 

Grav v1.7.44

Plugins :
Admin Panel v1.10.44
Algolia Pro Prémium v1.0.15
Email v4.0.4
Error v1.8.0
Flex Objects v1.3.6
Form v7.3.0
License Manager v1.0.2
Login v3.7.7
Markdown Notices v1.1.0
Page Toc v3.2.2
Problems v2.1.1
Sitemap v5.0.0

Site visible here : https://www.reflexio.fr/ (search item don't works and box visible in the footer)

**Comment by KentousHodo** [comment]
Short new information : I have add : 
![image](https://github.com/getgrav/grav-premium-issues/assets/134169940/545cf2e1-42eb-4759-a446-44c1f9a15400)
![image](https://github.com/getgrav/grav-premium-issues/assets/134169940/3aff319b-d422-44b9-8c0f-b41d10da3b52)
ANd it's better.
But no understand why because i have not copy the js folder in my theme ><
![image](https://github.com/getgrav/grav-premium-issues/assets/134169940/93daaf20-46db-4ea5-8056-a17bd7dcb588)

**Comment by rhukster** [comment]
If you are using a custom theme, you really only need to have this bit at the top before the closing `</head>` tag:

```
{% block assets deferred %}
    {{ assets.css()|raw }}
    {{ assets.js()|raw }}
{% endblock %}
```

And this at bottom before the closing `</body>` tag:

```
{% block bottom %}
    {{ assets.js('bottom')|raw }}
{% endblock %}
```

This is basically what Quark has to output the relevant CSS and JS bits that Algolia Pro will use. 

After that you will need to include the actual twig template logic that can render the search box:

https://getgrav.org/premium/algolia-pro/docs/frontend#loading-the-template

And lastly you need to have an element in your theme that should 'trigger' the search box.  This is typically a search icon or a search button.  You just need to add a simple `data-algolia-pro-trigger` attribute to any tag: https://getgrav.org/premium/algolia-pro/docs/frontend#delegate-a-trigger-element

To quickly test, just add a simple search link in the `user/themes/quark/templates/partials/navigation.html.twig`:

```
{% import 'macros/macros.html.twig' as macros %}

{% include 'partials/login-status.html.twig' ignore missing %}

<ul {{ tree ? 'class="tree"' : '' }}>
    {{ macros.nav_loop(pages) }}
    <li>
        <button type="button" data-algolia-pro-trigger>Search</button>
    </li>
</ul>
```

That should do it.

**Comment by KentousHodo** [comment]
OK, i have delete the "block javascript" from my code.
Thank you for this information about what my base.html.twig must contain.
I have already done the two other step. I think it's OK in front-end. (I have the box like in the GRAV website help) Now i will work on back end as search doing nothing.
Trying by myself first, maybe ask help in one or two weeks.
Again, thank you ! :)

**Comment by KentousHodo** [comment]
OK, i have delete the "block javascript" from my code.
Thank you for this information about what my base.html.twig must contain.
I have already done the two other step. I think it's OK in front-end. (I have the box like in the GRAV website help) Now i will work on back end as search doing nothing.
Trying by myself first, maybe ask help in one or two weeks.
Again, thank you ! :)
