### ISSUE TITLE
[typhoon] No Content Box for Blog Pages entry

### ISSUE THREAD

**Issue by zwankie** [getgrav/grav-premium-issues#411]
When using the Typhoon Theme there is an issue where there is no Content input text box for the Normal setting in the Content tab when trying to add a Blog page, only Title and Page Media shown.

When changing to Advanced mode there is a Content Box, the data entered works and displays the content only in the summary of a blog post, not when the blog post is opened.

However, when I change the Theme to a Grav default or Pinpress for example the Content field is fully visible in Grav Admin Pages for the Blog. I can then enter content and view it in Admin and the public page but when I switch back to the Typhoon theme it disappears from the Grav Admin page to edit the blog post and is also not displayed correctly on the public page.

![Grav-Admin-Pages-Blog-Content-Missing](https://github.com/getgrav/grav-premium-issues/assets/5724648/ec566de4-b9a4-4308-8b32-c8811db8f5dd)

Typhoon V2.4.5

**Comment by zwankie** [comment]
My apology, I just needed to read the documentation properly.

For Typhoon the blog post page type needs to be set to post, not blog.

It seems to not make a big difference on other themes I tested but definitely need to be type post with Typhoon.

This might help someone else.

**Comment by rhukster** [comment]
Glad you got it sorted. That was going to be my frist question!
