### ISSUE TITLE
[typhoon] Height of footer

### ISSUE THREAD

**Issue by and-42** [getgrav/grav-premium-issues#414]
Hi,

I'm looking for an easy solution to set the height of the footer.
Is there any option, without creating a custom theme?

Thanks in advance

**Comment by rhukster** [comment]
The height of the footer is realy dictated by the amount of content in the footer, and also the vertical padding around that content.  It's not a fixed height, nor should it be.  If you add more footer menu items the height will automatically adjust.

**Comment by and-42** [comment]
Thanks for the clarification.
