### ISSUE TITLE
[seo-magic] Minor spelling error in SEO Report section

### ISSUE THREAD

**Issue by Currey** [getgrav/grav-premium-issues#415]
There are minor spelling and grammar errors in the Seo-Magic Selected Body Text section of the SEO Report. The message with instructions that sits under the title.

Currently, it reads:
> This is the body that is selected based on the **Body elector** configuration option. It is used to determine automatically generate **Metadata Keywords** and **Metadata Descriptions**. The current **Metadata Keywords** are highlighted.

Whereas, I believe it should read:
> This is the body that is selected based on the **Body selector** configuration option. It is used to determine automatically generated **Metadata Keywords** and **Metadata Descriptions**. The current **Metadata Keywords** are highlighted.

![Screenshot-2024-02-20-at-13 44 54](https://github.com/getgrav/grav-premium-issues/assets/4483709/f16b1796-0a00-4ed7-baaf-1a0d519b8d2e)

**Comment by rhukster** [comment]
Thanks.. fixed for next release
