### ISSUE TITLE
How do I stop emails being sent to me

### ISSUE THREAD

**Issue by mfuggle** [getgrav/grav-premium-issues#416]
I have unsubscribed a dozen or more times trying to stop receiving emails from Grav stuff but they continue to come. If they don't stop I'll report the site so that it gets black listed.
I'm fed up unsubscribing.
Martin Fuggle

**Comment by rhukster** [comment]
What emails? We’re not sending any emails? Can you provide an example?

**Comment by mfuggle** [comment]
Maybe you could tell me what this is.

￼

Regards
Martin Fuggle
0408 265 586
***@***.***

Please note my new email address which is ***@***.***

**Comment by mfuggle** [comment]
Here’s a sample of the emails I am getting.


￼
Regards
Martin Fuggle
0408 265 586
***@***.***

Please note my new email address which is ***@***.***

**Comment by rhukster** [comment]
I can't see anthing other than a weird special character. How about a screenshot? I still really don't know what you are referring to.

**Comment by rhukster** [comment]
Here's a screenshot of your reply:

![Uploading CleanShot 2024-02-20 at 14.23.00@2x.png…]()

**Comment by mfuggle** [comment]
I’ll send another image of the emails being received. But maybe you can see from your email below that it just says Uploading Cleanshot etc but displays nothing.

Regards
Martin Fuggle
0408 265 586
***@***.***

Please note my new email address which is ***@***.***

**Comment by mfuggle** [comment]
Hi Andy,

See image attached below.

Regards
Martin Fuggle
0408 265 586
***@***.***

Please note my new email address which is ***@***.***

**Comment by rhukster** [comment]
Can you try visiting in your browser? Maybe incognito mode.  I think it’s something on your end. My screenshot shows fine. I can’t see anything you are posting. Replying via email might be the problem. This is a GitHub.com issue tracker.  Are you saying you are getting emails from GitHub? Maybe you accidentally subscribed to all issues or something? I’m a bit confused :)

**Comment by rhukster** [comment]
Try support@trilbymedia.com
