### ISSUE TITLE
[algolia-pro] Unexpected unauthorized license key

### ISSUE THREAD

**Issue by ninjah187** [getgrav/grav-premium-issues#417]
Hi,

I want to install Algolia Pro 1.0.15 on Grav 1.7. I am following documentation and did following steps already:

- upgraded Grav
- installed sitemap plugin
- installed license-manager plugin
- bought Algolia Pro license key and added it via license manager admin panel (it was successful)

Here's where problem arises. After adding the license key, I see button "Install Algolia Pro". I click it, installation goes well and I see success message, but then I am getting redirected to /admin/404 and there is no sign of Algolia being installed (no changes in admin panel, neither file system).

I checked grav.log file but no entries regarding Algolia Pro installation there.

Then, I tried to install Algolia Pro via gpm and the output is:

```
Preparing to install Algolia Pro [v1.0.15]
  |- Downloading package...    error
  |  '- Unauthorized Premium License Key
  '- Installation failed or aborted.
```

However, the license key is still remaining in license manager admin panel and looks valid.

One thing worth noting is that the license key was bought few months prior to its first activation (< 1 year). Is there any chance that this key got deactivated due to it's late first activation maybe?

Another thing worth noting is that I am trying to perform all of this on localhost (we have dev / staging / prod environments setup). Maybe it's not supposed to work on localhost at all and I need public domain for it?

Thanks for your input

**Comment by rhukster** [comment]
Hi @ninjah187 would yo mind please sending your user/data/license.yaml file to us via premium@getgrav.org so i can investigate this further?
