### ISSUE TITLE
[instagram-feed] Show only the images from visible posts

### ISSUE THREAD

**Issue by ohjay86** [getgrav/grav-premium-issues#418]
Hi, 
Is it possible to display only the images from currently visible posts? 
When I delete a post on Instagram, the image is still displayed in the Instagram feed on the Grav page.
Is there a way to change this?

Thanks for your help
Oliver

**Comment by rhukster** [comment]
Clear your Grav cache.

The instagram API calls and images are locally cached to get around the slowness of the API call, as well as the requet limits.  Clearing Grav cache should cause a fresh API call and get the latest state.

**Comment by ohjay86** [comment]
Hi thanks for your reply,
I have deleted the cache. But the pictures are still there. 
I removed the deleted posts on Instagram from the trash and the pictures are still there.
Is there another place where the Instagram data is cached?

**Comment by ohjay86** [comment]
I've removed all images from `user/assets/instagram-feed` and now it seems to work.
