### ISSUE TITLE
Post Install Typhoon Theme Issue

### ISSUE THREAD

**Issue by 3li0** [getgrav/grav-premium-issues#42]
Just purchased this theme as well as the enhanced editor. Everything looked ok during the installation, however I am now unable to access certain aspects of the admin interface post install. For instance if I go to the "pages" submenu I get the following error message:

ERROR: flex-objects.html.twig template not found for page

Same error occurs when I go to "accounts". I would like to see where the error is stemming from but unfortunately I am still very new to Grav in general. I do like the theme and the editor upgrades, but as it stands it looks like there is some sort of issue causing the functionality of the admin interface to break (at least for my install).

I am on the latest version of Grav running PHP 7.4 - any assistance would be appreciated.

**Comment by rhukster** [comment]
First, I don't think this is an issue with Typhoon, or NextGen, but rather with your Grav installation.  What version of Grav + Admin are you running? It sounds like you are using Grav 1.7, is it the latest 1.7.5 version?  Also what version of Admin + FlexObjects plugins are you running?

Lastly what platform is this on? Mac, Windows, Linux etc?

**Comment by rhukster** [comment]
BTW, we had a similar issue reported before and the culprit was the `content-edit` plugin:

https://github.com/getgrav/grav/issues/3169#issuecomment-767581767

If you have that plugin, please disable or better yet, uninstall it.

**Comment by 3li0** [comment]
Thanks for the help...

I am running: Grav v1.7.5 - Admin v1.10.3

And I just tried disabling content-edit. That fixed it!

Thanks so much for the help!

**Comment by rhukster** [comment]
Glad that sorted it.
