### ISSUE TITLE
[typhoon] ICO favicon with multiple sizes (16+32) not supported

### ISSUE THREAD

**Issue by Fifis** [getgrav/grav-premium-issues#421]
Good afternoon!

So far, most recommendations on the main forum have been about modifying twigs to get proper PNG favicons.

However, in small raster image design, there are explicit recommendations to edit 16x16 or 32x32 files directly to achieve the best crispiness and legibility and to avoid poor anti-aliasing / blurriness due to rescaling.

I have created a proper ICO file that has 16x16 and 32x32 variants, but the Grav CMS won’t accept it. In addition, many usability analysers explicitly recommend putting `favicon.ico` into the root folder.

Is there a possibility to upload a fully compatible hand-optimised ICO without getting the ‘Unsupported MIME type’ error? Or to safely excise this `link rel="icon"` property from the site so that the default `favicon.ico` be served from the site root?

I am using Grav 1.7.44, I purchased the Typhoon professional theme a couple of days ago, and its version is 2.4.5.

Thank you in advance!

Yours sincerely,
Andreï.

**Comment by rhukster** [comment]
Frankly `.ico` is very 2000's, it's redundant these days as `.png` is fully supported and a better more portable format.  Even better is an `.svg` which is supported in all modern formats, and is vector so can scale for any size + very small KB.

Regarding the ability to change this, it's not something that is done often, so is not in the admin.  You should just add the favicon (.png/.svg/.ico/etc), to the theme's `images/` folder, and then modify the `base.html.twig` to reference it.  it's a very simple process.

**Comment by Fifis** [comment]
Thank you for the prompt reply!
As ‘2000s’ as ICO files are, they work the best on FullHD desktops because Firefox is showing 16×16 ones in the tabs, and the bilinear down-scaling of a hi-res 128×128 PNG one results in a very ‘mushy’ and illegible 16×16 version.
This is why I would like to use the pre-generated optimal versions for each size and serve what’s needed. Since PNG files can only hold one layer / page, is it possible to declare multiple favicon sizes (e.g. `favicon16`, `favicon32` etc.) in the twig? E.g. would it be valid (or optimal) to write something like this:
```html
<link rel="icon" href="/path/to/favicon-16.png" sizes="16x16">
<link rel="icon" href="/path/to/favicon-32.png" sizes="32x32">
<link rel="icon" href="/path/to/favicon-128.png" sizes="128x128">
```

**Comment by rhukster** [comment]
Frankly if you really want to have multiple ico images like that, simply edit the `partials/base.html.twig` and add them yourself.  That way you have complete control.

**Comment by Fifis** [comment]
Thank you, I am going to do that in a child theme with inheritance.
