### ISSUE TITLE
[taxonomy] Original + translated tags on bilingual site on default language

### ISSUE THREAD

**Issue by sebastian0119** [getgrav/grav-premium-issues#425]
Hi there!

I am using the Typhoon theme with blog functionality, with two languages activated: Spanish (ES) as default language and English (EN) as second option.

So each post has currently two files in each directory:
```
spec.md
spec.en.md
```
where spec.md is the default file (in Spanish) and spec.en.md the translated file.

Each file has in its frontmatter something like this (extract):

- For default files in Spanish:
```
---
taxonomy:
    tag: [diseño, planos, inspección]
---
```

- For translated files in English:
```
---
taxonomy:
    tag: [design, cds, supervision]
---
```

When switching to English, the taxonomy list is "translated" correctly, means that it only filters the tags from all spec.en.md files.  
See also the following image:
![image](https://github.com/getgrav/grav-premium-issues/assets/52871458/3f122850-12c8-41e3-a07c-82e85f6764d9)

However, when using Spanish as the default language, all tags are duplicated, meaning that the Spanish version + the English version are listed (e.g. diseño + design or planos + cds).  
Another image:
![image](https://github.com/getgrav/grav-premium-issues/assets/52871458/7c20cbbf-4881-4c60-aac7-893550bbf871)

All the rest of translation is working well, the URL also always indicates which language is used (e.g. https://localhost:8000/es/blog/ or https://localhost:8000/en/blog/); it's just the tags. 

And by the way, when being in the Spanish environment and clicking on a tag in English from the tag list (e.g. design), an empty list of posts comes up, whereas when clicking on "diseño" the correct list of posts is shown. 

Any idea or suggestion is appreciated.

Grav v1.7.44
Taxonomylist v1.3.5

**Comment by sebastian0119** [comment]
A quick afterthought: I seems that it has something to do with the cache. 

When I am on the English version and clear the cache, then all tags are fine (English only). Switching to Spanish, tags for English + Spanish come up.

The other way around is exactly the same: when I am on Spanish and clear the cache, all tags are find and when switching to English, both versions are shown.

Right now, where this problems occurs, I am on development settings:

```
cache:
  enabled: true
  check:
    method: file
```

**Comment by sebastian0119** [comment]
Seems related to https://github.com/getgrav/grav-plugin-taxonomylist/issues/40

**Comment by rhukster** [comment]
Yes, this is a taxonomy specific issue, not an issue with Typhoon itself.  I'll pick up the conversation on the taxonomy plugin issue.
