### ISSUE TITLE
[typhoon] "classes=float-left" doesn´t work

### ISSUE THREAD

**Issue by Lurican** [getgrav/grav-premium-issues#426]
Hi everybody!

I am using

Grav: v1.7.44 with
Typhoon: v2.4.5

and I´m not able to show a floating image as expected.

In a default-Page I used the syntax as follows:

`![myimg](myimg.png?classes=float-left) The rest of my text...`

But in the frontend, the image was shown in a line seperately.

Best regards

Marc

**Comment by rhukster** [comment]
You will need to rebuild the CSS to include the new class:

https://getgrav.org/premium/typhoon/docs#developing-custom-css

Also you can include specific classes in the `available-classes.md` file to make sure they are always picked up and available to be used without having to do a recompile each time.
