### ISSUE TITLE
[nextgen-editor] Unexpected user permissions error with PageInject

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-premium-issues#43]
While trying out the new user management features of Grav 1.7, I've noticed that with the NextGen Editor I can no longer edit pages that contain PageInject Shortcodes for site Editors, here is what I see:

<img width="1440" alt="2021-02-08_11-57-41" src="https://user-images.githubusercontent.com/1812771/107274103-dcb20600-6a04-11eb-861d-d94570cc4971.png">

When I then try to view the Pages panel this error message is displayed:
<img width="1440" alt="2021-02-08_11-35-02" src="https://user-images.githubusercontent.com/1812771/107274183-e6d40480-6a04-11eb-8829-29bcd4561594.png">

Happy to test/share more info etc. Also, you learn more about the (basic) two user setup I am trying at this GitHub issue https://github.com/getgrav/grav-plugin-admin/issues/2053 (basically two user groups, where each user group can edit one folder of Pages).

UPDATE: This issue seems to prevent editing of ALL pages for users added in addition to original Super User, even just loading a page in NextGen for viewing etc. I can share pre-built Skeleton with this issue if helpful.

Thank you,
Paul

**Comment by rhukster** [comment]
What permissions does this user have? And do you mean that even super user can no longer edit?

**Comment by paulhibbitts** [comment]
Thanks @rhukster The original super user can still edit, but all users added with various rights etc cannot edit or view any page (NextGen always shows red dot progress). I've got two users, with access to two folders, but even page without any group permissions are not viewable/editable. 

I shared my setup in this Tweet:
https://twitter.com/hibbittsdesign/status/1358874005982224384?s=20

I can share my Grav user folder with you if helpful etc.

Thanks,
Paul

**Comment by rhukster** [comment]
OK, sounds like we might have a super user requirement in the inject logic.

**Comment by paulhibbitts** [comment]
I think your hunch is right @rhukster , I just set one of the two editor users to Super User and I was then able to use the NextGen Editor for that user!

**Comment by rhukster** [comment]
Hmm. Do your users have **Admin Pages** access?

The code in PageInject has:

```php
$controller->authorizeTask('pageInject', ['admin.pages', 'admin.super']
```

in this method:

```php
public function onAdminTaskExecute(Event $e): void
    {
        if ($e['method'] === 'taskPageInjectData') {
            header('Content-type: application/json');
            header('Cache-Control: no-cache, no-store, must-revalidate');
            $controller = $e['controller'];

            if (!$controller->authorizeTask('pageInject', ['admin.pages', 'admin.super'])) {
                http_response_code(401);
                $json_response = [
                    'status'  => 'error',
                    'message' => '<i class="fa fa-warning"></i> Unable to get PageInject data',
                    'details' => 'Insufficient permissions for this user.'
                ];
                echo json_encode($json_response);
                exit;
            }

            error_reporting(1);
            set_time_limit(0);

            $json_response = $this->getPageInjectData();

            echo json_encode($json_response);
            exit;
        }
    }
```

Please provide your users/groups setup so I can inspect.  Cheers.

**Comment by rhukster** [comment]
Based on your screenshot, your users only have READ + LIST, I think that's the issue. Digging deeper...

**Comment by rhukster** [comment]
I'm struggling to recreate this actually, but can you try changing line 70 in `user/plugins/page-inject/page-inject.php` to:

```php
if (!$controller->authorizeTask('pageInject', ['admin.pages.read', 'admin.pages.list', 'admin.super'])) {
```

**Comment by paulhibbitts** [comment]
Good news @rhukster , that fix looks to work like a charm! Users can now edit/view pages with NextGen just as they can with the standard Editor. Happy to further test for you, but that sure looks good on my end.

**Comment by rhukster** [comment]
Probably only needs "read", so going to change to that and push the fix.

**Comment by rhukster** [comment]
OK, fixed for the upcoming release: https://github.com/getgrav/grav-plugin-page-inject/commit/fa4f100a94495f6c8286c1e13487f7ccf52b9af2

**Comment by paulhibbitts** [comment]
Thank you very much @rhukster 👍
