### ISSUE TITLE
[typhoon] Gallery grid columns

### ISSUE THREAD

**Issue by Mikfr83** [getgrav/grav-premium-issues#431]
Hello Andy, 

Some noob questions :)

I would like to increase the number of columns in the gallery template.
I tried these tailwind classes:
- `grid-cols-2 sm:grid-cols-4 lg:grid-cols-8`
- `grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8`

But the result is not consistent, it seems impossible to obtain more than 4 columns.
It's the same with the features template.

And another query about the gallery ...
I need to setup a gallery with images / thumbnails in different size and aspect ratio (portrait & landscape).
There is a way to achieve that with the default gallery ?

PS: I duplicated the Typhoon theme, to start a custom one.

Thanks,
Michael

**Comment by rhukster** [comment]
You are probably not recompiling the css to pick up those new classes.  There’s a section in the docs that explains how to do it.  Scripts are written for you, just need to install the node modules.

**Comment by Mikfr83** [comment]
Actually, there is no change in the css on my side.

With the Typhoon theme, in the gallery, the issue appears with a simple tweak of the default settings:
![pW6wiovMCJ](https://github.com/getgrav/grav-premium-issues/assets/11748560/cef9181c-5dbe-401c-a532-65a204f3db5b)

The result:
![x8mlwk0XgJ](https://github.com/getgrav/grav-premium-issues/assets/11748560/c8b3d337-03eb-4108-9e17-dadff99f19ce)

Or more simple:
![t8jePBxk6y](https://github.com/getgrav/grav-premium-issues/assets/11748560/e93dbfe8-fe06-430a-9c88-a4482d20e11b)

Result:
![N17LItLnsG](https://github.com/getgrav/grav-premium-issues/assets/11748560/c5612942-687c-4ecd-9000-bf05ac81aada)

**Comment by Mikfr83** [comment]
Ok, thanks for your answers !
It wasn't clear in my mind, I assumed that all tailwind classes were available by default.
