### ISSUE TITLE
[typhoon] Login form white in dark mode

### ISSUE THREAD

**Issue by Mikfr83** [getgrav/grav-premium-issues#433]
Hi,

The login form remains white in dark mode

![ptWm1ri5AY](https://github.com/getgrav/grav-premium-issues/assets/11748560/1ba3924c-866d-450d-aaed-75a45a439c5b)

What's the easiest way to fix this?

Thanks,
Michael

**Comment by rhukster** [comment]
Must of missed this!

First step is to turn off the CSS that the login plugin provides, either via admin or in the `user/config/login.yaml` by setting:

```yaml
built_in_css: false
```

Then you will need to add some styling.  I just added this at the bottom of the `css/custom/plugins.css`:

```css
/* LOGIN PLUGIN */
#grav-login {
    @apply max-w-md p-6 mx-auto my-4 rounded-md bg-gray-100 dark:bg-gray-700/75 ;
    h1 {
        @apply text-center;
    }

}
/* END LOGIN PLUGIN */
```

NOTE: You will need to compile your CSS with the provided scripts to pick up this change: https://getgrav.org/premium/typhoon/docs#installing-npm-to-compile-css

I didn't add too much styling, as the intention is that you would style this as you need to.  However, it does look better than before:

![CleanShot 2024-04-23 at 12 25 25@2x](https://github.com/getgrav/grav-premium-issues/assets/1084697/652fe66d-b5b3-40d2-aac0-eaa52be30a11)

These changes will be in next release, but it's easy enough to add yourself.

**Comment by Mikfr83** [comment]
Thanks for your reply and the solution !
