### ISSUE TITLE
[typhoon] Different background on different pages

### ISSUE THREAD

**Issue by snakefox** [getgrav/grav-premium-issues#436]
Hi,

I started to build my own page with Typhoon and can see that the background is not always the same when switching between some pages.
Here it is correct and the same as on the other pages:
![image](https://github.com/getgrav/grav-premium-issues/assets/13438084/c78687d3-b38d-4f28-90b5-02ebb78023ac)

But when clicking on a post inside the same blog, it looks different:
![image](https://github.com/getgrav/grav-premium-issues/assets/13438084/276e3211-5035-463a-a97e-5bd1a7ce6b8c)

How can I change it easily ? It should always stay in gray.

Thank you, BR / Fatih

**Comment by rhukster** [comment]
I would really need to see what you have changed to know what you need to do.  however, in my testing, i changed the class in the `<body>` tag of `partials/base.html.twig` from `dark:bg-gray-900` to `dark:bg-red-700`.

I also noticed in Typhoon's `blog.html.twig` there's a slightly different bg color, so I changed `dark:bg-gray-800` to `dark:bg-red-600`

and also in the Typhoon configuration file, i changed the section classes to:

```yaml
section_classes: 'bg-white dark:bg-red-700 py-8 md:py-24'
```

That seems to have fixed most of my test cases.  Really the easiest way to handle these types of changes is to inspect the page and find where the background color is set.. find the class.. (e.g. `dark:bg-gray-900`) and then use your IDE to find all occurrences of this, and just change it.

Of course, you probably will need to recompile the CSS to pick up this new color change.. so please follow the documentation for this process: https://getgrav.org/premium/typhoon/docs#modify-the-css

**Comment by snakefox** [comment]
Hi @rhukster,

I made the change in `blog.html.twig` which you have proposed and it is working for me. Thank you very much for your support!
Can be closed.

BR
