### ISSUE TITLE
[typhoon] Removing Grav copyright line from footer

### ISSUE THREAD

**Issue by snakefox** [getgrav/grav-premium-issues#437]
Hi,

I am using Typhoon as a Premium template where a Grav copyright line is always added by default, see Screenshot below.
I would like to know if I am allowed to remove it from the footer w/o any legal issues ?

![image](https://github.com/getgrav/grav-premium-issues/assets/13438084/a2364ef4-a3e1-4b02-8997-657942e938ff)

The page is planned to be used for commercial purposes.

Thank you

**Comment by rhukster** [comment]
Of course you are fee to remove it
