### ISSUE TITLE
[typhoon] svg icons as custom bullet symbol

### ISSUE THREAD

**Issue by thebasti314** [getgrav/grav-premium-issues#439]
Hey there,

what would be the easiest way, to use some of the svg icons as a custom bullet symbol in an unordered list? And how to set the color. I'm not sure where to define. 

Many regards!

**Comment by rhukster** [comment]
This is really beyond the scope of Typhoon theme.. It's just CSS though, I suggest someting along the lines of: https://www.svgbackgrounds.com/custom-css-bullets-with-marker/

When you make changes to CSS though, you will need to recompile the Typhoon CSS: https://getgrav.org/premium/typhoon/docs#modify-the-css
