### ISSUE TITLE
'prose' class somewhat undocumented in Typhoon theme...

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav-premium-issues#44]
Having a dig around with Typhoon and I came across a somewhat confusing issue...

Trying to replumb the 'blog' template adding in a simple div to hold a title

`<div class="bg-indigo-400">{{ page.content|raw }}</div>`  (my test content is a markdown h1, so `# My Title`

This displays unstyled text, while `{{ page.content }}` displays unstyled text with my H1 tags!!

Through trial and error I discovered a weird 'prose' class that seems to fix the issue and enable markdown-styled content.

Can we get a bit more info on what this is and how/where it comes into play?

thanks!

**Comment by rhukster** [comment]
Although this doesn't look like a Typhoon specific issue, it does look weird.

Content is one of those field in a Page object that is automatically processed with makdown. So there's no reason why it would show that markdown in content.  If it was a title, such as:

````twig
<div class="bg-indigo-400">{{ page.title|raw }}</div>
```

And your title had markdown that would be expected and you could process that markdown explicitly with the `|markdown` filter. 

Are you sure your code is right?

If you mean that the content is not HTML styled, hat is related the `.prose` class you mentioned.  In TailwindCSS, there's no default styling, even for standard H1 tags, so you either need to add those explicitly in your twig, or use the `.prose` class which adds default styling for most basic HTML (Stuff that markdown supports).

So either something like:

```twig
<div class="bg-indigo-400 text-4xl">{{ page.title }}</div>
```

or:

```twig
<div class="bg-indigo-400 prose">{{ page.title|markdown }}</div>
```

I'm not 100% sure what you have and what you are doing, but maybe this will give some insight?

**Comment by rhukster** [comment]
BTW: https://github.com/tailwindlabs/tailwindcss-typography

This is the plugin we use for the typography, this is what makes `.prose` available.  We do some overrides and tweaks in a few places, but you can see the full docs with the link above.

**Comment by MattAppleton** [comment]
That helps seeing tailwinds-typography, thanks - not familiar with this plugin...

But still slightly confused by what the Twig is showing, see here...

```
 <div class="bg-indigo-400 prose">{{ page.content|raw }}</div> {# ! works, shows <h1>Title!</h1> <h2>Title!</h2> correctly #}
    <div class="bg-indigo-400 prose">{{ page.content }}</div> {# ! doesnt work, shows <h1>Title!</h1> <h2>Title!</h2> as raw unstyled html #}
    <div class="bg-indigo-400 ">{{ page.content|markdown }}</div> {# ! doesnt work, shows <h1>Title!</h1> <h2>Title!</h2> as unstyled text #}
```

shows as:

 
![SS_ 2021-02-10 at 09 51 32](https://user-images.githubusercontent.com/6295710/107494459-bc11b980-6b86-11eb-8e3f-d72a528f6210.png)

**Comment by rhukster** [comment]
I think all that is just the effects of the default setting in grav 1.7 where twig auto escape is now enabled by default.  You have to use |raw to output as html or it’s escape and html doesn’t render but is visible. 

You can disable this behavior in system config but it is that way for security reasons. 

More info in the grav 1.7 upgrade guide in advanced section of learn.

**Comment by MattAppleton** [comment]
Got it!


thanks...

**Comment by MattAppleton** [comment]
Just exploring this a bit further — was wondering — where does the {{ prose_style }} variable come from? Could find it in the docs / GRAV Api...

**Comment by rhukster** [comment]
It's actually just set in `partials/theme-variables`.  It's currently not configurable, I just needed a unified variable to allow a one-place change if needed.
