### ISSUE TITLE
[typhoon] Personal-related data collected by Typhoon code

### ISSUE THREAD

**Issue by snakefox** [getgrav/grav-premium-issues#445]
Hi,

due to GDPR, I would like to know what kind of personal related data is collected by Typhoon code on server-side, e.g. IP address or timestamps when a user accessed the web page, browser type, browser version, etc.

In Germany such topics are taken very seriously and we have always to inform users about any data that is collected about them.

Thank you, BR / Fatih

**Comment by rhukster** [comment]
There is nothing collected by the typhoon codebase, it's just a theme.
