### ISSUE TITLE
[typhoon] Problem creating a child-theme

### ISSUE THREAD

**Issue by CunoVoll** [getgrav/grav-premium-issues#446]
Hello

I wanted to create a child theme from the Typhoon theme, but apparently there are problems with the Color Tools plugin. Regardless of whether I create the child theme "by hand" or by CLI command, a server error message appears (see image). If I deactivate the Color Tools plugin, the error message disappears, but the site is not displayed correctly. I am working on Windows 10 with Grav v1.7.46 and laragon-PHP 8.1.1

Many thanks in advance for your support.
Cuno

![typhoon_child-theme](https://github.com/getgrav/grav-premium-issues/assets/60263942/1e873a8a-50d3-4bbb-a3eb-8b3758822bd4)

**Comment by rhukster** [comment]
The issue is not with the color tools plugin itself, it's with the child theme configuration.  The devtools plugin has an issue with nested quotes.  The fix is quite simple:

https://github.com/getgrav/grav-premium-issues/issues/423#issuecomment-2017682279

**Comment by CunoVoll** [comment]
Many thanks for the quick answer to my question. i will try this fix next week. 
Have a nice weekend. Regards, Cuno

**Comment by CunoVoll** [comment]
It worked. Thanks a lot.
