### ISSUE TITLE
Typhoon header background

### ISSUE THREAD

**Issue by tonhaarmans** [getgrav/grav-premium-issues#45]
It appears that the background color of the header element in the theme Typhoon does not change when setting the theme color chooser. See https://www.wideopenwindows.be

**Comment by rhukster** [comment]
Are you referring to the light/dark/system chooser option?  It's not supposed to change with that, as it is intended to be selected to work with the hero image, not the light/dark setting of the theme.

**Comment by tonhaarmans** [comment]
Ok, got it. Thanks.
