### ISSUE TITLE
[lightbox-gallery] Cant put the watermark on a zoomed version of the image

### ISSUE THREAD

**Issue by stbs01** [getgrav/grav-premium-issues#454]
Hi!

I am using a https://github.com/paulmassen/grav-theme-hyde Grav Theme (v0.2.2) with a Premium Lightbox Gallery Plugin (v1.0.6) on a Linux VPS Server. Now I have the following problem with the Lightbox Gallery Plugin:

I can't set up a second image in the Gallery Plugin to show the zoomed image with watermark similar as it is done here: https://www.andreasgursky.com/en/works/1997/times-square/zoom:1
I want basically the same - if you see the whole image, you dont see any watermarks, but if you zoom in, then you see them.

If you go to http://draft.teimur-bek-safiuli.com/works - you will see it.

Thanks for your help!

Best,
Teimur

studio@teimur-bek-safiuli.com

P.S. I have a pretty experienced guy who helps me to build my artist portfolio website, but here he cant help me anymore, thats why I need your help 🙏🏼

**Comment by rhukster** [comment]
Watermarks are not somethign the plugin does (neither lightbox-gallery nor GLightbox), you have to add them to your image manually.  This image has one: http://draft.teimur-bek-safiuli.com/images/5/9/7/5/1/59751f2767c09804fa81b5cf1f37035d5d9efda6-pexels-photo-3573351.jpeg

It's there in the full view when zoomed in or not, which is as expected as it's the same image in both cases. The zoomed in view is not a different image, it's just a fullsize version at 100% native resolution.  The default view is scaled down to fit the display.  So you can't have one with watermark and one without, it's the same as asking if you can have regular view being one image, and a zoomed in view being a totally different image.  The short answer is no, it's not how it is intended to work.

Sorry, but that's just the way the script works.

**Comment by rhukster** [comment]
That does appear to load another image on zoom. I don't think GLightbox works that way though.
