### ISSUE TITLE
The Website Font DM Sans wont show on iPhone and iPad

### ISSUE THREAD

**Issue by stbs01** [getgrav/grav-premium-issues#456]
Hi!

I am using a https://github.com/paulmassen/grav-theme-hyde Grav Theme (v0.2.2) with a Premium Lightbox Gallery Plugin (v1.0.6) on a Linux VPS Server. Now I have the following problem with the website:

I have on my website the font installed https://fonts.google.com/specimen/DM+Sans, and it shows right on Macbook / Windows / Android. But on iPhone and iPad the font is different, compare it here:

Google Chrome Macbook:
<img width="1917" alt="Screenshot 2024-07-02 at 18 22 53" src="https://github.com/getgrav/grav-premium-issues/assets/174446128/0f25144f-26f2-4fe1-ad8e-59d91fe9d1c3">

Google Pixel 6 Pro:
![photo_5197523926039780604_y](https://github.com/getgrav/grav-premium-issues/assets/174446128/b5152422-81b6-43fb-a8b9-997e8f1143f1)

iPad 11:
![photo_2024-06-30 19 32 30](https://github.com/getgrav/grav-premium-issues/assets/174446128/e7e9bc3d-78a8-4b1e-b3d1-22709e225df3)

iPhone XR:
![photo_2024-07-02 18 25 37](https://github.com/getgrav/grav-premium-issues/assets/174446128/06b6261d-f6ea-4006-962f-e666ca3c53a1)

Do you have an idea why it happens?

If you go to [http://draft.teimur-bek-safiuli.com/](http://draft.teimur-bek-safiuli.com/works) - you will see what I mean.

Thanks for your help!

Best,
Teimur

studio@teimur-bek-safiuli.com

P.S. I have a pretty experienced guy who helps me to build my artist portfolio website, but here he cant help me anymore, thats why I need your help 🙏🏼

**Comment by rhukster** [comment]
I can't support a question regarding a 3rd party theme. This issue tracker is for issues with premium plugins and Typhoon theme only. 

Try here: https://github.com/paulmassen/grav-theme-hyde/issues
