### ISSUE TITLE
[typhoon] SimpleSearch not seeming to work?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-premium-issues#47]
I am using Typhoon for the first time (such a nice customizable theme!), and I cannot seem to get the SimpleSearch plugin to work:
http://demo.hibbittsdesign.org/grav-skeleton-typhoon-blog-with-git-sync/

Looking at the Typhoon Blog demo site I see the same behaviour for the SimpleSearch box... is this a known issue or am I missing something?
https://demo.getgrav.org/typhoon/blog/

Thanks very much,
Paul

**Comment by w00fz** [comment]
Fixed in Typhoon, will be available with next release. Also the demo has been updated with the fix already.

Cheers,

**Comment by paulhibbitts** [comment]
Awesome, thank you very much @rhukster @w00fz !
