### ISSUE TITLE
Responsive hero image for Typhoon

### ISSUE THREAD

**Issue by tonhaarmans** [getgrav/grav-premium-issues#48]
hi, how would I make the hero image in Typhoon theme responsive? For mobile devices I have created a smaller version, but I don't know how to implement that. I do have the plugin Responsive Images installed...

**Comment by rhukster** [comment]
What do you mean by responsive? It already reduces fine for smaller screens but I think you mean using various images per screen size?

**Comment by tonhaarmans** [comment]
indeed: various images per screen size...

**Comment by rhukster** [comment]
Ok let me get back to you with code sample for that when im at the computer.

**Comment by tonhaarmans** [comment]
ok!

**Comment by rhukster** [comment]
Ok, this would take a bit of editing of the `partials/hero.html.twig`

Currently, Typhoon gets the name fo the hero image and applies the `|hero_image` twig filter to get the media object, then it gets the URL of that media image and assigns it to the `hero_image` variable.  This would have to be modified to actually get the `hero_image` object, which we need for the next part. 

So line 8 of `partials/hero.html.twig` would need to be changed to:

```twig
{% set hero_image = hero_image ?? ((page.header.hero.image|defined(hero_default))|hero_image) %}
```

(basically just remove the `.url` from the end.

Then on line 50 of the same file, we are manually outputting the hero image with a tag, and we were passing the URL:

```twig
<img class="background-image absolute inset-0 object-cover h-full w-full" src="{{ hero_image }}" alt="Hero Image"/>
```

Now to get this to render with retina style images, we have to replace this with some twig that outputs those multiple images.  You could do this manually, but probably the simplest way is to follow the Twig examples of the media docs: 

https://learn.getgrav.org/17/content/media#responsive-images

There are two main ways to handle responsive images.  One is to rely on an `image@2x.jpg` format, and let Grav automatically use that for higher density displays, and make the various 'smaller' images like `image@1x.jpg` and serve those:

```twig
{{ hero_image.sizes('80vw').classes().html(null, 'Hero Image', 'background-image absolute inset-0 object-cover h-full w-full')|raw }}
```

In fact this is backwards compatible, so I'll put it in the next update :)
