### ISSUE TITLE
Font in Typhoon gives internal server error

### ISSUE THREAD

**Issue by tonhaarmans** [getgrav/grav-premium-issues#49]
Hi,
I encountered an internal server error with the font Inter-roman.var.woff2

**Comment by rhukster** [comment]
Hmm. Can you provide a screenshot of where you are seeing the exactly and in what browser?

**Comment by tonhaarmans** [comment]
https://www.wideopenwindows.be/

![image](https://user-images.githubusercontent.com/37418410/107851530-00ad8700-6e0b-11eb-8072-e702f3a3f2db.png)

**Comment by rhukster** [comment]
Ok that error is coming from your web server. Please have a look in your server error logs as they should provide you an exact message as to the cause.  

It’s most likely the server doesn’t know how to serve woff2 extension font files and needs to have that added to its configuration. It depends on what your web server software is though.

**Comment by tonhaarmans** [comment]
Ok thanks!

**Comment by tonhaarmans** [comment]
In fact, I now see that can't be true, since I use also lato-v14-latin-100.woff2 and line-awesome.woff2 and they give no error...

**Comment by rhukster** [comment]
Ok please check the web server error logs.  Those will give more details.

**Comment by tonhaarmans** [comment]
Ok, found this in the error log:

[Sat Feb 13 14:50:47 2021] [error] [client 194.49.59.236] Syntax error in type map, no ':' in /home/vhosts/wideopenwindows.be/httpdocs/user/themes/curiosity/fonts/Inter-roman.var.woff2 for header wof2, referer: https://www.wideopenwindows.be/assets/d9c1b9266c497b551df1a36d531caff5.css

**Comment by tonhaarmans** [comment]
curiosity is the name of my copy of Typhoon...

**Comment by rhukster** [comment]
What web server are you running?

**Comment by rhukster** [comment]
Could be a CORS issue.

**Comment by tonhaarmans** [comment]
That sounds like WAY above my head...

**Comment by tonhaarmans** [comment]
I do know that the security of my site is very, very low. https://www.webpagetest.org/...

**Comment by rhukster** [comment]
Let me do some research and get back to you.  Still not at the computer. Family time :)

**Comment by tonhaarmans** [comment]
sure man, have fun

**Comment by rhukster** [comment]
Ok looks like its an issue with Apache and the name `.var.` in the font. 

* https://github.com/WordPress/twentytwenty/issues/718
* https://serverfault.com/questions/159152/apache-treating-files-with-var-in-their-names-as-type-maps

There are some Apache configuration workarounds, but probably the better solution is to rename the font.  I'll do that shortly.

**Comment by rhukster** [comment]
Fixed for 1.0.10
