### ISSUE TITLE
Typhoon theme - Homepage Side menu

### ISSUE THREAD

**Issue by jachambel** [getgrav/grav-premium-issues#52]
Hello. I'm creating a website with the Typhoon theme and I came across a problem: Even with the option (show_children_in_secondary_menu: true) selected, the secondary menu does not appear on the homepage. Is it a bug? I really need to have a secondary menu on the homepage. How can I do it?

Thank´s

**Comment by rhukster** [comment]
There was a bug with the homepage specifically due to the `route` being `/` and the menu data structure expecting the `rawRoute()`. See the commit above for the simple fix.  I will get a release out next week.

Cheers!

**Comment by jachambel** [comment]
73 / 5000
Resultados da tradução
Fantastic! I will wait for the next update. Good job, thanks.
