### ISSUE TITLE
[Typhoon 1.0.9] Hero display on page settings is not working 

### ISSUE THREAD

**Issue by kiranetph** [getgrav/grav-premium-issues#53]
![image](https://user-images.githubusercontent.com/15226809/108814931-9c4eac80-75ee-11eb-9090-c26649f9de2d.jpeg)

**Comment by rhukster** [comment]
I’ll take a look.

**Comment by rhukster** [comment]
This works for me.  Remember that the setting in Typhoon configuration is a global default.  If you override this in a page it will  still show up even if globally it's off by default.  I tested on a page that didn't have it overridden on the page:

![image](https://user-images.githubusercontent.com/1084697/108895737-3869bb00-75d1-11eb-8940-4856c496a2dc.png)

and just toggled it in the typhoon settings and the setting to `No` did stop it displaying.

**Comment by rhukster** [comment]
You are correct, fixing.

**Comment by rhukster** [comment]
will be in next released (today)
