### ISSUE TITLE
NextGen Content Editor

### ISSUE THREAD

**Issue by PeterB513** [getgrav/grav-premium-issues#54]
I installed the NextGen Content Editor. Because I was struggeling with the use of images with this editor I disabled the NextGen Content Editor and went back to the old editor.

Now I want to go back to the new editor. This is not possible. I enabled the editor but when I select a page the red dot is continuously blinking without any change. I tested also other pages with the same result. Even with new pages. Is it not possible to change from editor during the making of a page or the making of a site? Or is there something else the matter?
What to do?
Thanks,
Peter

**Comment by rhukster** [comment]
Can you open up your developer tools and look in the console. There are probably errors, those errors might be able to tell us what's going on.  Also is it only a specific page, or all pages?  What if you create a new page? If it's a specific page, can you attach a zip of the page folder so we can try to recreate it?

**Comment by rhukster** [comment]
It is possible that what you are seeing is related to a bug in the last couple of Admin plugin releases (now fixed in latest 1.10.6), that caused all the attributes of a YAML to be set to null when you disable a plugin.  The best way to resolve this is to update Admin to latests, and then delete your `user/config/plugins/netgen.yaml` file manually (might require FTP or SSH).

**Comment by PeterB513** [comment]
This works. Thanks.
The only thing is that I don’t see the option Shortcode core which is displayed in the Nestgen demo and description. 
Is there a way to enable this.
Peter

**Comment by PeterB513** [comment]
I found the solution. I had to install the plugin ShortCode Core. 
Is this not an idea to incorporate this in the editor features?

**Comment by rhukster** [comment]
The idea is for plugins to provide their own support for Nextgen rather than the other way around. This makes Nextgen more extensible.  Glad you got it sorted!
