### ISSUE TITLE
Frontend form checkbox false validation fail

### ISSUE THREAD

**Issue by yaroslav-khomyak** [getgrav/grav-premium-issues#55]
I use checkbox in frontend form, which don't need validation. User can check it or not - depending on preferences.

> option1:
            type: checkbox
            label: 'Select option'

When checkbox is checked - I get "Validation failed:" error upon submit.
When checkbox is unchecked - submit is successful.

I tried those options without luck:
_validate: required: false_  
_novalidate: true_

**Comment by w00fz** [comment]
Is this in regard of a premium product or just a generic Grav question? If it is a generic grav question it is best to use the [getgrav/grav@issues](https://github.com/getgrav/grav/issues) repository. If it's about a premium product, where are you trying to add this setting?

Generally speaking, it is not advised to use a `checkbox` type but rather the `toggle`, there's a good example in learn that will resolve your issue (see https://learn.getgrav.org/17/forms/forms/fields-available#toggle-field)
