### ISSUE TITLE
[typhoon] Mobile logo option 

### ISSUE THREAD

**Issue by memiked** [getgrav/grav-premium-issues#59]
As an enhancement, Can you add the option for a second logo just for mobile ? I have used similar function in the Quark template.
Thanks

**Comment by rhukster** [comment]
I shall consider this for a future update.  Good idea, thanks!

**Comment by rhukster** [comment]
FYI i did look into this, but currently there is really not the same need for mobile logo like quark.  In quark the mobile icon is used in the mobile nav.  In Typhoon the mobile nav purposefully doesn't have a logo to ensure there is maximum space for navigation.  

I will still consider it but it will require adding support for a logo in the navigation first.

**Comment by memiked** [comment]
Thank you !!!!!
