### ISSUE TITLE
The delete social icon button is not working

### ISSUE THREAD

**Issue by thilgertbo** [getgrav/grav-premium-issues#6]
I am unable to delete the all the social icons. I press delete and the last  icon vanish. When I press save,  the icons are back.

**Comment by w00fz** [comment]
What Grav version are you using?

**Comment by rhukster** [comment]
This is probably related to the fact that there are 'defaults' in the typhoon yaml.  When you remove all, it uses the defaults because Grav config doesn't save anything. I'm looking into it.

**Comment by rhukster** [comment]
Ok, I decided the best way to handle this was to add an extra toggle to enable/disable displaying of the menu + social icons.  I've implemented this and pushed a release of for version `1.0.5`. This should show up in GPM in < 30 mins.

![Theme: Typhoon  Grav 2020-12-19 at 6 07 27 PM](https://user-images.githubusercontent.com/1084697/102702904-35df9380-4225-11eb-9389-a261f019e9ed.jpg)
