### ISSUE TITLE
[seo-magic] Proxy support for http requests

### ISSUE THREAD

**Issue by izzyu91** [getgrav/grav-premium-issues#60]
When developing a grav site locally with the Symfony Local Web Server (https://symfony.com/doc/current/setup/symfony_server.html) you can't activate the seo-magic plugin when using the built-in proxy for domains (my-domain.wip). The HttpClient cannot resolve the hostname as it does not know about the proxy. This results in an exception on loading at least the plugin configuration page.

Possible solution: Add an optional proxy configuration in seo-magic that is passed to the HttpClient configuration in SEOGenerator.php:143

**Comment by rhukster** [comment]
A simple workaround would be to add an entry in /etc/hosts ?

**Comment by rhukster** [comment]
I've improved Grav's core HTTP Response class by breaking it out of GPM and making it's own HTTP\Client class with full proxy support.  Now everything is controlled by Grav's base configuration for the HTTP Client.  This will require an update to Grav and SEOMagic will, in turn, require that new version.  I expect this to be 1.7.24 (the next release).
