### ISSUE TITLE
[typhoon] Adding support for videos in gallery template

### ISSUE THREAD

**Issue by izumitelj** [getgrav/grav-premium-issues#61]
Enhancement. Since Lightbox plugin already supports videos it would be nice to improve gallery template (modular page), so that it supports adding videos as well.

**Comment by rhukster** [comment]
Not forgotten about this, just been busy with other projects.  Will look at it when i switch gears back to Typhoon.

**Comment by izumitelj** [comment]
No problem! I've just thougth it's easier to tracking issues here, than keeping it in the head or scattered in chats... Thanks :)
