### ISSUE TITLE
[typhoon] Option to open external links (from navigation) in new tab/window

### ISSUE THREAD

**Issue by izumitelj** [getgrav/grav-premium-issues#63]
Enhancement suggestion. Commonly there is a need to have external links open in new tab/window. Unfortunately built-in Grav external page blueprint doesn't support inserting additional `href` attributes like `target` and `rel`. There is also `external_links` plugin but it doesn't recognize links in navigation of Typhoon. 

One solution might be to search links in the `macros.html.twig` for loop (where navigation elements are created), and if the element is external link/page append additional `target="_blank"` to the link tag... Of course it would be better to have it as option because there may be situations where the current behavior is appropriate.

**Comment by rhukster** [comment]
Thanks i will look at adding support for external links in the next update.

**Comment by rhukster** [comment]
Fixed for next update
