### ISSUE TITLE
[typhoon] YouTube as social link in the footer

### ISSUE THREAD

**Issue by BlackScreen** [getgrav/grav-premium-issues#64]
Thank you for Grav and the typhoon theme. Glad to support your awesome work. 

One small thing though:
Would it be possible to add YouTube to the social links in the footer? Would be greatly appreciated. 🙂

**Comment by rhukster** [comment]
Sure i'll add that to the options for next update.

**Comment by BlackScreen** [comment]
> Sure i'll add that to the options for next update.

Perfekt. Thank you! :)
