### ISSUE TITLE
[typhoon]  --> Child --> No configuration in the admin-section 

### ISSUE THREAD

**Issue by anico-sy** [getgrav/grav-premium-issues#66]
Hi

I made a child-theme an I can not edit the 
in the theme-level-configuration
https://getgrav.org/premium/typhoon/docs#theme-level-configuration
in the admin section.

How can I extend the child theme so that I also have the admin section in the child?

Thanks for help and best regards

**Comment by rhukster** [comment]
When you created your child theme did you copy the blueprints file and the yaml configuration file into your child theme? The configuration file needs to be renamed to match your child theme’s name. Also blueprint needs to be update accordingly also.  

If you use devtools to login to create the child theme it will do these tasks for you. 

It should work fine in admin if you have followed all the steps.

**Comment by anico-sy** [comment]
Hi

blueprints.yaml change helped. 
Now I see the configuration in the admin-backend.

>> Also blueprint needs to be update accordingly also.

Do I understand this correctly? When blueprint.yaml in the typhoon theme is updated by you, then I should copy the data over to blueprint.yaml in my theme? So that the options are complete?


By the way, it is this installation which showed the devtool bug.
https://github.com/getgrav/grav-premium-issues/issues/50

**Comment by rhukster** [comment]
Devtools is already released with this fix... using devtools in the future will ensure this does not occur again.
