### ISSUE TITLE
Error on local install

### ISSUE THREAD

**Issue by cmadland** [getgrav/grav-premium-issues#67]
Trying to view ~/blog...

`0 - An exception has been thrown during the rendering of a template ("Trying to access array offset on value of type bool").`

Any thoughts? I've updated to Grav 1.7.8 and Typhoon 1.0.12.

Both local and prod are on the same versions, but the error only shows on local.

**Comment by rhukster** [comment]
Can you turn on the full error messages and provide a screenshot? Either that or past the relevant entry from the `logs/grav.log` file?  That will help determine what's causing the issue.

**Comment by cmadland** [comment]
<img width="964" alt="image" src="https://user-images.githubusercontent.com/12282929/111873799-5e277d00-894f-11eb-9253-e6adfde20937.png">

**Comment by cmadland** [comment]
Ok...I've disabled the 'External Links' plugin, and that resolves the issue.

**Comment by cmadland** [comment]
...and, likely a last update. It appears 'external links' borked because of this badge embed...
```
[![made-with-Markdown](https://img.shields.io/badge/Made%20with-Markdown-1f425f.svg)](http://commonmark.org)
```

**Comment by rhukster** [comment]
Ok, thanks for the follow up.  I think that if it continues to be an issue you should create an issue with the external links plugin repo.
