### ISSUE TITLE
[nextgen-editor] Problem with css-classes

### ISSUE THREAD

**Issue by Juolpo** [getgrav/grav-premium-issues#69]
When we insert an image via "_Shortcode Core > Figure_" and assign a css-class to it, a quotation mark is added to the class name (at the beginning and at the end) each time it's saved. So _.class_ becomes _."class"_ and then _.""class""_ after saving.

[![Error-nextgen.jpg](https://i.postimg.cc/BnHXK016/Error-nextgen.jpg)](https://postimg.cc/3krKsz15)

A weird behaviour. What can we do or what are we doing wrong?

**Comment by Juolpo** [comment]
Hey @rhukster or @w00fz 
can you please help me or do you have an idea what I´m doing wrong. 
We need to go online in the near future and so grav is unusable for us.

Thank you in advance.

**Comment by rhukster** [comment]
It's not your fault, it does look like a bug.

**Comment by w00fz** [comment]
Hey @Juolpo is it possible this bug comes from Gantry escaping the classname? I just tested on a regular Grav theme and I cannot reproduce the double quotation.

Is it only happening with the Figure shortcode or is it also happening with other ones? Such as the Div shortcode?

**Comment by w00fz** [comment]
FYI I tried also with the Gantry Helium Skeleton and I am unable to reproduce the issue. 

Feel free to provide additional details if this is still an issue.
