### ISSUE TITLE
[nextgen-editor] PDF inline in page

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-premium-issues#76]
use embed or iframe to inline a PDF via a shortcode.

**Comment by w00fz** [comment]
I remember I helped @paulhibbitts with something similar where he was able to embed widgets from a remote URL. The same concept should apply for PDFs I believe. Also I think the browser shortcode could be reused for this same aspect as it uses iframes as well.

**Comment by w00fz** [comment]
We went through this privately and realized it's already possible to do.
