### ISSUE TITLE
[Typhoon] Support SVG in the Image-Block Page Template

### ISSUE THREAD

**Issue by red2678** [getgrav/grav-premium-issues#78]
It would be great if we could use an SVG for the "image."

**Comment by rhukster** [comment]
Change line 4 of `templates/modular/image-block.html.twig` to: 

```
{% set image = page.media.files[page.header.image].url|defined(page.media.images|first.url) %}
```

notice `page.media.files` instead of `page.media.images`.

**Comment by red2678** [comment]
Awesome, thanks!
