### ISSUE TITLE
[instagram-feed] New API make hard/impossible to follow the tutorial.

### ISSUE THREAD

**Issue by softyoda** [getgrav/grav-premium-issues#79]
There have been changes in the Facebook and Twitter development API, so I don't know how to add the token or how to add a test-user.

![1034_firefox_amcgi_-_Roles_-_Facebook_for_Developers_-_Mozilla__30_03_2021_19h56(3204x942)_Nbda](https://user-images.githubusercontent.com/13988751/113039245-bfddb780-9197-11eb-8ed4-9a58337ba2d0.jpg)
![1041_firefox_Mozilla_Firefox_30_03_2021_20h36(430x76)_ZDTy](https://user-images.githubusercontent.com/13988751/113039249-c10ee480-9197-11eb-8097-f4a15a0241e1.jpg)
![1036_firefox_amcgi_-_Dashboard_-_Facebook_for_Developers_-_Mozi_30_03_2021_20h01(2378x1354)_j55p](https://user-images.githubusercontent.com/13988751/113039251-c10ee480-9197-11eb-86f7-cbe7c3e2c5aa.jpg)
![1035_firefox_Applications_et_sites_web_•_Instagram_-_Mozilla_Fi_30_03_2021_19h56(2993x776)_7Xd6](https://user-images.githubusercontent.com/13988751/113039254-c1a77b00-9197-11eb-98a7-2bbc7d33b7b7.jpg)

**Comment by w00fz** [comment]
Yeah they just recently changed the whole UI and we need to update the documentation screenshots accordingly.

**Comment by w00fz** [comment]
I updated the docs and make a few points clearer
