### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by thilgertbo** [getgrav/grav-premium-issues#8]
Could you create a documentation how to use the svg-icons with the feature module?

**Comment by rhukster** [comment]
In Typhoon, there's a modular twig template located at `templates/modular/features.html.twig`.  Staring on line 9, you will see:

```twig
        {% for feature in page.header.features %}
                <div class="flex duration-300 transform hover:scale-105">
                {% if page.header.variation == 'vertical' %}

                    <div class="flex flex-col w-full rounded-md group hover:bg-gray-100 dark:hover:bg-gray-800">
                        {% if feature.link %}
                        <a class="group-hover:text-primary dark:group-hover:text-primary" href="{{ url(feature.link) }}">
                        {% endif %}
                            <div class="text-gray-500 group-hover:text-primary rounded-md p-3 text-center">
                                    {{ svg_icon(feature.icon, 'w-16 h-16 stroke-current stroke-3/2 mx-auto')|raw }}
                            </div>
```

Here you can see that we're looping over the `page.header.features` and assigning each entry to `feature`. Then at the bottom of the snippet you will see the `svg_icon()` twig function called, that passes the name of the icon, and then takes a second argument of a string Tailwind classes to give the correct stroke, color etc.

Does that help?

**Comment by rhukster** [comment]
Added this to the docs.
