### ISSUE TITLE
[Typhoon] Feature request: Support for multilingual sites in the theme.

### ISSUE THREAD

**Issue by Eihrister** [getgrav/grav-premium-issues#81]
Hello!

One of the (to me) major powers of Grav is that it's so beautifully multilingual.
The theme, unfortunately, does not allow for much in the multilingual area.

- "Menu Links" in the footer can only be in one language, set in stone for all languages.
- "Footer Copyright" is a nice one to add little things, but is also only just one language.

I would also really enjoy having a language switcher somewhere there, for instance in the center, that perhaps looked like the theme color switcher (system/dark/light). Since selecting a language is not something you'd do very often. As it is now, we'd have to install the LangSwitcher plugin and then manually edit templates, so I feel it would be a great addition to the overall experience.

I myself am Dutch, use English most of the time for online things, and my in-laws speak Portuguese and Spanish, so multilingual support is great!

Kind regards,

Daniël

**Comment by Eihrister** [comment]
Oh, not related, but there's a typo in "Instagram" in the dropdown of the "Social Links"-section. Written "Instragram" there,

**Comment by rhukster** [comment]
I know that Typhoon needs some multi-language love.  I'll update this ticket when that gets completed.

I've also fixed that typo.. thanks.

**Comment by rhukster** [comment]
I plan on releasing an update tomorrow.  Basically i've got logic that will use a dedicated footer modular page if available, that way you can translate it for various languages making it fully multi-lang compatible.  If not found, it uses the default settings from the theme for compatibility.

Same goes for the notices.

Also i've moved all the strings to the en.yaml language file.  This will make all the labels translatable.

**Comment by Eihrister** [comment]
Hi again! Thank you so much- however, did the language switcher ever make it in? Because with the current langswitcher plug-in it's a bit difficult to get it shown, and it would be really nice to just check a box somewhere and have it integrated or built in to the core or theme ":) Ttat was the original (intended) reason for my raised issue.
