### ISSUE TITLE
Making sticky work has broken slick slider

### ISSUE THREAD

**Issue by danjames68** [getgrav/grav-premium-issues#83]
This may not be strictly Typhoon related but I'm using Typhoon so I'm asking the question here.

I am using KenWheeler's Slick Slider in a couple of places in my site - an image preview slide show and a reviews slider. I added them and they were both working well. I added the js and css like this:

``` 
 {% block stylesheets %}
    {% do assets.addCss('theme://build/css/site.css') %}
    {% set tailwind_theme %}
      {% include 'partials/theme.css.twig' %}
    {% endset %}
    {% do assets.addInlineCss(tailwind_theme) %}
      {% do assets.addCss('theme://css/slick/slick.css') %}
      {% do assets.addCss('theme://css/slick/slick-theme.css') %}
  {% endblock %}

  {% block javascripts %}
    {% do assets.addJs('theme://js/alpine.js', {loading: 'defer'}) %}
    {% do assets.addJs('theme://js/appearance.js', {group: 'bottom'}) %}
    {% do assets.addJs('theme://js/slick.min.js', {group: 'bottom'}) %}
  {% endblock %}

  {% block assets deferred %}
  {{ assets.css() | raw }}
  {{ assets.js() | raw }}
  {% endblock %}
```

The review implementation looks like this, as a modular page (with the js inline as I'm still developing):

```{% extends 'modular/partials/base.html.twig' %}

{% block module_content %}

<div class="w-full bg-burple-100 rounded-md pt-12 py-8 relative">
    <div class="reviews">
        {% for review in page.header.reviews %}
        <div class="w-full text-center px-16 md:px-24 lg:px-32 {{ prose_style }}">
            <div class="flex flex-row justify-center -mb-8">
            {% for i in 1.. review.stars %}
                {{ svg_icon('heroicons/solid/star.svg', 'h-6 w-6 text-primary stroke-3/2')|raw }}
            {% endfor %}
            </div>
            <h3 class="font-serif">&ldquo; {{ review.title}} &rdquo;</h3>
            {{ review.text|markdown }}
            <span class="text-sm text-gray-600">
                {{ review.client }}  
                staying in <a href="{{ base_url }}{{ review.link }}" alt="{{ review.property }}">{{ review.property }}</a>. 
                <em>{{ review.date is empty ? "" : review.date|date("M Y") }}</em>
            </span>
        </div>
        {% endfor %}
    </div>
</div>
    <div class="w-full text-center justify-center">
    <span class="text-center text-sm text-gray-600 hover:underline"><a href="https://g.page/invitationtotuscany" target="blank">Click here to see more of our reviews on Google</a></span>
    </div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.reviews').slick({
        arrows: true,
        dots: true,
        infinite: true,
        speed: 300,
        slidesToShow: 1,
        autoplay: true,
        autoplaySpeed: 8000,
    });
  });
</script>

{% endblock %}
```

Both implementations were working fine - and they've been up for a week or so.
Yesterday I decided the villa page would be better with a booking widget that follows the client down the page, so I went to implement a sticky panel in the sidebar. I ran into the usual `overflow-hidden` problems and while testing, tried just removing this line from `base.html`:

`:class="[ show_mobile_nav ? 'overflow-hidden' : '', theme ]" class="overflow-x-hidden">`

After this. the sticky panel worked perfectly, but the sliders stopped working. So I restored the original `base.html` file but they're still not working. 

I've checked the files are all getting pulled in, and I've restored all files back to before the sticky changes, but the sliders have just stopped working. The only **other** thing I did while working on this was to update the Lightbox plugin - so I've also tried turning the plugin off, in case there was something in there.

I'm stumped, don't know where to look next.

**Comment by danjames68** [comment]
After further investigation I have found:

```
Uncaught ReferenceError: $ is not defined
    at maison-de-timole:765
(anonymous) @ maison-de-timole:765
slick.min.js:1 Uncaught ReferenceError: jQuery is not defined
    at slick.min.js:1
    at slick.min.js:1
```

The top reference is the function: `  $(document).ready(function(){`

The lower one is 

```
!function(i){"use strict";"function"==typeof define&&define.amd?define(["jquery"],i):"undefined"!=typeof exports?module.exports=i(require("jquery")):i(jQuery)}(function(i){"use strict";var e=window.Slick||{};(e=function(){var e=0;return function(t,o){var s,n=this;n.defaults={accessibility:!0,adaptiveHeight:!1,appendArrows:i(t),appendDots:i(t),arrows:!0,asNavFor:null,prevArrow:'<button class="slick-prev" aria-label="Previous" type="button">Previous</button>',nextArrow:'<button class="slick-next" aria-label="Next" 
```

**Comment by danjames68** [comment]
I added `   {% do assets.addJs('jquery', 101) %}` back to `base.html.twig` and this solves it, but I'm puzzled as to why it stopped working. I did also update the admin plugin so I don't know if that changed anything. 

But I also have the original `base.html.twig` file and `jquery` wasn't required in that, though it still is in the Quark theme `base.html.twig`. 

Am I missing something obvious?

**Comment by w00fz** [comment]
Typhoon does not require jQuery and so it’s not provided with the base template. We rely on very minimal js for the theme and we accomplish it vis Alpine JS, which is a fraction of the size of jQuery.

However, you are definitely on the right track here, nothing stops you from adding jQuery to your typhoon copy base template and use any jQuery dependent libraries such as the slider you use. The solution you went for is what I would ha e suggested also.

**Comment by danjames68** [comment]
Thanks Djamil,

I hadn’t realised - and am still curious as to why it originally worked, this site has always been developed on my child theme of Typhoon.

Still, resolved now so all is well. Thanks.

Best,

Dan

**Comment by w00fz** [comment]
Could be that you had some plugin requiring jQuery and loading it, making the slider work.
