### ISSUE TITLE
[Typhoon] Is tailwind import wrong?

### ISSUE THREAD

**Issue by mouradsm** [getgrav/grav-premium-issues#84]
When I started my project using version 1.1.0 of Typhoon, I could see that the order of importing the tailwind directives is different from the order defined in the  [TailwindCSS](https://tailwindcss.com/docs/installation#include-tailwind-in-your-css) documentation. Was this intentional? It's causing me some problems when using the utilities classes since the `@tailwind base` directive resets everything that was previously applied to the `@tailwind utilities` directive.

```
# Typhoon site.css 
@tailwind utilities;
@tailwind base;
@tailwind components;
```

**Comment by w00fz** [comment]
Actually that's a valid good point @mouradsm , I think you are right. I have stumbled upon the same issue and was going to raise an issue so I wouldn't forget.

I had to change this on a project in this order to get it working as expected:

```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by rhukster** [comment]
You are correct, this has changed, and it is important to maintain proper order.  I've fixed this for the next release.
