### ISSUE TITLE
Save Failed: Array to string conversion after update Grav 1.7.11 en admin plugin 1.10.11

### ISSUE THREAD

**Issue by jeffreydewaal** [getgrav/grav-premium-issues#85]
After de update to Grav 1.7.11 en admin plugin 1.10.11 I got an error when I try to safe a user in account in the admin panel. "Save Failed: Array to string conversion"

When I try to safe a page in the admin panel "Save Failed: ucfirst() expects parameter 1 to be string, array given"

**Comment by 3li0** [comment]
Same issue here. Unable to add any content via the plugin.

**Comment by rhukster** [comment]
Is this an admin and pages issue in general? Is there a reason you opened in premium issues?

**Comment by jeffreydewaal** [comment]
I had a link to premium issues. There is no special reason for adding to premium issue. Sorry. Next time I report in the Grav issue .

**Comment by rhukster** [comment]
There's a similar issue that has been reported in admin plugin.  So closing this one.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/issues/2115
