### ISSUE TITLE
[nextgen-editor] Feature request: Allow configuration of media sources

### ISSUE THREAD

**Issue by bnjmnhssnn** [getgrav/grav-premium-issues#89]
The **Insert media** button only works with a restricted set of sources and URL patterns, probably the [CKEditor defaults](https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html#media-providers) . With CKEditor, you can [define additional sources](https://ckeditor.com/docs/ckeditor5/latest/api/module_media-embed_mediaembed-MediaEmbedConfig.html#member-extraProviders).

This functionality should be exposed as config setting, or alternatively, the docs should contain instructions how to do this with inline Javascript (if possible).

**Comment by w00fz** [comment]
This is fixed in v1.1.0, thank you for the suggestion!

https://getgrav.org/premium/nextgen-editor/docs#extra-media-embed-providers
