### ISSUE TITLE
Typhoon documentation when not using the admin plugin

### ISSUE THREAD

**Issue by sebastian0119** [getgrav/grav-premium-issues#9]
Hi there,

There already is a [bunch of documentation](https://getgrav.org/premium/typhoon/docs), but it is focused on the admin plugin. Most of it can be deducted for the manual configuration in the `typhoon.yaml`, but additional / separate documentation for users who (for any reason) do not install the admin plugin would be appreciated.

**Comment by w00fz** [comment]
Would it help if `typhoon.yaml` had documentation comments like the default ([`system.yaml` in Grav](https://github.com/getgrav/grav/blob/develop/system/config/system.yaml))  does?

**Comment by sebastian0119** [comment]
Sure, that would be great!

**Comment by rhukster** [comment]
This has been added for next release: https://github.com/trilbymedia/grav-theme-typhoon/commit/a10a69b3c3e19c5c788e5cc5b5863f21871996a2
