### ISSUE TITLE
double space = new line is not supported

### ISSUE THREAD

**Issue by Gurbuuz** [getgrav/grav-premium-issues#93]
When editing a text in expert mode using double space creates a new line. But moving to "normal" mode will completely ignore it, 

What I want:

    Text
    Like
    This

But it transforms into this:

    Text Like This

I’ve tried using the <br> tag inside markdown but that transforms the text to :

    Text

    Like

    This

**Comment by w00fz** [comment]
This is fixed in v1.1.0, thank you!
