### ISSUE TITLE
[nextgen-editor] Copying multiple sentences not supported

### ISSUE THREAD

**Issue by Gurbuuz** [getgrav/grav-premium-issues#96]
Hi, 

As you may suspect I'm spending a lot of time trying to transform my pages edited in "expert" mode to work inside "normal" mode with Grammarly. 

The current issue I'm running into is in regards to this tag, ``` which has transformed into a line to copy ```.

While this works great for one line sadly it doesn't work that great for multiple sentences.. 

How it looks inside Expert mode: 
![image](https://user-images.githubusercontent.com/36448058/116869990-00ef3e80-ac12-11eb-987c-234786198a15.png)

And inside the page it looks like this: 
![image](https://user-images.githubusercontent.com/36448058/116870071-1ebca380-ac12-11eb-8119-0e54965e0260.png)

But if I now open this in Normal mode to make Grammarly work it changes this beautiful thing into this, **Located at the bottom of the page all of the sudden.** : 
![image](https://user-images.githubusercontent.com/36448058/116870161-490e6100-ac12-11eb-9417-4d5103aa393c.png)

and if I by mistake save the page the layout of this beautiful copy line will turn into this where the copy symbol on the top right is located at the end of the page instead of the previous view.: 
![image](https://user-images.githubusercontent.com/36448058/116870237-722ef180-ac12-11eb-9801-fb86deb5b655.png)

If I now return to Expert mode then my beautiful layout will be transformed into this again located at the bottom of the page: 
![image](https://user-images.githubusercontent.com/36448058/116870332-ad312500-ac12-11eb-9ba9-eb0f062f2ea0.png)

**Comment by w00fz** [comment]
Can you paste the text here so it’s easy for me to copy?

also, with latest admin release, you should be able to use grammarly and spellchecking even in expert mode

**Comment by Gurbuuz** [comment]
Making Grammarly available in Expert mode is by far the easiest solution for me. I cannot make it to work though could you help me out with this? 

This is the view from expert mode, 
![image](https://user-images.githubusercontent.com/36448058/116971227-88dc5380-acb9-11eb-9577-5f51cfbab535.png)


and this is the view from normal mode: 
![image](https://user-images.githubusercontent.com/36448058/116971273-9a256000-acb9-11eb-9902-452f02370112.png)

**Comment by w00fz** [comment]
Yeah you are right for some reasons Grammarly is not working with expert mode. Expert mode uses the default editor which is CodeMirror and it seems to have some issues.

I can also confirm the issue you described, unfortunately I don't know quite yet what's causing that. Some of the rules is breaking out the expect output and I am trying to figure out which bit is. 
Bad news is there are a lot of different rules that make NextGen Editor and so this might take a while to figure out!

**Comment by Gurbuuz** [comment]
Understood, being able to use Grammarly was sadly the only reason for us as a company to upgrade in Grav. We're currently in the evaluation stage and it seems to me that we need to make a lot of sacrifices with our pages(destroy the layout) to have decent grammar. 

That is not the optimal case and I'm starting to question our decision behind this upgrade.. 

Do you think it's solvable to make it possible in "expert mode"? That would really be valuable

**Comment by w00fz** [comment]
Really the most reliable way would be to get some sort of RAW mode where all you see is a plain and simple `textarea` with your content in it, instead of CodeMirror. Then you would be able to do your raw editing as well as use the power of built-in spellchecking and extensions such as Grammarly.
This, of course, would be at the sacrifice of the nicer UI and styling you get with the current Expert mode editor.

I can see be something we built into Grav as an option, so you can pick CodeMirror or plain Textarea, but it does go beyond the scope of NextGen.

Ideally though, the issue you brought up I would like to get resolved within NextGen Editor, it is just not something I can guarantee I will be able to get to you quickly.

**Comment by Gurbuuz** [comment]
Ok great, hearing that there's an option out there being worked on calms me. If this means I will in no way sacrifice the styling inside the website I'm all for it. I honestly don't care about an ugly UI experience as I can jump back to expert mode if needed. 

I understand that this might take some time to implement, what would be a likely timeline for this to be released? When should I expect it?

**Comment by Gurbuuz** [comment]
Hi is there an update on this topic?

**Comment by w00fz** [comment]
Sorry @Gurbuuz, unfortunately this is a bigger effort than anticipated and I don't ave an ETA for you atm.

**Comment by Gurbuuz** [comment]
Hi @w00fz, no worries. Knowing that it is being worked on is enough information for me atm. 

Looking more than forward to this update as I'm super happy with everything else.

**Comment by w00fz** [comment]
Hi @Gurbuuz I have now released v1.1.4 which includes a new source code editor. This might not necessary resolve the issue of code getting converted to markdown and differently than how you expected, but that's how NextGen is meant to work. 
However now you can write the source code directly in the editor by enabling it in the toolbar, which will allow you to review/edit and preserve spell checking, and you wont need to switch to Expert mode either.

More details: https://getgrav.org/premium/nextgen-editor/docs#editing-source-code-advanced
