### ISSUE TITLE
[typhoon] New footer system not working

### ISSUE THREAD

**Issue by red2678** [getgrav/grav-premium-issues#98]
I have tried to get the new footer system working. I updated my theme and have made a page as outlined in the [docs](https://getgrav.org/premium/typhoon/docs#footer):

> Save location: user/pages/_footer (type: modular/footer)

However, my theme never finds the newly created page. I just keep getting this:

> NOTE: Footer Page as defined above cannot be found or is not a valid "modular/footer" type, using theme configuration below:

So, I have modified my theme. But, I do have the non-modified version installed on my Grav instance. It, the non-modified version, also does **not** find the newly created _footer page. Are there any other steps to get this working that I am missing other than creating the page?

Theme version: **v2.0.1**
 Grav version / admin plugin version: **v1.7.14 / v1.10.14**

Reproduction Steps:
I should mention I am doing this from ddev on my local machine currently. 

1. Create a local instance of Grav on your machine using [ddev](https://learn.getgrav.org/17/webservers-hosting/local-development-with-ddev#:~:text=ddev%20is%20an%20open%2Dsource,%2C%20WordPress%2C%20and%20GravCMS%20sites.)
2. Install Typhoon v2.0.1
3. Verify you are using the "non-paged" version of the footer
4. Create a new page as outlined [here](https://getgrav.org/premium/typhoon/docs#footer)
5. Go back to the theme configuration and see if it finds the new page
6. If yes to 5, verify the page content is displayed in the footer

Maybe it has something to do with my version of the theme. I do merge in new changes every time the theme gets updated. Perhaps something has been merged incorrectly I suppose. I have few merge conflicts so new changes usually just pull right in. I have done my best to verify that I merged 2.0.1 in full. The strangest thing is the vanilla version of Typhoon installed also does not find the page. Thanks for any assistance!

**Comment by rhukster** [comment]
is your footer page called: `_footer/footer.md` ?

**Comment by rhukster** [comment]
In my case i created a page called: `user/pages/modules/_footer/footer.md` as shown here:

<img width="1373" alt="CleanShot 2021-05-10 at 17 33 03@2x" src="https://user-images.githubusercontent.com/1084697/117736832-cb1ffc00-b1b5-11eb-9c19-1a0d14e614b1.png">

Then in my theme configuration i've configured it to use the modular route:

```yaml
footer_page_route: /modules/_footer
```

**Comment by red2678** [comment]
> if you don't have that modules/ folder at the root of pages, you should have the file user/pages/_footer/footer.md and then reference it with: footer_page_route: /_footer

D'oh. That was it. Many thanks! Sorry, while I am not new to CMS systems, I am new to Grav. Is it a common/best practice to create that folder if I may ask? Thanks!!

**Comment by red2678** [comment]
Ah, I like it. I can see how it would help keep things orginized. 

If I am correct, the docs don't make mention of that folder. Again, I want to stress how new I am to Grav. Perhaps changing [that image ](https://getgrav.org/premium/typhoon/docs#footer) to use the modules folder or no modules folder would help newbies like me not bother you guys. 

Thanks for the assistance!
